### DISCUSSION TITLE
Issues found in  Helm release selenium-grid to v0.30.0

### DISCUSSION THREAD

**Discussion by rajat2911** [SeleniumHQ/docker-selenium#2233] [General]
The selenium-grid-patch-scaledobjects-finalizers pod is having some issues due to which the deployment is not coming up, can see errors in logs: error: no objects passed to apply.
```
STDERR:
  coalesce.go:289: warning: destination for selenium-grid.nodeConfigMap.extraScripts.nodePreStop.sh is a table. Ignoring non-table value ()
  coalesce.go:289: warning: destination for selenium-grid.nodeConfigMap.extraScripts.nodeProbe.sh is a table. Ignoring non-table value ()
  coalesce.go:289: warning: destination for selenium-grid.nodeConfigMap.extraScripts.nodeProbe.sh is a table. Ignoring non-table value ()
  coalesce.go:289: warning: destination for selenium-grid.nodeConfigMap.extraScripts.nodePreStop.sh is a table. Ignoring non-table value ()
  Error: UPGRADE FAILED: post-upgrade hooks failed: 1 error occurred:
  	* timed out waiting for the condition
COMBINED OUTPUT:
  coalesce.go:289: warning: destination for selenium-grid.nodeConfigMap.extraScripts.nodePreStop.sh is a table. Ignoring non-table value ()
  coalesce.go:289: warning: destination for selenium-grid.nodeConfigMap.extraScripts.nodeProbe.sh is a table. Ignoring non-table value ()
  coalesce.go:289: warning: destination for selenium-grid.nodeConfigMap.extraScripts.nodeProbe.sh is a table. Ignoring non-table value ()
  coalesce.go:289: warning: destination for selenium-grid.nodeConfigMap.extraScripts.nodePreStop.sh is a table. Ignoring non-table value ()
  Error: UPGRADE FAILED: post-upgrade hooks failed: 1 error occurred:
  	* timed out waiting for the condition```

**Comment by VietND96** [comment]
May I know some more info?
The previous version that worked before you upgraded to v0.30.0
Are you using KEDA in sub-chart or an existing KEDA deployed separately (if so, which KEDA version)

Can you also `kubectl logs selenium-grid-patch-scaledobjects-finalizers` to see what wrong in that pod?

**Reply by rajat2911** [reply]
Hello @VietND96  yes we are using KEDA separately and the version is 2.14.0 . 
Below are the values i am using. 
```
autoscaling:
  enableWithExistingKEDA: true
#global:
#  seleniumGrid:
#    logLevel: FINE
  scaledJobOptions:
    scalingStrategy:
      # default stategy forces pod termination which runs the pod prestop hook - https://keda.sh/docs/latest/concepts/scaling-jobs/
      # The prestop hook starts the drain, which allows a job to finish successfully within $terminationGracePeriodSeconds
      strategy: default
```
Logs are as below :
```
{
insertId: "xxxxxxxx"
labels: {
compute.googleapis.com/resource_name: "xxxxxxxx"
k8s-pod/controller-uid: "xxxxxx"
k8s-pod/job-name: "selenium-grid-patch-scaledobjects-finalizers"
}
logName: "projects/xxxxxx/logs/stderr"
receiveTimestamp: "2024-04-29T05:04:21.089553690Z"
resource: {
labels: {
cluster_name: "xxxxx"
container_name: "selenium-grid-patch-scaledobjects-finalizers"
location: "xxxxxxx"
namespace_name: "selenium"
pod_name: "selenium-grid-patch-scaledobjects-finalizers-7wcks"
project_id: "xxxxx"
}
type: "k8s_container"
}
severity: "ERROR"
textPayload: "error: no objects passed to apply"
timestamp: "2024-04-29T05:04:19.461339015Z"
}```
