### DISCUSSION TITLE
Github Actions: Mounting volumes to retrieve downloaded files

### DISCUSSION THREAD

**Discussion by hikouki-gumo** [SeleniumHQ/docker-selenium#2315] [Q&A] [answered]
I followed ```https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#mounting-volumes-to-retrieve-downloaded-files```, I confirm this workaround work in my local machine.

I'm trying to setup in Github actions. I have a container to run job (job_container) and a container to provide Selenium Service (selenium_container). After chown, the permission looks fine from job_container:

```
$ ls -lah ${GITHUB_WORKSPACE}/target/Downloads
drwxr-sr-x  2   1200   1201 4.0K Jul 20 05:32 .
drwxr-sr-x 10 hikouki hikouki 4.0K Jul 20 05:35 ..
```

After create selenium_container with volume, the owner is root, not seluser as expected -> does not have permission to write downloaded files.

```
$ docker exec ${CONTAINER_ID} ls -lah /home/seluser/Downloads
drwxr-xr-x 2 root    root       6 Jul 20 05:32 Downloads
```

Could someone point where am I wrong here?

My workflow looks like this:
```
jobs:
  run:
    runs-on:
      - self-host-runner

    container:
      image: ${MY_RUNNER_CONTAINER_IMAGE}
      options: --user 1001
      volumes:
        - /run/docker:/run/docker
      env:
        ...

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        run: |
          ./build.sh

      - name: Provide Selenium Grid
        run: |
          mkdir "$GITHUB_WORKSPACE/target/Downloads"
          sudo chown 1200:1201 "$GITHUB_WORKSPACE/target/Downloads"
          docker run --rm -d -p 4444:4444 -p 7900:7900 --network ${{ job.container.network }} --network-alias standalone-selenium --shm-size="2g" -v "$GITHUB_WORKSPACE/target/Downloads":"/home/seluser/Downloads"  selenium/standalone-chrome:latest

      - name: Run test
        run: |
          ./test.sh
      
```
