### DISCUSSION TITLE
RBAC Issues with Selenium Grid Helm Chart and Keda Autoscaling: How to Resolve or Bypass RBAC Restrictions?

### DISCUSSION THREAD

**Discussion by nadolualex** [SeleniumHQ/docker-selenium#2389] [Q&A]
Tried to deploy a selenium-grid Helm chart with autoscaling functionality using Keda, but encountered RBAC issues related to `rbac.authorization.k8s.io`, getting the following error: `resource rbac.authorization.k8s.io:ClusterRole is not permitted in project`. I observed errors in several roles, including `ClusterRole`, `ClusterRoleBinding`, `Role`, and `RoleBinding`. I was wondering if there is any way to enable autoscaling for `selenium-grid` without RBAC because if I disable it, the Keda pods are refusing to start.

**Comment by VietND96** [comment]
Set this config key to false.
autoscaling.patchObjectFinalizers.enabled

**Reply by nadolualex** [reply]
I previously tried setting that to false, but unfortunately, it did not disable RBAC.

**Reply by VietND96** [reply]
Are you using the latest chart version?

**Reply by VietND96** [reply]
If possible, can you try a dry run with `helm template`, output all YAML rendered (remove secret info if necessary), and provide that output so that I can understand it further?

**Reply by nadolualex** [reply]
> Are you using the latest chart version?

yes, I am using the `0.35.2`  version of the helm chart

**Reply by nadolualex** [reply]
> If possible, can you try a dry run with `helm template`, output all YAML rendered (remove secret info if necessary), and provide that output so that I can understand it further?

Couldn't attach the file, hope it helps

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keda-operator    
    helm.sh/chart: keda-2.15.1
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.15.1
    app.kubernetes.io/instance: release-name
--
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keda-operator-minimal-cluster-role    
    helm.sh/chart: keda-2.15.1
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.15.1
    app.kubernetes.io/instance: release-name
--
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keda-operator-external-metrics-reader    
    helm.sh/chart: keda-2.15.1
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.15.1
    app.kubernetes.io/instance: release-name
--
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keda-operator-webhook    
    helm.sh/chart: keda-2.15.1
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.15.1
    app.kubernetes.io/instance: release-name
--
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-operator    
    helm.sh/chart: keda-2.15.1
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.15.1
    app.kubernetes.io/instance: release-name
--
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-operator-minimal    
    helm.sh/chart: keda-2.15.1
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.15.1
    app.kubernetes.io/instance: release-name
--
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-operator-system-auth-delegator    
    helm.sh/chart: keda-2.15.1
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.15.1
    app.kubernetes.io/instance: release-name
--
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-operator-hpa-controller-external-metrics    
    helm.sh/chart: keda-2.15.1
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.15.1
    app.kubernetes.io/instance: release-name
--
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-operator-webhook    
    helm.sh/chart: keda-2.15.1
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.15.1
    app.kubernetes.io/instance: release-name
--
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: keda-operator-certs    
    helm.sh/chart: keda-2.15.1
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.15.1
    app.kubernetes.io/instance: release-name
--
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-operator-certs    
    helm.sh/chart: keda-2.15.1
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.15.1
    app.kubernetes.io/instance: release-name
--
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-operator-auth-reader    
    helm.sh/chart: keda-2.15.1
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.15.1
    app.kubernetes.io/instance: release-name
```
