### DISCUSSION TITLE
Deploying Selenium Grid with ArgoCD

### DISCUSSION THREAD

**Discussion by KyriosGN0** [SeleniumHQ/docker-selenium#2569] [Q&A] [answered]
we deploy selenium grid's helm chart with argoCD, we have been wondering about removing the helm hooks from the scaled jobs resources, has anyone done that? is it safe? 
the main reasoning is that sometimes we want to make changes to those resources but argocd doesn't track them since they are deployed with helm hooks

**Comment by farioas** [comment, marked as answer]
I'm also using ArgoCD, so I've disabled the helm hooks, no problems at all:
```
autoscaling:
  patchObjectFinalizers:
    enabled: false # doesn't work with argocd
  annotations: ! # remove helm hooks
  authenticationRef:
    annotations: ! # remove helm hooks
```
