### DISCUSSION TITLE
How to set tolerations for KEDA

### DISCUSSION THREAD

**Discussion by batbattur** [SeleniumHQ/docker-selenium#2609] [Grid Autoscaling] [answered]
How do I set tolerations for the keda-operator and keda-operator-metrics-apiserver?

Currently I use the KEDA operator and metrics api server from the chart (without using external) as following:

```
    autoscaling:
      enabled: true
      scalingType: deployment
      scaledOptions:
        minReplicaCount: 1
        maxReplicaCount: 5
        pollingInterval: 20
        triggers:
        - type: selenium-grid
          metadata:
            url: "http://selenium-grid-selenium-hub.selenium:4444/graphql"
            browserName: 'chrome'
            platformName: 'linux'
```

However, I am unsure how to set tolerations for the keda-operator and keda-operator-metrics-apiserver? 
I noticed that there are some values for KEDA in the following but nothing to set for the tolerations. https://github.com/SeleniumHQ/docker-selenium/blob/967cb27a67ed54f18a0836690341c741fd757761/charts/selenium-grid/values.yaml#L1987-L2010 

If I want to set tolerations, does it mean I have to create my own external keda and set the tolerations manually?
