### DISCUSSION TITLE
Node doesn't register with hub when autoscaling is enabled.

### DISCUSSION THREAD

**Discussion by devqaio** [SeleniumHQ/docker-selenium#2615] [Grid Autoscaling] [answered]
Hi,

I am unsing below values.yaml to install helm chart (0.39.1) on minikube for learning. However, the node pod (Chrome in this case) stucks at "Sending Registration Event". But when the autoscaling is disabled, I can see the node available to use. What am I missing to establing the connectivity between node and hub with autoscaling enabled.
```

autoscaling:
  enabled: true
  scaledOptions:
    minReplicaCount: 1
    maxReplicaCount: 4
    pollingInterval: 20

firefoxNode:
  enabled: false

edgeNode:
  enabled: false

crossBrowsers:
  chromeNode:
    - nameOverride: '{{ $.Release.Name }}-node-chrome-120'
      imageTag: '120.0'
      hpa:
        platformName: 'Linux'
        browserVersion: '120.0'

```

![image](https://github.com/user-attachments/assets/512950a9-e2d3-4ed5-ade5-5e5f050fabeb)

Upon checking the logs in Hub, I see below exception which I feel is not related to node register

![image](https://github.com/user-attachments/assets/849fe9b6-b14c-4ca5-a5f8-d3716eb6cec3)

Thank you

**Comment by VietND96** [comment]
Looks like image tag 120.0 was using an old selenium-server.jar to start Node, where a config is not compatible with latest Hub 4.28.0
In this case, via env var SE_OPTS, can you try to add config flag `--session-timeout 300` to see any help?

**Reply by devqaio** [reply]
@VietND96 - I am new to helm. Would you mind help me on how to set env vars through values.yaml. Not sure of it is already documented and I overlooked that.

Thank you

**Reply by VietND96** [reply]
It follows the structure of chromeNode

```yaml
crossBrowsers:
  chromeNode:
    - nameOverride: '{{ $.Release.Name }}-node-chrome-120'
      imageTag: '120.0'
      extraEnvironmentVariables:
        - name: SE_OPTS
          value: "--session-timeout 300"
      hpa:
        platformName: 'Linux'
        browserVersion: '120.0'
```
