### ISSUE TITLE
Docker grid console is not getting refreshed even when selenium-nodes are down in the worker nodes.

### ISSUE THREAD

**Issue by kumar1210** [SeleniumHQ/docker-selenium#1001]
## 🐛 Bug Report

We have created a docker grid using multiple machine connected through a swarm network. Now post starting the docker grid, we have scaled up the selenium browser in the grid. Swarm will distribute the no. of nodes in the network post checking all the basic checks.  Let's say we have machines called hub, worker1 and worker2 in the grid. Once the grid is up, go to grid/console and confirm the no. of nodes browser nodes up in the grid. Till here, it works fine. 
But let's say one of the worker node get some network connectivity issue or it might get restarted. However the worker node will get re-registered over the swarm network and we can confirm it by running command : "docker node ls"
But when we check the number of browsers up in the docker grid with command : "docker stack ps <stack-name>". it shows the selenium nodes which were running on the restarted worker are in the shutdown status. Is this an issue ?
Also, when we go to localhost:<port>/grid/console, we can see all the nodes are showing as up status, even the shutdown one's.

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):
1. Create a docker swarm network using 2-3 machine. Making one machine as hub and other machines as worker nodes.
2. To create swarm network : docker swarm init --advertise-addr=<ip-addr>
3. To join a machine into the above swarm network(run it in other machines) : docker swarm join --token SWMTKN-1-5bbh9ksinfmajdqnsuef7y5ypbwj5d9jazt47urenz3ksuw9lk-227dtheygwbxt8dau8 <master host ip address>:2377
4. You can check in the respective machine, whether it's connected to the swarm network or not by running : docker info.
Now, we have a cluster to deploy the selenium gird. 
5. Deploy a selenium grid with few number of browser instances ( have attached the yml file for same).
6. Once the grid is up, launch the url, localhost:4444/grid/console and can check all the browser nodes are up. 
7. Run command, docker node ls and confirm the cluster status of all machines.
8. Run command, docker stack ls <stack-name> to check the browser nodes status.
9. Restart one of the worker machine, do the stepts 7 and 8 again, we can see worker has re-joined the swarm network but the browser nodes are in shutdown status. 
10.  launch the url, localhost:4444/grid/console, however the restarted worker browser nodes are in shutdown status but grid/console still shows that all the nodes are up, which gives a wrong impression through the UI.

## Expected behavior

Whatever browser nodes which are not ready to accept the requests should be displayed differently. For e.g. when a browser node is already consumed we show it in grey color, similarly if a browser is shutdown, either it should not be displayed in console or any marker to notify the same.

## Test script reproducing this issue (when applicable)
No script needed, have provided the docker compose configuration below

## Environment

OS:  Linux

Docker-Selenium image version:  3, 3.141, 3.141.59-zinc etc

Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
]
Docker compose config : 

```
version: '3'
networks:
  private:
    driver: overlay
services:
  hub:
    image: selenium/hub:3.141.59-zinc
    ports:
      - "4444:4444"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    environment:
      - GRID_TIMEOUT=3600
      - GRID_MAX_SESSION=1
      - GRID_MAX_INSTANCES=1
      - GRID_CLEAN_UP_CYCLE=60000
      - GRID_UNREGISTER_IF_STILL_DOWN_AFTER=180000
    networks:
      - private
  firefox:
    image: selenium/node-firefox-debug:3.141.59-zinc
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_SESSION=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5555" /opt/bin/entry_point.sh'
    ports:
      - "5555:5555"
      - "5901-5940:5900"
    deploy:
      replicas: 20
    networks:
      - private
```
