### ISSUE TITLE
Docker grid console is not getting refreshed even when selenium-nodes are down in the worker nodes.

### ISSUE THREAD

**Issue by kumar1210** [SeleniumHQ/docker-selenium#1002]
🐛 Bug Report
Even the worker browser nodes are down, grid console shows those browsers as an active browser. 

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):

1.  Create a docker swarm network using 2-3 machine. Making one machine as hub and other machines as worker nodes.
2. To create swarm network : docker swarm init --advertise-addr=
3. To join a machine into the above swarm network(run it in other machines) : docker swarm join --token SWMTKN-1-5bbh9ksinfmajdqnsuef7y5ypbwj5d9jazt47urenz3ksuw9lk-227dtheygwbxt8dau8 :2377
4. You can check in the respective machine, whether it's connected to the swarm network or not by running : docker info.
   Now, we have a cluster to deploy the selenium gird.
5.   Deploy a selenium grid with few number of browser instances ( have attached the yml file for same).
6.    Once the grid is up, launch the url, localhost:4444/grid/console and can check all the browser nodes are up.
7.    Run command, docker node ls and confirm the cluster status of all machines.
8.    Run command, docker stack ls to check the browser nodes status.
 9.   Restart one of the worker machine, do the stepts 7 and 8 again, we can see worker has re-joined the swarm network but the browser nodes are in shutdown status.
 10.   launch the url, localhost:4444/grid/console, however the restarted worker browser nodes are in shutdown status but grid/console still shows that all the nodes are up, which gives a wrong impression through the UI.

## Expected behavior

Whatever browser nodes which are not ready to accept the requests should be displayed differently. For e.g. when a browser node is already consumed we show it in grey color, similarly if a browser is shutdown, either it should not be displayed in console or any marker to notify the same.

## Test script reproducing this issue (when applicable)

docker-sompose Script : 

```
version: '3'
networks:
  private:
    driver: overlay
services:
  hub:
    image: selenium/hub:3.141.59-zinc
    ports:
      - "4444:4444"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    environment:
      - GRID_TIMEOUT=3600
      - GRID_MAX_SESSION=1
      - GRID_MAX_INSTANCES=1
      - GRID_CLEAN_UP_CYCLE=60000
      - GRID_UNREGISTER_IF_STILL_DOWN_AFTER=180000
    networks:
      - private
  firefox:
    image: selenium/node-firefox-debug:3.141.59-zinc
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_SESSION=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5555" /opt/bin/entry_point.sh'
    ports:
      - "5555:5555"
      - "5901-5940:5900"
    deploy:
      replicas: 20
    networks:
      - private
```

## Environment

OS: Linux
Docker-Selenium image version:   3.141.59-zinc 
Docker version: 18.09.1-ol, build c3ab8a8
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
Have already provide above.
