### ISSUE TITLE
latest (3.141.59-zirconium) version of hub cannot reach the node

### ISSUE THREAD

**Issue by burtsevyg** [SeleniumHQ/docker-selenium#1015]
## 🐛 Bug Report

latest (3.141.59-zirconium) version of hub cannot reach the node.
3.141.59-yttrium version work perfect.

## To Reproduce
Run docker stack:
(see instructions on https://dockerswarm.rocks/traefik/)
```
<!--
Please be sure to include an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/
If you can't provide a link to the page, consider creating a reproducible page on https://jsfiddle.net/
-->

version: '3.7'

services:
  hub:
    image: selenium/hub:latest
    networks:
      - default
      - traefik-public
    deploy:
      labels:
        - traefik.frontend.rule=Host:selenium-${DOMAIN?Variable DOMAIN not set}
        - traefik.enable=true
        - traefik.port=4444
        - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https

  chrome:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - default
      - traefik-public
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
      mode: global
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

networks:
  traefik-public:
    external: true
```
## Expected behavior

There are no error in the logs

## Test script or set of commands reproducing this issue

Please, see reproduce section.

## Environment

OS:  docker 19.03.5
Browser:   latest (see docker-compose file)
Browser version:  latest (see docker-compose file)
Browser Driver version:  latest (see docker-compose file)
Language Bindings version:  latest (see docker-compose file)
Selenium Grid version (if applicable):  latest (see docker-compose file)

Log errors:
```
12:54:09.713 INFO [Hub.start] - Nodes should register to http://172.18.0.7:4444/grid/register/
12:54:09.713 INFO [Hub.start] - Clients should connect to http://172.18.0.7:4444/wd/hub
12:54:22.684 INFO [DefaultGridRegistry.add] - Registered a node http://47be09a43cfa:5555
12:54:33.010 INFO [DefaultRemoteProxy.onEvent] - Marking the node http://47be09a43cfa:5555 as down: cannot reach the node for 2 tries
12:55:33.036 INFO [DefaultRemoteProxy.onEvent] - Unregistering the node http://47be09a43cfa:5555 because it's been down for 60027 milliseconds
12:55:33.037 WARN [DefaultGridRegistry.removeIfPresent] - Cleaning up stale test sessions on the unregistered node http://47be09a43cfa:5555
```
