### ISSUE TITLE
Random crashes with "connection refused" running selenium/standalone-chrome-debug

### ISSUE THREAD

**Issue by alb-i986** [SeleniumHQ/docker-selenium#1032]
## 🐛 Bug Report

Hi,

I'm getting random crashes running selenium/standalone-chrome-debug.

This is my docker-compose file:

```
version: '3'

services:

  selenium-chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444" # selenium grid hub
      - "5900:5900" # vnc server (password: secret)
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - VNC_NO_PASSWORD=1

```

This is the output with the error I'm getting:

```
selenium-chrome_1  | 08:38:07.476 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session d7c6155bf7e38ff56e1fe2fe1feebc12 (org.openqa.selenium.chrome.ChromeDriverService)
selenium-chrome_1  | [1587026290.447][SEVERE]: Timed out receiving message from renderer: 0.100
selenium-chrome_1  | [1587026290.550][SEVERE]: Timed out receiving message from renderer: 0.100
selenium-chrome_1  | [1587026290.653][SEVERE]: Timed out receiving message from renderer: 0.100
selenium-chrome_1  | [1587026290.761][SEVERE]: Timed out receiving message from renderer: 0.100
selenium-chrome_1  | [1587026290.865][SEVERE]: Timed out receiving message from renderer: 0.100
selenium-chrome_1  | [1587026290.970][SEVERE]: Timed out receiving message from renderer: 0.100
selenium-chrome_1  | [1587026291.073][SEVERE]: Timed out receiving message from renderer: 0.100
selenium-chrome_1  | [1587026291.182][SEVERE]: Timed out receiving message from renderer: 0.100
selenium-chrome_1  | [1587026291.286][SEVERE]: Timed out receiving message from renderer: 0.100
selenium-chrome_1  | [1587026291.795][SEVERE]: Timed out receiving message from renderer: 0.100
selenium-chrome_1  | [1587026292.265][SEVERE]: Timed out receiving message from renderer: 0.100
Unexpected API error for skywalkerstabilitycert_selenium-chrome_1 (HTTP code 500)
Response body:
dial unix /Users/alb/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: connection refused
```

The image is up-to-date:
```
$ docker pull selenium/standalone-chrome-debug
Using default tag: latest
latest: Pulling from selenium/standalone-chrome-debug
Digest: sha256:c393783a689d050adab2509bccdac65abb159ebaab994563277fba9669158c7e
Status: Image is up to date for selenium/standalone-chrome-debug:latest
```

## To Reproduce

With the following docker-compose file:

```
version: '3'

services:

  selenium-chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - VNC_NO_PASSWORD=1

```

Run `docker-compose up selenium-chrome`.

Then I launch my tests from Intellij IDEA, with Cucumber JUnit, **in debug mode**, and I step through the code. Sometimes I may also leave the execution paused for quite a long time, actually, because I'm using your Chrome for _developing_ tests, and I need to find a good locator, you know.
So could that be the thing? That is, that these containers are not designed to sustain a long execution?
But actually it only crashes sometimes. Other times the session naturally times out, with no crashes whatsoever.

## Test script reproducing this issue (when applicable)

N/A, as this issue occurs randomly.

## Environment

OS: OSX 10.10.5

Docker-Selenium image version: latest
image id: ab22600a9c2b

Docker Version 17.06.2-ce-mac27 (19124)
Channel: stable
428bd6ceae

docker-compose version 1.14.0, build c7bdf9e
