### ISSUE TITLE
W3C: false, not working with selenium hub (works with standalone)

### ISSUE THREAD

**Issue by jagarzone6** [SeleniumHQ/docker-selenium#1034]
## 🐛 Bug Report

Error in tests running in docker selenium/hub with selenium/node-chrome, all tests using 
`driver.actions()` or 
`driver
    .manage()
    .window()
    .setSize()` 
fail with errors:
`UnknownCommandError: unknown command: Cannot call non W3C standard command while in W3C mode` and
`unknown command: unknown command: session/90d9a40cf2534e448ae6a2ad5f38c1bf/window/size`

After I switch to selenium/standalone-chrome same tests passes.

## To Reproduce
1. Capabilities:
Set chrome option W3C: false
2. script, any tests using
`driver.actions()` or 
`driver
    .manage()
    .window()
    .setSize()` 

Steps to reproduce the behavior (including the command to start the containers):
docker-compose file:

```
version: '3.4'
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
```

## Expected behavior
Tests should pass and execute successfully all non w3c actions  

## Test script reproducing this issue (when applicable)
`driver.actions()` or 
`driver
    .manage()
    .window()
    .setSize()` 

## Environment

OS:  
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"

Docker-Selenium image version: 
selenium/node-chrome             latest              c3454acccbb6        8 days ago          908MB
selenium/hub                     latest              fc6accc9b9e2        8 days ago          263MB

Docker version: 
Docker version 19.03.8, build afacb8b7f0

Docker-Compose version (if applicable):
docker-compose version 1.24.1, build 4667896b

Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
docker-compose up -d
