### ISSUE TITLE
Cannot reach the node

### ISSUE THREAD

**Issue by moreiraj2** [SeleniumHQ/docker-selenium#1042]
## 💬 Question

Can someone help me with selenium-hub running in docker? 

docker-compose.yml
````
version: '3'

services:
  selenium-hub:
    image: selenium/hub:3.2.0
    container_name: selenium-hub
    privileged: true
    ports:
      - "4444:4444"
    environment:
      - GRID_DEBUG=true
````

I have access to grid console using browser http://localhost:4444/grid/console

<img width="678" alt="Screenshot 2020-05-13 at 11 17 55" src="https://user-images.githubusercontent.com/62352215/81800997-a42fdb00-950b-11ea-826c-22dd74e15c15.png">

But when I try to register a node with appium get this error message:

````[debug] [Appium] Appium successfully registered with the grid on http://127.0.0.1:4444[debug] [Appium] Grid registration error: Cannot find proxy with ID =http://0.0.0.0:4723 in the registry.````

And the logs on selenium-docker:

```
selenium-hub    | WARN [DefaultGridRegistry.removeIfPresent] - Cleaning up stale test sessions on the unregistered node http://0.0.0.0:4723
selenium-hub    | WARN [BaseRemoteProxy.<init>] - Max instance not specified. Using default = 1 instance
selenium-hub    | INFO [DefaultGridRegistry.add] - Registered a node http://0.0.0.0:4723
selenium-hub    | INFO [DefaultRemoteProxy.onEvent] - Marking the node http://0.0.0.0:4723 as down: cannot reach the node for 2 tries
```
