### ISSUE TITLE
Support for Firefox ESR in custom build process

### ISSUE THREAD

**Issue by other019** [SeleniumHQ/docker-selenium#1050]
## 🐛 Bug Report
As I wanted to build the NodeFirefox image with version esr-latest it appears to be impossible, because there is no special rule for downloading. That rule is needed just like for nightly-latest. It cannot be downloaded from CDN.

Download button leads to https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=linux64&lang=en-US. If you try to go with CDN you can receive this readme https://download-installer.cdn.mozilla.net/pub/firefox/releases/latest-esr/README.txt.

## To Reproduce

```bash
make generate_all
BUILD_ARGS="--build-arg FIREFOX_VERSION=esr-latest" make firefox firefox_debug    
[...]
ttps://download-installer.cdn.mozilla.net/pub/firefox/releases/esr-latest/linux-x86_64/en-US/firefox-esr-latest.tar.bz2:
2020-05-27 15:10:46 ERROR 404: Not Found.
```

## Expected behavior
It is expected to receive docker image containing firefox68.8.0esr.

## Test script reproducing this issue (when applicable)
```bash
git clone https://github.com/SeleniumHQ/docker-selenium.git
cd docker-selenium
make generate_all
BUILD_ARGS="--build-arg FIREFOX_VERSION=latest-esr" make firefox firefox_debug    
```
minimal compose for testing
```yaml
version: "3.3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200525
    container_name: selenium-hub
    ports:
      - "4444:4444"
  firefox:
    image: selenium/node-firefox-debug:3.141.59-20200525
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
```
## Environment

OS: Arch Linux
Docker-Selenium image version: custom builded 
Docker version: Docker version 19.03.8-ce, build afacb8b7f0

## Proposed solution
https://github.com/SeleniumHQ/docker-selenium/pull/1049
