### ISSUE TITLE
armhf docker image of Selenium

### ISSUE THREAD

**Issue by vipulgupta2048** [SeleniumHQ/docker-selenium#1076]
## 🚀 Feature Proposal
I am trying to run Selenium on RPi3 in a docker container and all the docker images that are available are of x86 architecture type. Henceforth I am willing to build a fully-featured arm7hf image for Selenium to be able to run on modern ARM devices (with some help from your side) if you feel this is viable enough. 

## Motivation
ARM is a fast-approaching architecture that is becoming better day by day with recent advancements. Selenium especially being quite popular with folks working in web automation and testing, if the framework can run on modern high-performance boards like RaspberryPi's then it would be extremely helpful to the community in general. 

`Superior web automation now becomes portable with ARM-based devices` sounds like a great pitch. 

## Example

Build a fully-featured dockerfile for selenium that is compatible with ARM to build a docker image, we can either modify present components (recommended) or build a new one. Folks, wanting to run on Selenium on ARM devices, can easily pull the image and start working on it. 

Ubuntu Bionic 18.04 has multi-arch support for armhf so we are sorted there for the base image.  
Google-Chrome is not available on ARM, so we can use Chromium. 
And, Chromium-Chromedriver as an alternative for chromedriver. That's the two major things that gets changed.

Let me know what you think folks! Happy to help to build this if it sounds viable enough.

**Comment by diemol** [comment]
@vipulgupta2048 
Yeah, I guess over time there will be more interest in these images, but not having Chrome or ChromeDriver is less than ideal. 
Additionally, I guess we need to compile the Selenium Server jar for ARM?

**Comment by vipulgupta2048** [comment]
Thanks for replying @diemol 
Can you explain why Chromium and Chromium-Chromedriver won't fit together and would be less than ideal for running Selenium? I understand everything is configured with taking Chrome and Chromedriver as a base but isn't there any way to run the alternatives. 

Yes, Selenium server needs to be recompiled for ARM since it contains some non-JVM code. Otherwise, it might have just worked. How do you think I should go about this?

**Comment by diemol** [comment]
Well, people want to test on the same browser customers use. We know that Chromium is the base for Chrome, but in reality, people want to test with Chrome. 

About Selenium jar, we need to figure out how to do it in a simple way. For now, the focus is Selenium 4 and after that is released, we can check this again. In general, this does not look as a simple thing to achieve.

**Comment by vipulgupta2048** [comment]
@diemol Agreed to that, more users use Chrome so makes sense to take that. With your response, I thought Chromium wouldn't work at all even with a little tinkering.

About Selenium jar, at first, it seemed quite straightforward as we can just run the same Bazel build over on the ARM container. But, since Bazel is not available on ARM as a package, please do let me know if there is a way about how I can go building the package. Anything would help at this point. Thanks!

**Comment by diemol** [comment]
@vipulgupta2048 yeah, right now we are still working towards a beta in Selenium 4, so no priority for this right now. I will comment back later.

**Comment by vipulgupta2048** [comment]
Thanks @diemol appreciate it!
Happy to help, I have laid some groundwork for the same when i tried porting myself. Let me know I can share it over here when the time comes :+1:

**Comment by henningn** [comment]
Since apple silicon is released, this issue might be relevant for more users.

Currently selenium/standalone-chrome failed in my setup with "driver.version: unknown".
The selenium/standalone-firefox still works. I've build standaloneFirefox for arm64, which was pretty straightforward and give a decent preformance boost.

(Tested with DockerPreview7.)

**Comment by jmichaelward** [comment]
+1 for relevancy. Just tried to run our tests this morning on Apple M1, and the same errors reported 6 days ago are there. I'll give standalone-firefox a look in the meantime.

**Comment by thomasphilibert** [comment]
> Since apple silicon is released, this issue might be relevant for more users.
> 
> Currently selenium/standalone-chrome failed in my setup with "driver.version: unknown".
> The selenium/standalone-firefox still works. I've build standaloneFirefox for arm64, which was pretty straightforward and give a decent preformance boost.
> 
> (Tested with DockerPreview7.)

Hello @henningn, 
Can you explain to me how you did it? I get the same result between Chrome and Firefox on an Apple M1.

Best,
Thomas

**Comment by henningn** [comment]
@thomasphilibert,
I can use selenium/standalone-firefox:4.0.0-beta-1-prerelease-20201208 out of the box. It is slow but it works.

To build an arm image you have to ake some changes to the "Base"-Dockerfile and "NodeFirefox"-Dockerfile. (see https://github.com/henningn/docker-selenium-arm64/commit/c0f0f6440d735c7ef12b6f2c43e05e30a550fa42)

I've pushed the image to docker hub, where the amd64 version is the official one and the arm64 version is the self build version. You can find it here: https://hub.docker.com/repository/docker/henningn/selenium-standalone-firefox

**Comment by DmitrySkripkin** [comment]
I tried @henningn solutions with firefox, it didn't help. Then I tried to recreate Base and Hub images with arm64 ubuntu, same results.
From my perspective the problem is in Base and Hub images. When I run Hub on Linux amd64 machine i can browse to `localhost:4444` and see Selenium page, but it doesn't work on arm machine (ports are exposed but response is empty).

BTW, no problems with running selenium with Chrome natively without Docker. I think we can manage it to run as expected in a container.


EDIT:
I was able to run Hub successfully. Now I can open `localhost:4444` page. I have no idea why it didn't work previously. Now I think I can try to run firefox image.

**Comment by sj26** [comment]
Does armhf run on arm64? (I'm guessing the reverse doesn't work, armv9 > armv7.)

I have multi-arch linux amd64/arm64 images for all the Selenium parts as well as Chromium and Firefox which work great on Docker for Mac on an M1 as linux/arm64, and on AWS Graviton2 instances as the same, and still work on linux/amd64 platform as well:

https://github.com/sj26/docker-selenium

They're currently pushed to Docker Hub here:

https://hub.docker.com/u/seleniarm

The main blocker seems to be getting good upstream browser binaries. The best I could find was Debian who build Chromium and Firefox across many platforms.

**Comment by jamesmortensen** [comment]
@sj26 How did it go compiling the selenium docker images for the ARM architecture?  I tried to pull from seleniarm but it seems the images are not published on Docker, unless I'm just missing something.

```
version: "3"
services:
  chrome0:
    image: seleniarm/node-chromium:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - seleniarm-hub
    environment:
      - SE_EVENT_BUS_HOST=seleniarm-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  chrome1:
    image: seleniarm/node-chromium:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - seleniarm-hub
    environment:
      - SE_EVENT_BUS_HOST=seleniarm-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6901:5900"

  chrome2:
    image: seleniarm/node-chromium:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - seleniarm-hub
    environment:
      - SE_EVENT_BUS_HOST=seleniarm-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6902:5900"

  seleniarm-hub:
    image: seleniarm/hub
    container_name: seleniarm-hub:4.0.0-beta-1-20210215

    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

I tried running a hub from here but it said:

```
$ docker-compose -f docker-compose-hub-arm64.yml up -d
Pulling seleniarm-hub (seleniarm/hub:)...
ERROR: manifest for seleniarm/hub:latest not found: manifest unknown: manifest unknown
```

What am I missing?  Thanks.

**Comment by sj26** [comment]
I think I didn't publish a `latest` tag for `seleniarm/hub` sorry! Only `4.0.0-beta-1-20210215`. I think the scripts still push 3.x series as `latest`.

https://hub.docker.com/r/seleniarm/hub/tags

**Comment by jamesmortensen** [comment]
@sj26 Thank you!  Glad to be able to run my Docker Selenium Hub again!  Here is my updated docker-compose:

```
version: "3"
services:
  chrome0:
    image: seleniarm/node-chromium:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - seleniarm-hub
    environment:
      - SE_EVENT_BUS_HOST=seleniarm-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  chrome1:
    image: seleniarm/node-chromium:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - seleniarm-hub
    environment:
      - SE_EVENT_BUS_HOST=seleniarm-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6901:5900"

  chrome2:
    image: seleniarm/node-chromium:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - seleniarm-hub
    environment:
      - SE_EVENT_BUS_HOST=seleniarm-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6902:5900"

  seleniarm-hub:
    image: seleniarm/hub:4.0.0-beta-1-20210215
    container_name: seleniarm-hub-4.0.0-beta-1-20210215

    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

**Comment by zeevo** [comment]
+1 for these images. It would be nice to run a selenium server on Raspberry Pi 4 using Docker.

**Comment by idontusenumbers** [comment]
> I have multi-arch linux amd64/arm64 images for all the Selenium parts as well as Chromium and Firefox which work great on Docker for Mac on an M1 as linux/arm64, and on AWS Graviton2 instances as the same, and still work on linux/amd64 platform as well:

This has been working well for me, thanks!

Any chance of an updated build? I'd be curious about the new noVnc server that seems to have been merged since the latest build.

**Comment by sanemat** [comment]
any updates?

**Comment by klimsava** [comment]
@sj26 Hi! How to visually check the browser activity?

**Comment by sj26** [comment]
For my fork, I don't have the time to rebase it against upstream sorry so updates will be sporadic. I'd love to see upstream support for ARM.

**Comment by diemol** [comment]
We'd love to see contributions in this aspect as well, we do not have machines to test this and we have little time to research on this. However, seems @sj26 has had the time to get this ahead. We are happy to discuss how we can get this done. Looking forward to your contributions!

**Comment by soulgalore** [comment]
I've been looking to do the same for sitespeed.io so I can help out here or test. There are some problems though: 
* @diemol what's Seleniums requirements for browser versions? I always try to run my test with the latest stable versions for Chrome/Firefox but getting those for ARM (and corresponding drivers) is a pain (at least at the moment)
* Has anyone found a way to use different docker files per platform/arch? That way you don't have to have big if/else depending on the platform. I haven't been able to find a way with docker buildx but maybe someone else has?

**Comment by stickperson** [comment]
> Has anyone found a way to use different docker files per platform/arch? That way you don't have to have big if/else depending on the platform. I haven't been able to find a way with docker buildx but maybe someone else has?

@soulgalore how about just specifying the Dockerfile with `-f`?

**Comment by diemol** [comment]
>@diemol what's Seleniums requirements for browser versions? I always try to run my test with the latest stable versions for Chrome/Firefox but getting those for ARM (and corresponding drivers) is a pain (at least at the moment)

Ideally we only want to support the latest stable versions, and I believe that is the main problem with this, getting the binaries for browsers and browser drivers is not straight forward.

**Comment by jamesmortensen** [comment]
Is it possible to just ease into the ARM64 waters slowly by at least supporting Debian ARM64 and Chromium, such as seleniarm/standalone-chromium only?  The Chromium ARM64 binary on Debian 10 seems pretty stable.  I haven't tried other browsers, but being able to run tests in a Chromium browser in containers on the Mac M1 is better than not being able to run any tests at all.  I've been using @sj26 solution for some time now and it's allowed me to continue to be productive while on the Mac M1...

I also noticed that TravisCI appears to support running tests on the ARM64 architecture, which means you should be able to run these through automated tests before publishing them, even if you don't have a physical ARM machine.  https://docs.travis-ci.com/user/multi-cpu-architectures/

**Comment by soulgalore** [comment]
> @soulgalore how about just specifying the Dockerfile with -f?

yes building containers from different Docker files and give them different tags works fine with `-f` but if you want the them to have the same name and same tag but built for different architecture I haven't find a way to do that. For example building with `docker buildx` for one platform at a time and then pushing them, the Docker hub only contains the latest pushed container/platform, not for all platforms. Or at least when I did a quick try.

**Comment by jamesmortensen** [comment]
I apologize for assuming this is easier than it sounds.  As with many of these things, once you dig in, you realize it's not so straightforward.  

I created a fork to update Selenium/Standalone-Chrome to use 4.0.0-rc-2-prerelease (or off the latest trunk at the time of this writing)

https://github.com/seleniarm/docker-selenium

You can build the images yourself with the `sh build.sh` command and then use the noVNC client in your browser.  I haven't had time to look at Firefox or the Selenium Grid yet, but others are welcome to give it a try.

**Comment by jamesmortensen** [comment]
I pushed some of the ARM64 Docker Selenium images to Docker Hub.  They can be found here:  https://hub.docker.com/u/seleniarm.

**Comment by DmitriyYukhanov** [comment]
Thank you @jamesmortensen !

**Edited:**
For those who would like to build non-64 bit arm images: I was able to build armhf images out from the @jamesmortensen [repo](https://github.com/seleniarm/docker-selenium) right on the rPi 4.
Changes required to make it happen:
- replace arm64 with arm/v7 at the `build.sh`
- replace arm64 with armhf at the `Base/Dockerfile`

Keeping all this local as I'm not experienced with docker publishing enough.

**Comment by jmriego** [comment]
thanks a lot @DmitriyYukhanov ! for some reason I was not able to get it to work replacing arm64 with arm/v7 and had to replace it with armhf.

So just replace `arm64` with `armhf` in both `build.sh` and `Base/Dockerfile` from that repo. I didn't get Firefox working but Chrome does so I can manage with that for the moment

**Comment by viktorianer** [comment]
After great work from @jamesmortensen, we have an image for `arm` based arch.
I would be nice to merge it in this repo. If I knew how to help, I would do it myself. I've [already created a ticket](https://github.com/seleniarm/docker-selenium/issues/2). 

I think @jamesmortensen or @sj26 can help much more than me. :)

**Comment by jamesmortensen** [comment]
Seleniarm container images are built with a lot of unknowns that make merging them upstream a risky endeavor.  Here are the challenges that need to be overcome:

- There are no Google Chrome binaries, only Chromium, for ARM64, and the Selenium maintainers prefer to support the browsers used most by users, which is Google Chrome. 
- The ARM64 binary for Chromium on Debian is 3 major versions behind the latest Chromium on the x86_64 platform, and Debian is the only distro where we can find a matching ARM64 Chromedriver binary.
- Firefox on ARM64 is also a few versions behind the x86_64 build.  
- There are no ARM64 binaries for geckodriver available on Mozilla's site or in any Linux distro packages.  I have to build it manually in an intermediate ARM64 container and then copy it into the node-firefox container image during the build process.  Currently, it cannot be automated like it can for the upstream images due to problems attempting to run `cargo build` in a shell script.
- There are no ARM64 binaries for Microsoft Edge or Opera, at least not to my knowledge, and if there were, we would need corresponding WebDrivers for them as well.
- The other images in the seleniarm repo have not been built and tested, such as the distributor, standalone-docker, etc.  
- Coming back to testing, to the best of my knowledge, we don't have any automated tests for the seleniarm images.

I am not sure what the update process is for browser binaries and WebDrivers on Debian/Ubuntu ARM64.  It doesn't seem like those communities are able to keep the binaries up to date.  At this time, it seems best to maintain the seleniarm fork until things stabilize, as most people working on Intel based systems will probably be better served by the images which are in the upstream repo.

I consider seleniarm to be helpful for those of us on ARM64 machines, but they should also be considered very alpha at this time.  If you're able to run the Intel images, I highly recommend running them instead.  Hope this helps!

**Comment by zwbetz-gh** [comment]
@sj26 / @jamesmortensen - just want to say **thank you** 💯. 

I burned most of today debugging these error messages, only to find this wonderful thread. 

I now have to maintain 2 docker compose files, an arm64 for myself, and a regular amd64 for the rest of the team. Which I'll happily do in exchange for a working setup 🙂 

```
docker-compose.e2e.arm64.yml
docker-compose.e2e.yml
```

---

**Edit:** I recently learned about the concept of "override" in docker compose. So, now I can override just the `image` value. See snippets below:

File `docker-compose.e2e.yml`:

```yml
version: '3.4'
services:

  e2e:
    depends_on:
      - hub
      - chrome
    build:
      context: ./e2e
      dockerfile: ./Dockerfile
    volumes:
      - ./e2e/tests_output:/app/tests_output
    env_file:
      - .env
    command: ./run.sh

  hub:
    image: selenium/hub:4.1.1-20211217
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    env_file:
      - .env
    environment:
      - GRID_DEBUG=true

  chrome:
    depends_on:
      - hub
    image: selenium/node-chrome:4.1.1-20211217
    shm_size: 2gb
    env_file:
      - .env
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - START_XVFB=false
      - GRID_DEBUG=true
```

File `docker-compose.e2e.arm64.yml`:

```yml
version: '3.4'
services:

  hub:
    image: seleniarm/hub:4.0.0-20211213

  chrome:
    image: seleniarm/node-chromium:4.0.0-20211213
```

Run it with:

```sh
docker compose \
-f docker-compose.yml \
-f docker-compose.e2e.yml \
-f docker-compose.e2e.arm64.yml \
build hub chrome e2e

docker compose \
-f docker-compose.yml \
-f docker-compose.e2e.yml \
-f docker-compose.e2e.arm64.yml \
up -d hub chrome

docker compose \
-f docker-compose.yml \
-f docker-compose.e2e.yml \
-f docker-compose.e2e.arm64.yml \
run --rm e2e
```
