### ISSUE TITLE
Chrome fails to start when running on the same network with appium

### ISSUE THREAD

**Issue by itaishalom** [SeleniumHQ/docker-selenium#1077]
## 🐛 Bug Report

Hi all. I'm trying to run a docker compose file but the chrome got stuck in a loop:
```
selenium-hub             | 14:34:47.711 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
chrome_1                 | 2020-07-06 14:34:47,745 INFO spawned: 'xvfb' with pid 9469
chrome_1                 | 2020-07-06 14:34:47,746 INFO spawned: 'fluxbox' with pid 9470
chrome_1                 | 2020-07-06 14:34:47,747 INFO spawned: 'vnc' with pid 9471
chrome_1                 | 2020-07-06 14:34:47,748 INFO spawned: 'selenium-node' with pid 9472
chrome_1                 | 2020-07-06 14:34:47,755 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1                 | 2020-07-06 14:34:47,755 INFO success: fluxbox entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1                 | 2020-07-06 14:34:47,755 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1                 | 2020-07-06 14:34:47,755 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1                 | 2020-07-06 14:34:47,755 INFO exited: xvfb (exit status 1; not expected)
selenium-hub             | 14:34:47.787 INFO [GridLauncherV3.lambda$buildLaunchers$5] - Launching Selenium Grid hub on port 4444
chrome_1                 | 2020-07-06 14:34:47,803 INFO exited: fluxbox (exit status 1; not expected)
chrome_1                 | Connecting to the Hub using the host localhost and port 4444
chrome_1                 | 2020-07-06 14:34:48,126 INFO spawned: 'fluxbox' with pid 9504
chrome_1                 | 2020-07-06 14:34:48,135 INFO success: fluxbox entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1                 | 2020-07-06 14:34:48,136 INFO exited: fluxbox (exit status 1; not expected)
```

The interesting thing is that If I put the appium on a different network (not the localhost) it's working fine.
But for my purpose, I'm must have them all on the same localhost.

## To Reproduce
This is the docker compose file i'm trying to run:
```
version: '3.4'
services: 
  
  selenium_hub:
    image: selenium/hub:3.141.59-20200525
    container_name: selenium-hub
    privileged: true
    ports:
      - '4444:4444'
    network_mode: host 
    pid: "host"

  chrome:
    image: selenium/node-chrome-debug:3.141.59-20200525
    network_mode: host 
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    depends_on:
      - selenium_hub
    environment:
      - START_XVFB=true
      - HUB_HOST=localhost
      - HUB_PORT=4444
    pid: "host"
    

  # Appium Docker Android  
  appium_android_device:
    image: appium/appium
    depends_on:
      - chrome
    privileged: true
    pid: "host"
    network_mode: host 
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
    environment:
      - HUB_PORT=4444
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=localhost
      - BROWSER_NAME=chrome
```

## Expected behavior

Be able to connect to the chrome node using vnc at 127.0.0.1:5900
but it's impossible.

## Environment
The host machine is Ubuntu 18.04
check the docker compose file

**Comment by diemol** [comment]
@itaishalom what OS are you using on the host machine?
Does `appium/appium` also have VNC?

**Comment by itaishalom** [comment]
The host machine runs Ubuntu.
I don't think that the appium container runs vnc as it's not specified:
https://hub.docker.com/r/appium/appium

Anyway, the interesting thing is that with the following docker compose, the issue with that fluxbox does not occur

```
version: '3.4'
services: 
  
  selenium_hub:
    image: selenium/hub:3.141.59-20200525
    container_name: selenium-hub
    privileged: true
    ports:
      - '4444:4444'
    network_mode: host 
    pid: "host"

  chrome:
    image: selenium/node-chrome-debug:3.141.59-20200525
    network_mode: host 
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    depends_on:
      - selenium_hub
    environment:
      - START_XVFB=true
      - HUB_HOST=localhost
      - HUB_PORT=4444
    pid: "host"
    

  # Appium Docker Android  
  appium_android_device:
    image: appium/appium
    depends_on:
      - chrome
    privileged: true
    pid: "host"
    networks:		 #different network
		- default
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
    environment:
      - HUB_PORT=4444
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=192.168.10.2  #host ip's
      - BROWSER_NAME=chrome
```
