### ISSUE TITLE
Encrypt full Slack key on TravisCI

### ISSUE THREAD

**Issue by edumco** [SeleniumHQ/docker-selenium#1085]
## 🚀 Feature Proposal

Add full encryption on the Slack key that is used on `travis.yml`.

## Motivation

The exposure of non-encrypted keys on CI files is an anti-pattern and always should be avoided.

### Requirements:

- Ruby

- Travis CLI <https://rubygems.org/gems/travis>

### Steps

- Install Ruby <>

- Install Travis CLI 

```ruby
gem install travis
```

- On the project folder execute:

```bash
travis encrypt "<account>:<token>#channel" --add notifications.slack.rooms
```

### Expected result

The slack notifications section will look like this:

```yml
notifications:
  slack:
    rooms:
      - secure: "sdfusdhfsdofguhdfgubdsifgudfbgs3453durghssecurestringidsuag34522irueg="
```

## References

1. Configuring Slack notifications: <<https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications>>

2. Encryption keys <<https://docs.travis-ci.com/user/encryption-keys/>>

3. How to Install Ruby on Ubuntu 18.04 <<https://linuxize.com/post/how-to-install-ruby-on-ubuntu-18-04/>>
