### ISSUE TITLE
File upload fails on version 4.0.0-alpha-6-20200721 (Chrome & FireFox)

### ISSUE THREAD

**Issue by Valentyna** [SeleniumHQ/docker-selenium#1094]
## 🐛 Bug Report

`attach_file('file', '/path/to/file.txt', visible: false)`

On Chrome it fails with 
`Selenium < 3.14 with remote **Chrome doesn't support multiple file upload** (ArgumentError)`

On FireFox it fails with
```
Selenium::WebDriver::Error::InvalidArgumentError: **File not found:** /opt/project/end-to-end-test/data/downloads/firefox/backup-appliance-SMCVE-KVM-c1d1b28d-2147-4f4b-a5b4-3ee83c7a1107.20200803.1656.tgz
from WebDriverError@chrome://marionette/content/error.js:175:5
```

I verified that file is present and tested with non-existing file - in that case I'd see Capybara::FileNotFound: cannot attach file

docker-compose.yml

```
version: "3.4"
services:
  selenium-hub:
    image: docker.artifactory1.lancope.ciscolabs.com/selenium/hub:4.0.0-alpha-6-20200721
    container_name: selenium-hub
    ports:
      - '4444:4444'

  chrome:
    image: docker.artifactory1.lancope.ciscolabs.com/selenium/node-chrome:4.0.0-alpha-6-20200721
    volumes:
      - /dev/shm:/dev/shm
      - ./end-to-end-test/data/downloads:/home/seluser/Downloads
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  firefox:
    image: docker.artifactory1.lancope.ciscolabs.com/selenium/node-firefox:4.0.0-alpha-6-20200721
    volumes:
      - /dev/shm:/dev/shm
      - ./end-to-end-test/data/downloads:/home/seluser/Downloads/
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  x-end-to-end-test: &end-to-end-test
    build: end-to-end-test
    entrypoint: '/opt/project/end-to-end-test/bin/start.sh'
    volumes:
      - .:/opt/project/
      - /var/run/docker.sock:/var/run/docker.sock

  chrome-test:
    <<: *end-to-end-test
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - BROWSER=chrome
    depends_on:
      - chrome

  firefox-test:
    <<: *end-to-end-test
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - BROWSER=firefox
      - COMPOSE_PROJECT_NAME
    depends_on:
      - firefox
```

Browser registers in env.rb
```
case ENV['BROWSER']
when 'firefox'
  caps = Selenium::WebDriver::Remote::Capabilities.firefox(acceptInsecureCerts: true)
  opts = Selenium::WebDriver::Firefox::Options.new(prefs: { 'browser.download.dir' => "/home/seluser/Downloads/#{ENV['BROWSER']}",
                                                            'browser.download.folderList' => 2,
                                                            'browser.helperApps.neverAsk.saveToDisk' =>
                                                                'application/octet-stream' })
  Capybara.register_driver :selenium do |app|
    Capybara::Selenium::Driver.new(app,
                                   browser: :chrome,
                                   url: "http://#{ENV['HUB_HOST']}:#{ENV['HUB_PORT']}/wd/hub",
                                   desired_capabilities: caps,
                                   options: opts)
  end
when 'chrome'
chrome_args = %w[--ignore-certificate-errors --window-size=1360,998] # --user-data-dir=/tmp (for chrome_debug.log)
  opts = Selenium::WebDriver::Chrome::Options.new(args: chrome_args, prefs:
        { 'download.default_directory' => "/home/seluser/Downloads/#{ENV['BROWSER']}" })
    Capybara.register_driver :selenium_chrome do |app|
      Capybara::Selenium::Driver.new(app,
                                     browser: :chrome,
                                     url: "http://#{ENV['HUB_HOST']}:#{ENV['HUB_PORT']}/wd/hub",
                                     options: opts)
  end
end
```

## To Reproduce

Have a test like:

> system('touch file.txt')
> driver.navigate.to('https://formswift.com/sem/convert-pdf-to-word')
> attach_file('file', 'file.txt')

Run test with either of

> docker-compose run chrome-test
> docker-compose run firefox-test

## Expected behavior

File should be attached/uploaded

**Comment by diemol** [comment]
@Valentyna could I please have a complete script to reproduce the issue? I don't have a site to do multiple uploads and I would need to build everything from scratch.

**Comment by diemol** [comment]
Closing as we did not get more information

**Comment by Valentyna** [comment]
Hi, sorry for late response
I actually don't have the code that I can share - we're testing website which is not accessible anywhere except lab

It still fails on 4.0.0-beta-4-20210608
This time I'm using standalone image.

I believe something like this would work (I haven't tested it though):

test.rb
```
require 'capybara'
require 'capybara/dsl'
require 'selenium-webdriver'

caps = Selenium::WebDriver::Remote::Capabilities.firefox(acceptInsecureCerts: true,
                                                           'moz:firefoxOptions' => {
                                                             prefs: { 'browser.helperApps.neverAsk.saveToDisk' =>
                                                                          'application/octet-stream',
                                                                      'browser.download.folderList' => 2,
                                                                      'browser.download.dir' => "/home/seluser/Downloads/firefox" }
Capybara.register_driver :selenium do |app|
    Capybara::Selenium::Driver.new(app,
                                   browser: :firefox,
                                   url: "http://firefox:4444/wd/hub",
                                   capabilities: caps,
                                   options: opts)
  end
Capybara.current_driver = :selenium
Capybara.default_driver = :selenium
Capybara.visit('https://www.persofoto.com/upload/passport-photo')

attach_file('file', <path_to_some_photo>, visible: false)
```

and docker-compose.yml:
```
  firefox:
    container_name: firefox
    image: selenium/standalone-firefox:4.0.0-beta-4-20210608
    volumes:
      - /dev/shm:/dev/shm
      - ./end-to-end-test/data/downloads:/home/seluser/Downloads/
    ports:
      - "4445:4444"
      - "7902:7900" #this is to observe in noVNC
  test:
    image: ruby
    entrypoint: ["ruby", "gem install capybara", "gem install selenium-webdriver", "/opt/project/test.rb"]
    volumes:
      - .:/opt/project/
      - /var/run/docker.sock:/var/run/docker.sock 
```
