### ISSUE TITLE
how to run in none headless mode?

### ISSUE THREAD

**Issue by Doaa-Ismael** [SeleniumHQ/docker-selenium#1099]
I want to run codeception tests on chrome browser using docker but browser is not opening at all .. it always run in headless mode. so how to run in non-headless ?

this is my deocker-compose.yml 
```
version: '3'

services:
  codecept:
    image: codeception/codeception
    depends_on:
      - chrome
    volumes:
      - .:/project
    networks:
      main:

  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
      - 5900
    container_name: chrome
    privileged: true
    networks:
      main:

networks:
  main:
```

and here is acceptance.suite.yml

```
actor: AcceptanceTester
modules:
    enabled:
        - Asserts:
        - WebDriver:
            url: https://google.com
            host: 'chrome'
            browser: 'chrome'
            debug: true
            window_size: 820x1000

        - \Helper\Acceptance
step_decorators: ~        
```

I tried to change to selenium/standalone-chrome-debug image but it is not opening the browser also
