### ISSUE TITLE
How to use swarm selenium grid

### ISSUE THREAD

**Issue by zainal-abidin-assegaf** [SeleniumHQ/docker-selenium#1104]
How to use swarm selenium grid ?? 

from portainer everything is running properly,

![image](https://user-images.githubusercontent.com/22811935/91662841-24a43700-eb0f-11ea-8158-14cf57e5a74c.png)

Docker version: 18.06.3-ce
Docker-Compose version (if applicable): docker stack deploy -c selenium-grid.yaml selenium

selenium-distributor logs:
![image](https://user-images.githubusercontent.com/22811935/91662903-8cf31880-eb0f-11ea-9b0f-eacc462c650d.png)

selenium-event-bus logs:
![image](https://user-images.githubusercontent.com/22811935/91662925-ab591400-eb0f-11ea-80d5-16889b45e6b9.png)

selenium-router logs:
![image](https://user-images.githubusercontent.com/22811935/91662932-c2980180-eb0f-11ea-912e-da80d64ff44a.png)

selenium-sessions logs:
![image](https://user-images.githubusercontent.com/22811935/91662944-dba0b280-eb0f-11ea-93ee-39f2c8f2447e.png)

```
version: '3.7'

networks:
  bridge:
    external: true

services:
  selenium-event-bus:
    image: selenium/event-bus:4.0.0
    networks:
      - bridge
    ports:
      - "4442:4442"
      - "4443:4443"
      - "5560:5557"

  selenium-sessions:
    image: selenium/sessions:4.0.0
    networks:
      - bridge
    ports:
      - "5556:5556"
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=192.168.33.230
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-distributor:
    image: selenium/distributor:4.0.0
    networks:
      - bridge
    ports:
      - "5553:5553"
    depends_on:
      - selenium-event-bus
      - selenium-sessions
    environment:
      - SE_EVENT_BUS_HOST=192.168.33.230
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSIONS_MAP_HOST=192.168.33.230
      - SE_SESSIONS_MAP_PORT=5556

  selenium-router:
    image: selenium/router:4.0.0
    networks:
      - bridge
    ports:
      - "4444:4444"
    depends_on:
      - selenium-distributor
      - selenium-sessions
    environment:
      - SE_DISTRIBUTOR_HOST=192.168.33.230
      - SE_DISTRIBUTOR_PORT=5553
      - SE_SESSIONS_MAP_HOST=192.168.33.230
      - SE_SESSIONS_MAP_PORT=5556

  chrome:
    image: selenium/node-chrome:latest
    networks:
      - bridge
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=192.168.33.230
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:latest
    networks:
      - bridge
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=192.168.33.230
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  opera:
    image: selenium/node-opera:latest
    networks:
      - bridge
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=192.168.33.230
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
```
