### ISSUE TITLE
Unable to find provider for session

### ISSUE THREAD

**Issue by TomaszKolek** [SeleniumHQ/docker-selenium#1135]
## 🐛 Bug Report

I'm using 2 docker containers - hub and firefox.
Every 2 hours my python script starts ~79 drivers, one by one

```
for i in range(79):
    try:
        try:
            driver = ....
            # scrape something
        finally:
             driver.quit()
    except Exception as e:
         logger.error(e)
         continue
```
however, after some time of running containers, I receive `Unable to find provider for session:` error for every iteration.
The script works for some time, then it seems some sessions are not cleared, and it started raising the error for every driver we try to create

Also, container restart resolves the problem for some time

## To Reproduce

docker-compose
```
  selenium-hub:
      image: selenium/hub:4.0
      container_name: selenium-hub
      environment:
        - GRID_BROWSER_TIMEOUT=60
        - GRID_TIMEOUT=60
      ports:
        - "4442:4442"
        - "4443:4443"
        - "4444:4444"

  firefox:
    image: selenium/node-firefox:4.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6901:5900"
```

Exact script
```
for s in L: # L is list of 79 objects
    try:
            firefox_options = webdriver.FirefoxOptions()
            driver = webdriver.Remote(
                command_executor=settings.SELENIUM_HUB,
                desired_capabilities=firefox_options.to_capabilities(),
            )
            try:
                results = cls._request(driver, s)
                data = cls._process_results(results)
            finally:
                driver.quit()
    except Exception as e:
        logger.error(e)
        continue
```
## Expected behavior

Every session quits correctly so the session pool is always 16 at the end of the script

**Comment by omarmhaimdat** [comment]
The timeout part is still a mystery for me as well, I also noticed that it took around 5 minutes and 15 secondes for the grid (router in the case of full grid) to totally recognize that the session is totally cleared. Did you notice if the `GRID_BROWSER_TIMEOUT` variable is actually effective?

**Comment by TomaszKolek** [comment]
@omarmhaimdat not really, I run my script every 2h so thought that timeout will help here - but actually, it seems it has no effect

**Comment by diemol** [comment]
@TomaszKolek could you please paste the container logs?

**Comment by diemol** [comment]
@TomaszKolek, also, please try with the latest (pre)release. https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-beta-1-prerelease-20201130

**Comment by bdteo** [comment]
@TomaszKolek, I can report exactly the same happening. Here is my docker-compose.yml:

```
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-alpha-7-prerelease-20200921
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-alpha-7-prerelease-20200921
    container_name: selenium-hub
    ports:
      - "4442:4442" 
```

I am using Selenium through the `php-webdriver`, always quitting, having a similar (try/catch) piece of code:
```

    /**
     * @throws Throwable
     */
    public function run()
    {
        $exception = null;

        try {
            $driver = self::createChromeDriver(
                [
                    'disableImages' => !$this->downloadImages,
                    'disableJavaScript' => false,
                ]
            );
            $this->setDriver($driver);

            $this->executeAllTests();
        }
        catch (Throwable $throwable) {
            $exception = $throwable;
            $exceptionsDirectory = 'exceptions/' . strtolower(
                    OsHelpers::sanitizeFileName(
                        $exception->getMessage()
                    )
                );

            $testId = $this->getTestId() ?? 'null';
            $exceptionId = Str::random();

            $this->takeScreenshot(
                "$exceptionsDirectory/" .
                "test-id-$testId-$exceptionId.png"
            );
        }

        $this->driver->quit();

        if ($exception) {
            throw $exception;
        }
    }
```

The tests I am running happen every 24 hours. That is, the `run()` method is executed once every 24 hours.
Still, Selenium dies after some time, and all the tests fail to execute.
The exception I get is exactly the same: `Unable to find provider for session: ...`.

Currently, I resort to restarting my `systemd` containers service programmatically through php every single time I run the tests.
It was a bit complicated to set up the latter in a secure way and it is a clumsy solution but it works.
