### ISSUE TITLE
Selenium Hub sometimes uses 100% CPU usage at startup

### ISSUE THREAD

**Issue by Luc45** [SeleniumHQ/docker-selenium#1162]
## 🐛 Bug Report

Sometimes, when I start the Docker containers, the Selenium Hub process gets stuck at 100% CPU usage:

![selenium-100](https://user-images.githubusercontent.com/9341686/102346182-36560100-3f7d-11eb-9638-d40f9302dc5b.jpg)

When this happens, I have to restart the stack. Here's a screenshot after I did that:

![selenium-0](https://user-images.githubusercontent.com/9341686/102346340-71583480-3f7d-11eb-8c5f-f9d1d011da45.jpg)

Notice the column "CPU%" on both screenshots, and the "Command".

## To Reproduce

No need to do anything specific, just start the docker-compose stack.

## Expected behavior

I would like to consistently see the same result as in the second screenshot: Almost no CPU usage after starting the services.

## Test script reproducing this issue (when applicable)

I don't know how to reproduce this. I just start the containers and 3 out of 10 times it happens.

## Environment

OS: Manjaro 20.2
Docker-Selenium image version: 3 (updated to latest tag)
Also provide the docker image id 
```
selenium/standalone-chrome        3.141.59            94750fa10f22        3 months ago        918MB
selenium/node-chrome-debug        <none>              c28d488748be        3 months ago        949MB
selenium/hub                      <none>              dffdad82155b        3 months ago        263MB
```
Docker version: Docker version 19.03.13-ce, build 4484c46d9d
Docker-Compose version (if applicable): docker-compose version 1.27.4, build unknown
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

I start my containers with two instances of the Chrome nodes, so I can run tests in parallel: `docker-compose up -d --scale chrome=2 --remove-orphans`

```yml
hub:
  image: selenium/hub:3
  ports:
    - ${DOCKER_GATEWAY_IP}:4444:4444
chrome:
  image: selenium/node-chrome-debug:3
  volumes:
    - /dev/shm:/dev/shm
  depends_on:
    - hub
  environment:
    - HUB_HOST=hub
    - VNC_NO_PASSWORD=1
  ports:
    - ${DOCKER_GATEWAY_IP}:5900-5901:5900
  extra_hosts:
    - "${HOST_SINGLE_TESTS} ${HOST_MULTI_TESTS}:${DOCKER_GATEWAY_IP}"
```
