### ISSUE TITLE
Browser dies inside selenium container 3.141.59-oxygen

### ISSUE THREAD

**Issue by mikhalkaivan** [SeleniumHQ/docker-selenium#1170]
## 🐛 Bug Report

Hi, everyone. We use our internal artifactory image based on 3.141.59-oxygen (Chrome 74, chromedriver 74), for running test suites nightly. The largest test suite uses 5 threads and about 5 hours total duration. Apparently, maybe in 15% cases we face with browser crashes for that and for others test suites. Error message:
`org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.`
We monitor resource usage on Jenkins, and often it occurs on about 100% memory usage of node, but sometimes only on 65%, that is very confusing me. Also often we can see messages of oom_killer (dmesg command):
```
22:20:02  [26781247.638781] Out of memory: Kill process 119764 (chrome) score 308 or sacrifice child
22:20:02  [26781247.639633] Killed process 119764 (chrome) total-vm:1079844kB, anon-rss:63596kB, file-rss:9512kB
```
Interesting detail: increasing mem_limit on container doesn't help, but make it even worse. Based just on experience, we find optimal memory amount, about 2Gb.

My question: is it possible if not rid off but at least minimize this issue on 3.141.59-oxygen? Maybe, better use newest version?

## To Reproduce

Part of configuration from docker-compose.yml (some field was removed for privacy sake):

```
version: "2.3"
services:
  tests:
    extends:
      file: docker-compose.build.yml
      service: jdk-mvn
    depends_on:
      - selenium
    extra_hosts:
                ////
    environment:
               ////
    command: sh -c "mvn -B -U clean install -DskipTests && mvn -B test -pl module -Pprofile -Denvironment=staging -Dbrowser.type=REMOTE_CHROME_LINUX"

  selenium:
    container_name: selenium
    image: selenium-standalone-chrome:3.141.59-oxygen
    restart: always
    shm_size: '2gb'
    mem_limit: 2200m
    extra_hosts:
              ////
    environment:
              ////
    expose:
      - /////
```

Command for running: 
`docker-compose up -d selenium` (test suites stored in another container). Then, for running tests:
`docker-compose run --rm tests`

## Expected behavior

Successful test running, or at least clear understanding why it is happening, why increasing memory limit on container doesn't help, but makes crashes more frequent

## Environment

OS: Ubuntu about 16.04 (have no acces to node right now) 
Docker-Selenium image version: 3.141.59-oxygen 
Docker-Compose version: 2.3
