### ISSUE TITLE
Selenium Grid Helm Chart

### ISSUE THREAD

**Issue by pedromctech** [SeleniumHQ/docker-selenium#1184]
## 🚀 Feature Proposal

Hi guys. I worked in a Helm Chart for deploying the Selenium Grid in Kubernetes. Currently, I've seen two alternatives:

- [https://github.com/helm/charts/tree/master/stable/selenium](https://github.com/helm/charts/tree/master/stable/selenium)
- [https://github.com/ambirag/da-kubes](https://github.com/ambirag/da-kubes)

But the helm chart stored in the official helm repository is deprecated, and the @ambirag's helm chart seems to be outdated.

I'm taking as reference [k8s-deployment-full-grid.yaml file](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/k8s-deployment-full-grid.yaml) adding an opera node as well. This is the Helm Chart:

https://github.com/pedrodotmc/docker-selenium/tree/selenium-grid-helm-chart/chart/selenium-grid

I don't know whether to add the helm chart folder to this repository or to create a new one. I await your comments!

## Motivation

Currently, there is no (or I don't know) a Helm Chart that supports the deployment of Selenium Grid components separately.

## Example

```bash
# Clone the project
git clone https://github.com/pedrodotmc/docker-selenium.git

# Install basic grid
helm install selenium-grid docker-selenium/chart/selenium-grid/.

# Or install full grid (Router, Distributor, EventBus, SessionMap and SessionQueuer components separated)
helm install selenium-grid --set isolateComponents=true docker-selenium/chart/selenium-grid/.
```

**Comment by diemol** [comment]
Thank you for this, @pedrodotmc! This is something we really need :)
Please allow us a few days to complete other Grid related tasks and we'll back to you!

**Comment by Luckless** [comment]
Also very much interested in this. Particularly if it's brought up to date to support the opera and edge nodes as options too

**Comment by zzvara** [comment]
This is amazing! I just adopted your code, built a Helm Chart to our private repository, and now using the Hub.

Do you plan to add optional arguments to Hub, or is it configurable through environment variables, for example `-timeout 30`?

**Comment by electrical** [comment]
As a user of both Kubernetes and Selenium I wanted to provide some early feedback which might be useful.
On first glance it's great work! This saved me building our own.

I've noticed a few things which you might want to implement/consider:

* Services for all browsers are created even when they are not used. Selenium talks to each individual node directly so don't need the service IP's. If the aim is to provide a service for the VNC port I would suggest you create a service for each node individually and also use that with the registration, otherwise you have a 1 in x chance to get the right node. perhaps redesigning them into stateful sets could help with giving them a consistent naming.
* Currently people will have to talk to the `selenium-router` service for submitting jobs and the UI. This might be confusing. I would suggest creating a `selenium` service for all user interaction.
* All image tags are done individually. I would suggest adding a `global` part and add the `imageTag` there for the default value which can be overwritten individually. this way it's much easier to bump the version instead of doing it everywhere separately.
* The /dev/shm is currently unbound. Browsers can do weird things. I think it would be wise to limit the size to 1GB or something sensible.

**Comment by pedromctech** [comment]
> This is amazing! I just adopted your code, built a Helm Chart to our private repository, and now using the Hub.
> 
> Do you plan to add optional arguments to Hub, or is it configurable through environment variables, for example `-timeout 30`?

Hi @zzvara Currently, it's configurable through environment variables. If you deploy selenium separately, variables that you define will be added to all components.

**Comment by electrical** [comment]
@pedrodotmc happy to collaborate / help with anything you need. I'm planning to deploy this into my staging environment pretty soon :-)

**Comment by zzvara** [comment]
> > This is amazing! I just adopted your code, built a Helm Chart to our private repository, and now using the Hub.
> > Do you plan to add optional arguments to Hub, or is it configurable through environment variables, for example `-timeout 30`?
> 
> Hi @zzvara Currently, it's configurable through environment variables. If you deploy selenium separately, variables that you define will be added to all components.

I could not figure out how to do that? Could you demonstrate? Thanks!

**Comment by pedromctech** [comment]
@zzvara Sorry for answering late, I'm been very busy with othe stuff. You can set variables in your `values.yaml`, something like this:
```yaml
hub:
  extraEnvironmentVariables:
    - name: SE_SESSION_REQUEST_TIMEOUT
      value: "300"
```
In the same way, if you deploy components separately:
```yaml
components:
  extraEnvironmentVariables:
    - name: SE_SESSION_REQUEST_TIMEOUT
      value: "300"
```
Or you can use your custom docker image as well.

**Comment by pedromctech** [comment]
Hey guys, I'm been very busy last days, but I just implemented a new version with @electrical suggestions (except creation of selenium service, i think i'll need some help for implementing that). You can clone new version from branch [selenium-grid-helm-chart-0.2.0](https://github.com/pedrodotmc/docker-selenium/tree/selenium-grid-helm-chart-0.2.0), or if you prefer first version, it's in [selenium-grid-helm-chart-0.1.0](https://github.com/pedrodotmc/docker-selenium/tree/selenium-grid-helm-chart-0.1.0) branch. 
Thanks @electrical for your feedback.

**Comment by electrical** [comment]
@pedrodotmc changes look great. I'll try it out on the weekend and review. Thank you again for the great work on this!

**Comment by zzvara** [comment]
@pedrodotmc we are testing the new version as well.

In isolated deployment, the Grid does not seem to be working on our cluster. https://github.com/SeleniumHQ/docker-selenium/issues/1222

**Comment by electrical** [comment]
Deployed the updated version over the weekend and all looks good :-) @diemol perhaps worth for Selenium to setup a small helm repo for this?

**Comment by diemol** [comment]
@pedrodotmc, are you in the Selenium [Slack or IRC](https://www.selenium.dev/support/)? If not, could you please join and reach out to me? Thank you! 🙇

**Comment by Luckless** [comment]
How's this coming along? We'd like to get moved off the selenium chart in the old /stable repo if this is the new official one

**Comment by MantasGurskis** [comment]
hi @pedrodotmc, great job with the charts, I am trying to add browser_timout to selenium_hub, tried multiple options but nothing seems to help, browsers stay idle for about 5-6mins. Could you help me out here?
```
extraEnvironmentVariables:
    - name: TIMEOUT
      value: "30"
    - name: BROWSER_TIMEOUT
      value: "60"
    - name: browserTimeout
      value: "60"
    - name: GRID_BROWSER_TIMEOUT
      value: "60"
    - name: SE_SESSION_REQUEST_TIMEOUT
      value: "60"
```

**Comment by ilpianista** [comment]
FYI: I forked @pedrodotmc repo to add support for `nodeSelector`, `tolerations` and Edge nodes. It's in the [selenium-grid-helm-chart-0.3.0](https://github.com/ilpianista/docker-selenium/tree/selenium-grid-helm-chart-0.3.0) branch.

**Comment by peter-kinzelman** [comment]
![Screen Shot 2022-01-05 at 4 50 14 PM](https://user-images.githubusercontent.com/45794455/148294648-18ac786a-107a-401a-b56f-4618a206281a.png)
![Screen Shot 2022-01-05 at 4 49 54 PM](https://user-images.githubusercontent.com/45794455/148294649-3de60dc0-f58f-4c78-8208-6d2f0a785876.png)

Charts are awesome! What value do i need to set in order to see the VNC view via the remote Hub page inside of an individual session (sessions tab)

**Comment by palanisamy-hari** [comment]
> ![Screen Shot 2022-01-05 at 4 50 14 PM](https://user-images.githubusercontent.com/45794455/148294648-18ac786a-107a-401a-b56f-4618a206281a.png) ![Screen Shot 2022-01-05 at 4 49 54 PM](https://user-images.githubusercontent.com/45794455/148294649-3de60dc0-f58f-4c78-8208-6d2f0a785876.png)
> 
> Charts are awesome! What value do i need to set in order to see the VNC view via the remote Hub page inside of an individual session (sessions tab)

you will need to pass this ENV variable SE_NODE_GRID_URL -> [Explained in Readme](https://github.com/SeleniumHQ/docker-selenium#grid-url-and-session-timeout)

**Comment by tgupta-adc** [comment]
Will it get merged soon? my team would love to have it.

**Comment by diemol** [comment]
We are open to receive pull requests for this, we'd be happy to provide an official helm chart.

**Comment by tgupta-adc** [comment]
great!! I assumed that https://github.com/pedrodotmc/docker-selenium/tree/selenium-grid-helm-chart-0.2.0/chart/selenium-grid is something we intend to use based on issue description. I can wait for it to get merged.

**Comment by ilpianista** [comment]
> FYI: I forked @pedrodotmc repo to add support for `nodeSelector`, `tolerations` and Edge nodes. It's in the [selenium-grid-helm-chart-0.3.0](https://github.com/ilpianista/docker-selenium/tree/selenium-grid-helm-chart-0.3.0) branch.

We run our tests on this helm chart since August. If @pedrodotmc isn't interested anymore in merging this, I can open a new PR.

**Comment by diemol** [comment]
@ilpianista absolutely, we can also give credit to @pedrodotmc

**Comment by sidcarter** [comment]
@ilpianista are you able to open a PR for the helm chart please?

**Comment by maxnitze** [comment]
I was just looking for a chart and stumbled upon this. Thanks for the work!

I have a couple of ideas on how to improve the chart, that I would love to see added to it.

The pods do not use dedicated service accounts, which would be best practice from a security perspective.

More on the feature side, I think the way the nodes are configured is a bit too restricted. In my setup, for example, I use different versions of Chrome nodes for testing. And I could imagine many people do so.

So what I did pre-configure set of default node settings (a copy from the `chromeNode` settings) and the let the user provide a list of nodes to deploy. It looks somewhat like this:

```yaml
...
nodeDefaults:
  # Default Number of nodes
  replicas: 1
  # Default image pull policy (see https://kubernetes.io/docs/concepts/containers/images/#updating-images)
  imagePullPolicy: IfNotPresent
  # default port list to enable on container
  ports:
...
# Map of nodes. Name and tag of image need to be provided. Additionally, all "nodeDefaults" may be overwritten.
nodes: {}
#  chrome:
#    imageName: selenium/node-chrome
#    imageTag: 4.0.0-beta-1-prerelease-20210114
#    replicas: 3
```

Now there is only one template left for the nodes that looks like this (they were all pretty similar):

```yaml
{{- range $name, $node := .Values.nodes }}
{{- $nodeWithDefaults := merge $node $.Values.nodeDefaults }}
{{- $fullName := default (printf "selenium-node-%s" $name) $node.nameOverride | trunc 63 | trimSuffix "-" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
...
      volumes:
        - name: dshm
          emptyDir: { "medium": "Memory" }
{{- end }}
```

So in my own setup I now configured these nodes to be deployed:

```yaml
nodes:
  chrome:
    imageName: selenium/node-chrome
    imageTag: 3.141.59-20200525
    replicas: 10
  chrome74:
    imageName: selenium/node-chrome
    imageTag: 3.141.59-oxygen
    replicas: 6
  firefox:
    imageName: selenium/node-firefox
    imageTag: 3.141.59-20200525
    replicas: 10
```

(yes they are pretty old and I need to update :) )

What do you think?

How and when would be the best way to address these changes? I would wait for the PR to be merged and then create a new issue here to discuss? Or create a PR directly? How to deal with the "breaking changes"? Or support both?
