### ISSUE TITLE
INFO [LocalSessionMap.lambda$new$0] - Deleted session from local session map, Id: X

### ISSUE THREAD

**Issue by mbitar-gm** [SeleniumHQ/docker-selenium#1195]
## 🐛 Bug Report

Sometimes I dont want to driver.quit() at the end of the test, in order to make it easier to debug later.
So if a test fails, I am not using driver.quit() in order to keep the session open.
However, after a while, (saw that through vnc) the container is closing open chrome sessions.

INFO [LocalSessionMap.lambda$new$0] - Deleted session from local session map, Id: X

## To Reproduce

Run a session, driver.get(URL), and do not driver.quit(). 
Wait for a few minutes, the chrome windows will automatically close.

I am using this with java :

```
final ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("--no-sandbox");
        chromeOptions.addArguments("--disable-dev-shm-usage");
        chromeOptions.setAcceptInsecureCerts(true);
        Util.debug("Initiating Remote Web Driver...");
        return new RemoteWebDriver(new URL(GlobalEnv.getEnvValue("REMOTE_WEBDRIVER")),chromeOptions);
```

## Expected behavior

I expected for the chrome sessions to stay open.

## Test script reproducing this issue (when applicable)

Just start a driver session without .quit() when done.

## Environment

OS: Windows
Docker-Selenium image version: selenium/standalone-chrome:4.0.0-beta-1-prerelease-20210114.
Docker version: 20.10.2
Docker-Compose version (if applicable):  1.27.4
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): 
```
version: "3"
services:
  chrome:
    image: "selenium/standalone-chrome:4.0.0-beta-1-prerelease-20210114"
    ports:
      - "5900:5900"
      - "4444:4444"
    volumes:
      - "/dev/shm:/dev/shm"
```
