### ISSUE TITLE
GraphQL error: Can't serialize value (/grid/nodes[0]/status) : Invalid input for Enum 'Status'. Unknown value 'DOWN'

### ISSUE THREAD

**Issue by nithinstar093** [SeleniumHQ/docker-selenium#1217]
## 🐛 Bug Report

Seeing this GraphQL error: 
**Can't serialize value (/grid/nodes[0]/status) : Invalid input for Enum 'Status'. Unknown value 'DOWN' in the grid/console** for selenium 4.

selenium/hub:4.0.0-alpha-7-20201119

I'm trying to deploy selenium 4 to the Kubernetes cluster, I'm able to open the grid console and list all the deployed chrome and firefox nodes, but after quite sometime(2 hours or so), when I hit grid/console route I'm seeing above GraphQL error.

I have to delete the deployments and redeploy selenium hub again to get rid of graphql error, but this keeps happening after some time.

I tried to consume the latest 4.0.0-beta-1-20210215 version, I'm seeing Bad gateway when I deploy selenium hub with beta version(with the exact same config I'm able to deploy the alpha version but alpha version has sporadic Graphql error)

docker-compose.yml 

```
version: '3'

services:
  hub:
    image: selenium/hub:4.0.0
    container_name: hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  firefox:
    build: ./node-firefox
    image: selenium/node-firefox:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome:
    build: ./node-chrome
    image: selenium/node-chrome:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
```

## Expected behavior

Selenium 4 grid URL to be available all the time and do not see GraphQL error.

## Screenshots

Grid with nodes working as expected sometimes

<img width="1508" alt="Screenshot 2021-02-23 at 4 30 51 PM" src="https://user-images.githubusercontent.com/20794613/108834739-8fcd5280-75f4-11eb-92b6-8fad6532fd9f.png">

GrpahQL error 

<img width="1678" alt="Screenshot 2021-02-23 at 4 28 21 PM" src="https://user-images.githubusercontent.com/20794613/108834423-2e0ce880-75f4-11eb-99ae-60a529935ef8.png">
