### ISSUE TITLE
Error "KeyError: 'value'" when executing over 'opera' and 'edge' containers

### ISSUE THREAD

**Issue by diegoquirino** [SeleniumHQ/docker-selenium#1219]
## 🐛 Bug Report

When I execute robotframework script to 'opera' or 'edge' runing containers, error "KeyError: 'value'" is shown. With the same script, 'firefox' and 'chrome' runing containers works perfectly.

## To Reproduce

1. Create grid: `docker network create 20210223092457_grid`
2. Run container (edge or opera): `docker run -d -p 4444:4444 -p 6900:5900 --net 20210223092457_grid --name selenium -v /dev/shm:/dev/shm selenium/standalone-opera:4.0.0-beta-1-20210215`
3. Run robot test script: `robot --outputdir output *.robot`

## Expected behavior

It is expected test runs and pass by opening google.com website in the browser.

## Test script reproducing this issue (when applicable)

GitHub project: https://gitlab.com/diegoquirino/robot-edge.git
**Change browser using *locators.py* BROWSER variable and run *main.py* file.**

## Environment

OS: Windows 10
Docker-Selenium image version: 4.0.0-beta-1-20210215
Docker version: 20.10.2
Exact Docker command to start the containers:

- docker run -d -p 4444:4444 -p 6900:5900 --net 20210223092457_grid --name selenium -v /dev/shm:/dev/shm selenium/standalone-opera:4.0.0-beta-1-20210215

**Comment by PuppetA17** [comment]
I have the same problem, have you found the solution？

**Comment by diegoquirino** [comment]
> I have the same problem, have you found the solution？

Not yet. sorry!

**Comment by diemol** [comment]
Could you please provide a way to reproduce this with Selenium WebDriver? I am not a robotframework user so I cannot dig into it.

In the meantime, also providing the docker containers logs can be useful to diagnose the issue.

**Comment by domibarton** [comment]
> Could you please provide a way to reproduce this with Selenium WebDriver? I am not a robotframework user so I cannot dig into it.
> 
> In the meantime, also providing the docker containers logs can be useful to diagnose the issue.

There you go:

```python
from selenium.webdriver import Remote
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


driver = Remote(desired_capabilities=DesiredCapabilities.OPERA)
driver.get('https://www.selenium.dev/')
driver.close()
```

It results in (only for `DesiredCapabilities.OPERA` & `DesiredCapabilities.EDGE`:

```
Traceback (most recent call last):
  File "/tmp/selenium-error/tests/test.py", line 52, in <module>
    driver = Remote(desired_capabilities=DesiredCapabilities.OPERA)
  File "/tmp/selenium-error/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/tmp/selenium-error/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/tmp/selenium-error/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/tmp/selenium-error/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 127, in check_response
    value = value['value']
```

**Comment by diemol** [comment]
What version of the Python bindings are you using? Could you please share the logs of the docker containers as well?

**Comment by domibarton** [comment]
Btw I'm using the official grid/node Docker images. Here's my docker compose:

```yaml
---
version: '3.8'

services:

  chrome:
    image: selenium/node-chrome:4.0.0-beta-2-prerelease-20210312
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - '5901:5900'

  firefox:
    image: selenium/node-firefox:4.0.0-beta-2-prerelease-20210312
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - '5902:5900'

  edge:
    image: selenium/node-edge:4.0.0-beta-2-prerelease-20210312
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - '5903:5900'

  opera:
    image: selenium/node-opera:4.0.0-beta-2-prerelease-20210312
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - '5904:5900'

  selenium-hub:
    image: selenium/hub:4.0.0-beta-2-prerelease-20210312
    container_name: selenium-hub
    ports:
      - '4442:4442'
      - '4443:4443'
      - '4444:4444'
```
