### ISSUE TITLE
Unable to set Selenium logging level option via docker-compose

### ISSUE THREAD

**Issue by shiivan** [SeleniumHQ/docker-selenium#1242]
## 🐛 Bug Report

I've been attempting to set the logging level in the 4.0.0 beta release via SE_OPTS and get the generic help error which is telling me to do exactly what I'm attempting. I believe the help error and/or documentation needs to be updated.

## To Reproduce

My docker-compose file:
```
version: "3"
services:
    selenium:
        image: selenium/standalone-chrome:4.0.0-beta-2-prerelease-20210315
        environment:
          - SE_OPTS="--log-level SEVERE"
        volumes:
            # Share host memory with container.
            - /dev/shm:/dev/shm
        ports:
            - 4444:4444
            # VNC port for debugging.
            - 5901:5900
```

The truncated container log output:
```
Recreating new_scripts_selenium_1 ... done
Attaching to new_scripts_selenium_1
selenium_1  | 2021-03-19 00:17:32,464 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
selenium_1  | 2021-03-19 00:17:32,466 INFO supervisord started with pid 8
selenium_1  | 2021-03-19 00:17:33,469 INFO spawned: 'xvfb' with pid 10
selenium_1  | 2021-03-19 00:17:33,471 INFO spawned: 'vnc' with pid 11
selenium_1  | 2021-03-19 00:17:33,472 INFO spawned: 'selenium-standalone' with pid 12
selenium_1  | 2021-03-19 00:17:33,475 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1  | 2021-03-19 00:17:33,475 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1  | 2021-03-19 00:17:33,475 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1  | Was passed main parameter '"--log-level' but no main parameter was defined in your arg class
selenium_1  | Usage: standalone [options]
selenium_1  |    Options:
...
selenium_1  |       --log-level
selenium_1  |           Log level. Default logging level is INFO. Log levels are described here 
selenium_1  |           https://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html 
selenium_1  |           Default: INFO
...
selenium_1  | 2021-03-19 00:17:33,888 INFO exited: selenium-standalone (exit status 0; expected)
```

## Expected behavior

I'd expect the contianer to start Selenium with the given logging level, or I'd expect the helper error or documentation to provide clear example of how to pass SE_OPTS.

## Environment

OS: OSX (Catalina)
Docker-Selenium image version: 4.0.0-beta-2-prerelease-20210315

Docker version: Docker version 20.10.5, build 55c4c88
Docker-Compose version (if applicable): docker-compose version 1.28.5, build c4eb3a1f
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): See above.

**Comment by diemol** [comment]
There is no need to quote `--log-level SEVERE`

This works.

```yml
version: "3"
services:
    selenium:
        image: selenium/standalone-chrome:4.0.0-beta-2-20210317
        environment:
          - SE_OPTS=--log-level SEVERE
        volumes:
            # Share host memory with container.
            - /dev/shm:/dev/shm
        ports:
            - 4444:4444
            # VNC port for debugging.
            - 5901:5900
```
