### ISSUE TITLE
ERROR: Unable to find handler for (GET) /session

### ISSUE THREAD

**Issue by nithinstar093** [SeleniumHQ/docker-selenium#1248]
## 🐛 Bug Report

The selenium 4 grid is up and running with chrome and firefox nodes. When running tests against selenium 4 grid(K8s deployment), I'm getting ERROR: Unable to find handler for (GET) /session

I was able to able to run the tests locally with docker-compose up command.

This is the config I'm using while running tests 

```
  config.host = 'testing-selenium4.com';
  config.port = '80';
  config.path = "/"
```

Our tests were running fine with selenium 3 k8s deployment which had path - '/wd/hub/', here I have updated it to '/' since wd/hub was depreciated.

Any help and inputs would be appreicated.

## To Reproduce

I was not able to reproduce the issue locally, issue is happening only with K8s deployment of grid.

## Expected behavior

Able to run tests with K8s deployment of grid.

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

Docker-Selenium image version: 4.0.0-beta-3-prerelease-20210321
Also provide the docker image id 
-->
Docker-compose.yml

```
version: '3'

services:
  hub:
    image: selenium/hub:4.0.0-beta-1-20210215
    container_name: hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  firefox:
    build: ./node-firefox
    image: selenium/node-firefox:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome:
    build: ./node-chrome
    image: selenium/node-chrome:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
```
