### ISSUE TITLE
Selenium 4 [docker] -  SE_NODE_MAX_CONCURRENT_SESSIONS environmant variable doesn't apply

### ISSUE THREAD

**Issue by prokhoshin** [SeleniumHQ/docker-selenium#1249]
## 🐛 Bug Report

Grid 4. Unable to apply SE_NODE_MAX_CONCURRENT_SESSIONS param for node docker container

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):

1. Create docker-compose file (based on docker-compose-v3.yml from this repo)
2. Add SE_NODE_MAX_CONCURRENT_SESSIONS=3 environment variable
3. Run docker-compose
4. Check http://localhost:4444/status - there is still "maxSessions": 1

## Full response

```
{
  "value": {
    "ready": false,
    "message": "Selenium Grid not ready.",
    "nodes": [
      {
        "id": "fb68032c-8c71-4658-9170-786bed442880",
        "uri": "http:\u002f\u002f192.168.80.3:5555",
        "maxSessions": 1,
        "osInfo": {
          "arch": "amd64",
          "name": "Linux",
          "version": "4.19.104-microsoft-standard"
        },
        "heartbeatPeriod": 60000,
        "availability": "DOWN",
        "version": "4.0.0-beta-3 (revision 909239cd9f)",
        "slots": [
          {
            "lastStarted": "1970-01-01T00:00:00Z",
            "id": {
              "hostId": "fb68032c-8c71-4658-9170-786bed442880",
              "id": "2a0988de-2b5c-4af6-bb80-ee90bfa94f91"
            },
            "stereotype": {
              "browserName": "chrome",
              "platformName": "LINUX"
            }
          }
        ]
      }
    ]
  }
}
```

## Expected behavior

"maxSessions" param should be equal 3

## Test script reproducing this issue (when applicable)

docker-compose up -d

Invoke-WebRequest 'http://localhost:4444/status' | Select-Object -Expand Content

## Environment

OS:  Windows 10
Docker-Selenium image version: 4.0.0-beta-3-prerelease-20210321
Docker version: 20.10.5, build 55c4c88
Docker-Compose version (if applicable): 1.28.5, build c4eb3a1f
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

```
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210321
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_CONCURRENT_SESSIONS=3
    ports:
      - "6900:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-beta-3-prerelease-20210321
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

**Comment by diemol** [comment]
How many CPUs do you have available?

**Comment by prokhoshin** [comment]
Should be 4 cores + 4 virtual cores

Next command was executed inside the node container: 

seluser@e1a96c49e536:/$ lscpu
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       GenuineIntel
```

seluser@e1a96c49e536:/$ nproc
`8`

**Comment by prokhoshin** [comment]
Hi @diemol 
I checked the source code and found a method to get the number of sessions
```
  public int getMaxSessions() {
    return Math.min(
      config.getInt(NODE_SECTION, "max-sessions").orElse(DEFAULT_MAX_SESSIONS),
      DEFAULT_MAX_SESSIONS);
  }
```
If I understand the code correctly, for the environment variables, this parameter is transformed into
**SE_NODE_MAX_SESSIONS** (not SE_NODE_MAX_CONCURRENT_SESSIONS)
So I tried to run next docker-compose and looks like all good now.

**docker-compose.yml**
```
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210321
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
    ports:
      - "6900:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-beta-3-prerelease-20210321
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```
**Response from http://localhost:4444/status**
```
{
  "value": {
    "ready": true,
    "message": "Selenium Grid ready.",
    "nodes": [
      {
        "id": "26bf6be6-a531-4ff3-9396-43b4c190dc46",
        "uri": "http:\u002f\u002f172.19.0.3:5555",
        "maxSessions": 3,
        "osInfo": {
          "arch": "amd64",
          "name": "Linux",
          "version": "4.19.104-microsoft-standard"
        },
        "heartbeatPeriod": 60000,
        "availability": "UP",
        "version": "4.0.0-beta-3 (revision 909239cd9f)",
        "slots": [
          {
            "lastStarted": "1970-01-01T00:00:00Z",
            "stereotype": {
              "browserName": "chrome",
              "platformName": "LINUX"
            },
            "id": {
              "hostId": "26bf6be6-a531-4ff3-9396-43b4c190dc46",
              "id": "4b6e274f-3d6d-4ad3-9c87-454368d276ce"
            }
          },
          {
            "lastStarted": "1970-01-01T00:00:00Z",
            "stereotype": {
              "browserName": "chrome",
              "platformName": "LINUX"
            },
            "id": {
              "hostId": "26bf6be6-a531-4ff3-9396-43b4c190dc46",
              "id": "c7323f96-ad20-4009-8c34-4462e12aeedb"
            }
          },
          {
            "lastStarted": "1970-01-01T00:00:00Z",
            "stereotype": {
              "browserName": "chrome",
              "platformName": "LINUX"
            },
            "id": {
              "hostId": "26bf6be6-a531-4ff3-9396-43b4c190dc46",
              "id": "37ea0d1c-951a-48f9-a14e-b2b95e27835b"
            }
          }
        ]
      }
    ]
  }
}
```
I searched and tried many variations of the name of this parameter before creating this bug. And it looks like this option was not among them.

Checked commits and yeah, param name was changed on March 6, 2021 [https://github.com/SeleniumHQ/selenium/commit/0a19bc4613dabbaaad01d921e3717cc4a309db72](url)
