### ISSUE TITLE
SE_NODE_SESSION_TIMEOUT does not close browser if the browser is still trying to fetch the resource (same for GRID_TIMEOUT is selenium 3)

### ISSUE THREAD

**Issue by JannisBush** [SeleniumHQ/docker-selenium#1283]
## 🐛 Bug Report

When a page takes longer to load than the `SE_NODE_SESSION_TIMEOUT` timeout is configured, the client loses connection to the browser and cannot close the browser anymore using `driver.quit()` (expected behavior). However, the browser is also not closed by the grid/the code in the container after the timeout happened. This might be expected behavior (or there might be another setting where one can configure this I have not found yet), but this quickly leads to many stale browsers open, eventually crashing the container or having the grid refusing to start a new session. (As a workaround I can set the `page_load_timeout` parameter to a smaller value and then close the browser using `driver.quit()` when that timeout event is fired)

## To Reproduce

- Start the containers using docker-compose
- Load a page with a very slow loading time (needs to be higher than `SE_NODE_SESSION_TIMEOUT`)
- Wait (timeout will happen, driver.close() does not work, browser is still open)
- Connect to the container using VNC and see that the browser is still open (or run the script several times, after ~5 times it won't start anymore)

## Expected behavior

I expect that the browser gets killed after the session timeouts.

## Test script reproducing this issue (when applicable)
 
Selenium client code:
```
from selenium import webdriver

grid_url = "http://localhost:4444/wd/hub"
def get_driver():
    return webdriver.Remote(
        command_executor=grid_url,
        options=webdriver.ChromeOptions())

try:    
    driver = get_driver()
    try:
        driver.get("http://172.17.0.1:8080")
    except Exception as e:
        print(e)
finally:
    try:
        driver.quit()
    except Exception as e:
        print("Fatal error", e)
```
(save as `test.py` and run with `python test.py`

Simple server that will take longer to answer than `SE_NODE_SESSION_TIMEOUT`:
```
import BaseHTTPServer
import time

class Handler( BaseHTTPServer.BaseHTTPRequestHandler ):
    def do_GET( self ):
        time.sleep(6000)
        self.send_response(200)
        self.send_header( 'Content-type', 'text/html' )
        self.end_headers()

httpd = BaseHTTPServer.HTTPServer( ('172.17.0.1', 8080), Handler )
httpd.serve_forever()
```
(Save as `server.py` and run with `python server.py`)

## Environment

OS: Ubuntu 18.04.5 LTS
Docker-Selenium image version: 4.0.0-beta-3-20210426 (also affects other versions)
Also provide the docker image id 
--> selenium/node-chrome:4.0.0-beta-3-20210426 (affects all browsers)
Docker version: Docker version 20.10.6, build 370c289
Docker-Compose version: docker-compose version 1.17.1
Exact Docker command to start the containers: `sudo docker-compose -f docker-compose-v3.yml up`

(Save as docker-compose-v3.yml)
```
# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=30
    ports:
      - "6900:5900"

  edge:
    image: selenium/node-edge:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=30
    ports:
      - "6901:5900"

  firefox:
    image: selenium/node-firefox:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=30
    ports:
      - "6902:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-beta-3-20210426
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

**Comment by duolabmeng6** [comment]
![image](https://user-images.githubusercontent.com/59047063/119082782-58bedf80-ba31-11eb-975a-3e94aed107c6.png)
I also encountered how to solve the problem, how to close the browser process overtime

**Comment by duolabmeng6** [comment]
```
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20210422
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      #- GRID_MAX_SESSION=10 # 最大会话数量 指连接数
      - GRID_TIMEOUT=1000
      - GRID_BROWSER_TIMEOUT=2
      - JAVA_OPTS=-Xmx512m
      #- SE_OPTS="-debug"
      #- SE_OPTS=-browserTimeout 10 -timeout 10 -newSessionWaitTimeout 10
      - SE_OPTS=-newSessionWaitTimeout 300000 #毫秒 队列会话超时时间 就是提交上去的任务 如果超时就丢弃不会堵着
  chrome:
    image: selenium/node-chrome-debug:3.141.59-20210422
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
      - SCREEN_WIDTH=1366
      - SCREEN_HEIGHT=768
      - SCREEN_DEPTH=24
      - START_XVFB=false
    ports:
      - "5900:5900"
#  firefox:
#    image: selenium/node-firefox:3.141.59-20210422
#    depends_on:
#      - selenium-hub
#    environment:
#      - HUB_HOST=selenium-hub
#      - HUB_PORT=4444
#      - NODE_MAX_INSTANCES=10
#      - NODE_MAX_SESSION=10
#      - SCREEN_WIDTH=1366
#      - SCREEN_HEIGHT=768
#      - SCREEN_DEPTH=24
```

It's solved

```
SE_OPTS=-newSessionWaitTimeout 300000
```

**Comment by JannisBush** [comment]
Hi @duolabmeng6 
I think you had a another error and used selenium 3.
The `newSessionWaitTimeout` specifies how long a new request waits until a free node is available. `timeout`, `GRID_TIMEOUT` or `SE_NODE_SESSION_TIMEOUT` (in selenium4) specifies after what time period a stale session is terminated. `GRID_BROWSER_TIMEOUT` or `browserTimeout` specifies how long a browser should try to load a resource before it times out.

I just tested my original error with selenium 3 and it also occurs there (and I have some more details). 
Summary: If the loading of a resource takes longer than the sessionTimeout, the session is released but the browser is not terminated. 

New docker-compose file (selenium 3):
```
version: "3"
services:
  selenium-hub2:
    image: selenium/hub:3.141.59-20210422
    container_name: selenium-hub2
    ports:
      - "4444:4444"
    environment:
      #- GRID_TIMEOUT=10
      #- GRID_BROWSER_TIMEOUT=2
      - JAVA_OPTS=-Xmx512m
      - SE_OPTS=-browserTimeout 5 -timeout 10 -newSessionWaitTimeout 10
  chrome:
    image: selenium/node-chrome-debug:3.141.59-20210422
    depends_on:
      - selenium-hub2
    environment:
      - HUB_HOST=selenium-hub2
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
      - SCREEN_WIDTH=1366
      - SCREEN_HEIGHT=768
      - SCREEN_DEPTH=24
      - START_XVFB=true
    ports:
      - "5900:5900"
```
New test script (intentionally not calling driver.quit():
```
import os
from selenium import webdriver

grid_url = "http://localhost:4444/wd/hub"
def get_driver():
    return webdriver.Remote(
        command_executor=grid_url,
        options=webdriver.ChromeOptions())
try:    
    driver = get_driver()
    driver.get("http://172.17.0.1:8080")
except Exception as e:
        print(e)
```

New server file (python3 compatible):
```
from http.server import BaseHTTPRequestHandler,HTTPServer
import time

class Handler(BaseHTTPRequestHandler):
    def do_GET( self ):
        time.sleep(6000)
        self.send_response(200)
        self.send_header( 'Content-type', 'text/html' )
        self.end_headers()

httpd = HTTPServer( ('172.17.0.1', 8080), Handler )
httpd.serve_forever()
```

1. Start the container `docker-compose up`
2. Connect to the container using vnc on port 5900, pw secret
3. Run `test.py` without the server started
4. Result: output of the script `Message: unknown error: net::ERR_CONNECTION_REFUSED`, after the specified timeout of 10s the browser is killed and the session released (as expected, correct behavior)
5. Start the server: `python server.py`
6. Run `test.py` again
7. Result: The script will try to load the page for the specified 5 seconds and then exit. The node will try to load the page forever (not stop after 5 seconds). The browser is not killed after 10 seconds (it will stay open forever). After 10 seconds the session is released and we can start the script again leading to many browsers open in the container (see attached screenshot). (Maybe, this is a selenium issue and not a docker-selenium one?)

![Screenshot from 2021-05-21 11-35-49](https://user-images.githubusercontent.com/33023300/119117084-2b6e3380-ba29-11eb-980a-9baaa6f568b0.png)

What I did to workaround the problem for now:
- Specify the  `page_load_timeout` parameter in my client code, you can the catch a timeout exception and close the driver yourself.
- Use the dynamic-grid setting of selenium 4, such that stale browsers are not a problem anymore.

**Comment by duolabmeng6** [comment]
```
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20210422
    container_name: selenium-hub
    ports:
      - 4444:4444
    environment:
      - GRID_MAX_SESSION=1000 # 最大会话数量 指连接数
      - GRID_MAX_INSTANCES=1000 # 最大会话数量 指连接数
      - GRID_TIMEOUT=20 # 单位: 秒
      - GRID_BROWSER_TIMEOUT=20 # 单位: 秒 关闭浏览器的时间
      - JAVA_OPTS=-Xmx512m
      - SE_OPTS=-newSessionWaitTimeout 200000 #毫秒 队列会话超时时间 就是提交上去的任务 如果超时就丢弃不会堵着
  chrome:
    image: selenium/node-chrome-debug:3.141.59-20210422
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2
      - SCREEN_WIDTH=1366
      - SCREEN_HEIGHT=768
      - SCREEN_DEPTH=24
      #- START_XVFB=false
    ports:
      - 5900:5900
```

I tested 20 seconds to shut down the browser
```
      - GRID_TIMEOUT=20 # Unit second
      - GRID_BROWSER_TIMEOUT=20 # Unit second Time to close browser
      - JAVA_OPTS=-Xmx512m
      - SE_OPTS=-newSessionWaitTimeout 200000 # Unit millisecond Queue session timeout is the task submitted to it. If it times out, it will be discarded and will not be blocked
```
Important parameters 
`GRID_BROWSER_TIMEOUT=20`
`SE_OPTS=-newSessionWaitTimeout 200000`

20 seconds will shut down correctly

**Comment by duolabmeng6** [comment]
> @ duolabmeng6，您好：
> 我认为您还有另一个错误，并使用了硒3。
> 它`newSessionWaitTimeout`指定了一个新请求等待一个空闲节点可用之前要等待多长时间。`timeout`，`GRID_TIMEOUT`或`SE_NODE_SESSION_TIMEOUT`（在selenium4中）指定在多长时间后终止陈旧会话。`GRID_BROWSER_TIMEOUT`或`browserTimeout`指定浏览器在超时之前应尝试加载资源的时间。
> 
> 我刚刚用硒3测试了我的原始错误，并且它也在那里发生了（我还有一些详细信息）。
> 摘要：如果资源的加载花费的时间超过sessionTimeout，则释放会话，但不会终止浏览器。
> 
> 新的docker-compose文件（硒3）：
> 
> ```
> version: "3"
> services:
>   selenium-hub2:
>     image: selenium/hub:3.141.59-20210422
>     container_name: selenium-hub2
>     ports:
>       - "4444:4444"
>     environment:
>       #- GRID_TIMEOUT=10
>       #- GRID_BROWSER_TIMEOUT=2
>       - JAVA_OPTS=-Xmx512m
>       - SE_OPTS=-browserTimeout 5 -timeout 10 -newSessionWaitTimeout 10
>   chrome:
>     image: selenium/node-chrome-debug:3.141.59-20210422
>     depends_on:
>       - selenium-hub2
>     environment:
>       - HUB_HOST=selenium-hub2
>       - HUB_PORT=4444
>       - NODE_MAX_INSTANCES=1
>       - NODE_MAX_SESSION=1
>       - SCREEN_WIDTH=1366
>       - SCREEN_HEIGHT=768
>       - SCREEN_DEPTH=24
>       - START_XVFB=true
>     ports:
>       - "5900:5900"
> ```
> 
> 新的测试脚本（故意不调用driver.quit（）：
> 
> ```
> import os
> from selenium import webdriver
> 
> grid_url = "http://localhost:4444/wd/hub"
> def get_driver():
>     return webdriver.Remote(
>         command_executor=grid_url,
>         options=webdriver.ChromeOptions())
> try:    
>     driver = get_driver()
>     driver.get("http://172.17.0.1:8080")
> except Exception as e:
>         print(e)
> ```
> 
> 新服务器文件（与python3兼容）：
> 
> ```
> from http.server import BaseHTTPRequestHandler,HTTPServer
> import time
> 
> class Handler(BaseHTTPRequestHandler):
>     def do_GET( self ):
>         time.sleep(6000)
>         self.send_response(200)
>         self.send_header( 'Content-type', 'text/html' )
>         self.end_headers()
> 
> httpd = HTTPServer( ('172.17.0.1', 8080), Handler )
> httpd.serve_forever()
> ```
> 
> 1. 启动容器 `docker-compose up`
> 2. 使用端口5900上的vnc连接到容器，pw secret
> 3. 在`test.py`不启动服务器的情况下运行
> 4. 结果：脚本的输出`Message: unknown error: net::ERR_CONNECTION_REFUSED`，在指定的10s超时后，浏览器被杀死并释放了会话（按预期，正确的行为）
> 5. 启动服务器： `python server.py`
> 6. 再跑`test.py`一次
> 7. 结果：该脚本将尝试在指定的5秒钟内加载页面，然后退出。节点将尝试永久加载页面（5秒后不会停止）。10秒后浏览器不会被杀死（它将永远保持打开状态）。10秒后，会话释放，我们可以再次启动脚本，从而导致容器中打开了许多浏览器（请参阅随附的屏幕截图）。（也许这是一个硒问题，而不是docker-selenium一个？）
> 
> ![2021-05-21 11-35-49的屏幕截图](https://user-images.githubusercontent.com/33023300/119117084-2b6e3380-ba29-11eb-980a-9baaa6f568b0.png)
> 
> 我目前为解决该问题所做的工作：
> 
> * `page_load_timeout`在我的客户端代码中指定  参数，您可以捕获超时异常并自行关闭驱动程序。
> * 使用硒4的动态网格设置，这样陈旧的浏览器就不再成为问题。



> Hi @duolabmeng6
> I think you had a another error and used selenium 3.
> The `newSessionWaitTimeout` specifies how long a new request waits until a free node is available. `timeout`, `GRID_TIMEOUT` or `SE_NODE_SESSION_TIMEOUT` (in selenium4) specifies after what time period a stale session is terminated. `GRID_BROWSER_TIMEOUT` or `browserTimeout` specifies how long a browser should try to load a resource before it times out.
> 
> I just tested my original error with selenium 3 and it also occurs there (and I have some more details).
> Summary: If the loading of a resource takes longer than the sessionTimeout, the session is released but the browser is not terminated.
> 
> New docker-compose file (selenium 3):
> 
> ```
> version: "3"
> services:
>   selenium-hub2:
>     image: selenium/hub:3.141.59-20210422
>     container_name: selenium-hub2
>     ports:
>       - "4444:4444"
>     environment:
>       #- GRID_TIMEOUT=10
>       #- GRID_BROWSER_TIMEOUT=2
>       - JAVA_OPTS=-Xmx512m
>       - SE_OPTS=-browserTimeout 5 -timeout 10 -newSessionWaitTimeout 10
>   chrome:
>     image: selenium/node-chrome-debug:3.141.59-20210422
>     depends_on:
>       - selenium-hub2
>     environment:
>       - HUB_HOST=selenium-hub2
>       - HUB_PORT=4444
>       - NODE_MAX_INSTANCES=1
>       - NODE_MAX_SESSION=1
>       - SCREEN_WIDTH=1366
>       - SCREEN_HEIGHT=768
>       - SCREEN_DEPTH=24
>       - START_XVFB=true
>     ports:
>       - "5900:5900"
> ```
> 
> New test script (intentionally not calling driver.quit():
> 
> ```
> import os
> from selenium import webdriver
> 
> grid_url = "http://localhost:4444/wd/hub"
> def get_driver():
>     return webdriver.Remote(
>         command_executor=grid_url,
>         options=webdriver.ChromeOptions())
> try:    
>     driver = get_driver()
>     driver.get("http://172.17.0.1:8080")
> except Exception as e:
>         print(e)
> ```
> 
> New server file (python3 compatible):
> 
> ```
> from http.server import BaseHTTPRequestHandler,HTTPServer
> import time
> 
> class Handler(BaseHTTPRequestHandler):
>     def do_GET( self ):
>         time.sleep(6000)
>         self.send_response(200)
>         self.send_header( 'Content-type', 'text/html' )
>         self.end_headers()
> 
> httpd = HTTPServer( ('172.17.0.1', 8080), Handler )
> httpd.serve_forever()
> ```
> 
> 1. Start the container `docker-compose up`
> 2. Connect to the container using vnc on port 5900, pw secret
> 3. Run `test.py` without the server started
> 4. Result: output of the script `Message: unknown error: net::ERR_CONNECTION_REFUSED`, after the specified timeout of 10s the browser is killed and the session released (as expected, correct behavior)
> 5. Start the server: `python server.py`
> 6. Run `test.py` again
> 7. Result: The script will try to load the page for the specified 5 seconds and then exit. The node will try to load the page forever (not stop after 5 seconds). The browser is not killed after 10 seconds (it will stay open forever). After 10 seconds the session is released and we can start the script again leading to many browsers open in the container (see attached screenshot). (Maybe, this is a selenium issue and not a docker-selenium one?)
> 
> ![Screenshot from 2021-05-21 11-35-49](https://user-images.githubusercontent.com/33023300/119117084-2b6e3380-ba29-11eb-980a-9baaa6f568b0.png)
> 
> What I did to workaround the problem for now:
> 
> * Specify the  `page_load_timeout` parameter in my client code, you can the catch a timeout exception and close the driver yourself.
> * Use the dynamic-grid setting of selenium 4, such that stale browsers are not a problem anymore.

After my repeated tests, there should be no problem

I tested docker-selenium 4 and couldn't solve it, so I changed docker-selenium 3

**Comment by duolabmeng6** [comment]
![image](https://user-images.githubusercontent.com/59047063/119122582-3ba20500-ba61-11eb-9d73-2db23103b206.png)
![image](https://user-images.githubusercontent.com/59047063/119122846-8c196280-ba61-11eb-947a-cb2012c288ad.png)
The browser was closed at about 45s

I don't know how to set parameters. It seems invalid

Timeout. The queue is not cleared
`- SE_OPTS=-newSessionWaitTimeout 200000` Parameter cannot be set

I think it's a bug. I use selenium 3 to follow up


Here's my configuration, but it doesn't work. Timeout doesn't shut down the browser, it's blocked all the time
```
version: "3"
services:
  selenium-hub:
    image: selenium/hub:4
    container_name: selenium-hub
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    environment:
      - GRID_MAX_SESSION=1000 # 最大会话数量 指连接数
      - GRID_MAX_INSTANCES=1000 # 最大会话数量 指连接数
      - GRID_TIMEOUT=10 # 单位: 秒
      - GRID_BROWSER_TIMEOUT=10 # 单位: 秒 关闭浏览器的时间
      - JAVA_OPTS=-Xmx512m
      - SE_NODE_SESSION_TIMEOUT=10
      #- SE_OPTS="-debug"
      #- SE_OPTS=-browserTimeout 10 -timeout 10 -newSessionWaitTimeout 10
      #- SE_OPTS=-newSessionWaitTimeout 200000 #毫秒 队列会话超时时间 就是提交上去的任务 如果超时就丢弃不会堵着
  chrome:
    image: selenium/node-chrome:4
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2
      - SCREEN_WIDTH=1366
      - SCREEN_HEIGHT=768
      - SCREEN_DEPTH=24
      #- START_XVFB=false
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=10
    ports:
      - 5900:5900

```


Existing problems

1. Unable to set the time to close the browser

2. Unable to set the task queue clear time

3.100 and send the queue blocking, causing the docker to crash

Maybe I'm not familiar with how to configure, I hope there are big guys' advice
