### ISSUE TITLE
Selenium node is not stopped gracefully

### ISSUE THREAD

**Issue by ibalosh** [SeleniumHQ/docker-selenium#1291]
## 🐛 Bug Report

Selenium node and hub are started up via docker-compose - with 1 total slots. Test is started and takes up one session.
While test was running `docker stop --time=30 [CONTAINER_ID]` command was executed for docker container selenium-node. This triggers SIGTERM signal, which is ok. The problem is that docker container node is stopped right away. Shouldn't it be stopped once the test is done or timeout is reached? Test itself is ~20 seconds long.

## To Reproduce

* run docker-compose up 
* run any test which uses selenium and takes ~20 seconds
* after test is started run docker stop --time=30 [NODE_CONTAINER_ID] to stop selenium node container 

## Expected behavior

Expected test to pass since it's short and can be executed before graceful shutdown of docker selenium node container.
Instead container was stopped right away.

## Environment

OS: OSX 10.15.7 (MacOS Catalina)
Docker compose file used:

```
version: "3.8"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-beta-4-prerelease-20210517
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=300
      - JAVA_OPTS=-XX:ActiveProcessorCount=1
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - START_XVFB=false
      - SCREEN_DEPTH=24
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=1024
    restart: "no"

  selenium-hub:
    image: selenium/hub:4.0.0-beta-4-prerelease-20210517
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    restart: "no"
```

Video example attached.

![selenium](https://user-images.githubusercontent.com/14041/118800800-99d3ba00-b8a0-11eb-8d2f-08b069259c3d.gif)

Selenium hub logs attached:

[selenium-logs.txt](https://github.com/SeleniumHQ/docker-selenium/files/6508069/selenium-logs.txt)

Ruby logs attached:

[selenium-ruby-logs.txt](https://github.com/SeleniumHQ/docker-selenium/files/6508104/selenium-ruby-logs.txt)

Used Ruby gem version:

gem 'selenium-webdriver', '~> 4.0.0.beta3'
