### ISSUE TITLE
Parallel execution

### ISSUE THREAD

**Issue by shivam1397a** [SeleniumHQ/docker-selenium#1304]
HI,

I am working on a POC for Selenium Grid 4 implementation. I am using BDD framework with Java and maven. I am using Junit to execute features in parallel. I used docker-compose to create selenium grid and it is working fine and also I am able to execute one Feature file at a time. But when I am trying to execute my scripts in parallel mode(multiple session for one browser per execution), I am getting 'Could not start a new session' error and only one of the Feature files is running(Note: I am able run my script in parallel in my local machine). I am using below lines in my Java file:
```
DesiredCapabilities cap = new DesiredCapabilities(); 
cap.setCapability(ChromeOptions.CAPABILITY, chromeOptions.addArguments("window-size=1760,1020","--headless","--disable-dev-shm-usage","--no-sandbox"));
cap.setBrowserName("chrome");
driver = new RemoteWebDriver(new URL("http://localhost:4444"), cap);
```

Below is my docker-compose.yml:
```
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-beta-4-prerelease-20210527
    volumes:
      - /dev/shm:/dev/shm
     depends_on:
      - selenium-hub
     environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442 
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
     ports: 
     - "6900:5900"
  edge:
    image: selenium/node-edge:4.0.0-beta-4-prerelease-20210527
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub 
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
    ports: 
     - "6901:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-beta-4-prerelease-20210527 
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```
Could someone help me in figuring out how the parallel execution can be achieved here?
