### ISSUE TITLE
Starting hub on Docker on Apple M1 / Apple Silicon Mac crashes with "Could not find a non-loopback ip4 address for this machine" error

### ISSUE THREAD

**Issue by darxmac** [SeleniumHQ/docker-selenium#1315]
## 🐛 Bug Report

Starting a hub and chrome node with docker-compose on Apple Silicon crashes with this exception:

```
chrome_1      | Exception in thread "main" org.openqa.selenium.WebDriverException: Could not find a non-loopback ip4 address for this machine
chrome_1      | Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
chrome_1      | System info: host: 'ed6859b3ddc8', ip: '172.50.7.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.25-linuxkit', java.version: '1.8.0_212'
chrome_1      | Driver info: driver.version: unknown
chrome_1      |         at org.openqa.selenium.net.NetworkUtils.getIp4NonLoopbackAddressOfThisMachine(NetworkUtils.java:73)
```

## To Reproduce

Spin up the referenced docker-compose spec on M1 Mac (MacMini)

## Expected behavior

Not crashing with `org.openqa.selenium.net.NetworkUtils.getIp4NonLoopbackAddressOfThisMachine`

## Environment

OS: macOS 11.2.2 (20D80)
Docker-Selenium image version: 
selenium/node-chrome 3.141.59 | 0843e55de3dc
selenium/hub  3.141.59  705be32777f0
Docker version:  Docker version 20.10.7, build f0df350
Docker-Compose version docker-compose version 1.29.2, build 5becea4c
Exact Docker command to start the containers:

```
version: '3.6'

services:
  chrome:
    image: selenium/node-chrome:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
      - HUB_HOST=hub
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    ports:
      - "5555:5555"
  hub:
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"
    environment:
      - SE_OPTS=-browserTimeout 0 -timeout 60
```
