### ISSUE TITLE
Pass env vars to containers created through dynamic grid.

### ISSUE THREAD

**Issue by JannisBush** [SeleniumHQ/docker-selenium#1319]
## 🐛 Bug Report

Setting `SE_NODE_MAX_SESSIONS` and `SE_NODE_OVERRIDE_MAX_SESSIONS` in the dynamic grid/node-docker mode does nothing. 

## To Reproduce

- Run `docker-compose -f dynamic.yml up`
- VIsit http://localhost:4444/ui/index.html#/ and see that the max concurrency was not updated.

## Expected behavior

The max concurrency is updated to the wanted value. This works when the option is used with the non-dynamic mode/node-chrome, but not for the dynamic mode.
- Screenshot for `dynamic.yml`:
![image](https://user-images.githubusercontent.com/33023300/123096802-c0e95280-d42f-11eb-96ca-d04a78819c01.png)

- Screenshot for `non-dynamic.yml`:
![image](https://user-images.githubusercontent.com/33023300/123096676-a1eac080-d42f-11eb-8281-2f73079bd92e.png)

## Test script reproducing this issue (when applicable)

Dynamic.yml:
```yml
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.0.0-rc-1-prerelease-20210618
    volumes:
      - ./assets:/opt/selenium/assets
      - ./NodeDocker/config.toml:/opt/bin/config.toml
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=80
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
 
  selenium-hub:
    image: selenium/hub:4.0.0-rc-1-prerelease-20210618
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
 ```
config.toml:
```toml
[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618", "{\"browserName\": \"chrome\"}"
    ]

# URL for connecting to the docker daemon
# host.docker.internal works for macOS and Windows.
# Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
# To have Docker listening through tcp on macOS, install socat and run the following command
# socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
url = "http://172.17.0.1:2375"
# Docker image used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20210426"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
#[server]
#host = <ip-from-node-machine>
#port = <port-from-node-machine>
```

Working docker-compose file (`non-dynamic.yml`):
```yml
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-rc-1-prerelease-20210618
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=80
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    ports:
      - "6900:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-rc-1-prerelease-20210618
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444
```

## Environment

OS: Ubuntu 18.04
Docker-Selenium image version:  4.0.0-rc-1-prerelease-20210618
Also provide the docker image id 
--> selenium/node-docker:4.0.0-rc-1-prerelease-20210618
Docker version: Docker version 20.10.7, build f0df350
Docker-Compose version (if applicable): docker-compose version 1.17.1
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): `docker-compose -f dynamic.yml up`

**Comment by rafaelsart** [comment]
I'm having exactly the same issue.

**Comment by diemol** [comment]
Dynamic Grid does not have this enabled due to the nature of it, since it spins a docker container per each executed test, therefore it really needs that the available CPUs are there.

In the example you provide to reproduce the issue, you want to overwrite the max sessions to 80, which means you will eventually need 80 CPUs if you want to run 80 tests in parallel (and potentially more if video recording is enabled). Have you measured performance when running tests with Dynamic Grid which show that you can use one CPU for more than one test?

**Comment by JannisBush** [comment]
Thanks for the answer. I just used 80 as an example here and solved my scaling problem by giving docker access to more CPUs. Documenting somewhere that this parameter does not work for dynamic grid, or allowing the overwrite if the user really wants it, would probably be helpful for  future users.

However, I also had the problem that I could not specify other settings (e.g., `SE_NODE_SESSION_TIMEOUT`) for the nodes in the dynamic grid. Which seems related to this bug (if this is unrelated I can open a new bug report and this one can be closed?).

**Comment by diemol** [comment]
Right, I understand there are a set of settings like `SE_NODE_SESSION_TIMEOUT` one would like to pass to the dynamic containers being created. 

I will leave this open so we can have a look when the bugs blocking RC1 are cleared out.

**Comment by arvinder06** [comment]
Any updates on this?

**Comment by diemol** [comment]
No updates. Happy to receive contributions, though :)

**Comment by jaraiza-impinj** [comment]
@JannisBush  One workaround (in the meantime) that worked for me is to provide the environment variable `SE_OPTS` and use CLI options documented [here](https://www.selenium.dev/documentation/grid/configuration/cli_options/). Here is a snippet of my `docker-compose.yml`:

```
 node-docker:
    image: selenium/node-docker:4.1.2-20220208
    volumes:
      - ./config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_OPTS=--override-max-sessions true --max-sessions 6 --session-timeout 7200

  selenium-hub:
    image: selenium/hub:4.1.2-20220208
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```
So with this workaround I can configure session timeout, override max sessions, and set max sessions using dynamic grid. 😃
