### ISSUE TITLE
"Failed to save session capabilities", Video saved but the session information is not saved in Dynamic Grid

### ISSUE THREAD

**Issue by rezaakv** [SeleniumHQ/docker-selenium#1320]
## 🐛 Bug Report

Hello, First of all thank you so much for creating this amazing project! 

The session info, `se:options`, for my test executions are not saved in the directory next to the video. 
There is only the folder created with random name such as "00ba4fa78cd37e07bc96333616d39cef" and the video.mp4 file is inside it. No information about which test this was or any other session info is saved which I believe it should be. 

This is the error that appears in the docker logs whenever a test is run:

```
node-docker_1   | 03:57:33.669 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
node-docker_1   | 03:57:33.680 WARN [DockerSessionFactory.saveSessionCapabilities] - Failed to save session capabilities
node-docker_1   | java.nio.file.AccessDeniedException: /myselenium
node-docker_1   | 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
node-docker_1   | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
node-docker_1   | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
node-docker_1   | 	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
node-docker_1   | 	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
node-docker_1   | 	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
node-docker_1   | 	at java.base/java.nio.file.Files.createDirectories(Files.java:783)
node-docker_1   | 	at org.openqa.selenium.grid.docker.DockerSessionFactory.saveSessionCapabilities(DockerSessionFactory.java:376)
node-docker_1   | 	at org.openqa.selenium.grid.docker.DockerSessionFactory.apply(DockerSessionFactory.java:221)
node-docker_1   | 	at org.openqa.selenium.grid.docker.DockerSessionFactory.apply(DockerSessionFactory.java:85)
node-docker_1   | 	at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:143)
node-docker_1   | 	at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:325)
node-docker_1   | 	at org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:52)
node-docker_1   | 	at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
node-docker_1   | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
node-docker_1   | 	at org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0(RequiresSecretFilter.java:64)
node-docker_1   | 	at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
node-docker_1   | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
node-docker_1   | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
node-docker_1   | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
node-docker_1   | 	at org.openqa.selenium.grid.node.Node.execute(Node.java:240)
node-docker_1   | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
node-docker_1   | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
node-docker_1   | 	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
node-docker_1   | 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
node-docker_1   | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
node-docker_1   | 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
node-docker_1   | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
node-docker_1   | 	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
node-docker_1   | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
node-docker_1   | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
node-docker_1   | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
node-docker_1   | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
node-docker_1   | 	at java.base/java.lang.Thread.run(Thread.java:829)

```

## To Reproduce

The docker-compose.yml I am using for the dynamic grid is the following: 
```
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.0.0-beta-4-prerelease-20210604
    volumes:
      - /myselenium/assets:/opt/selenium/assets
      - /cloud/home/reza/seleniumtestsproj/config.toml:/opt/bin/config.toml
    network_mode: "host"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=127.0.0.1
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

    privileged: true
  selenium-hub:
    image: selenium/hub:4.0.0-beta-4-prerelease-20210604
    privileged: true
    network_mode: "host"
```
And the config.toml is:
```
[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-chrome:4.0.0-beta-4-prerelease-20210604", "{\"browserName\": \"chrome\"}"
    ]

# URL for connecting to the docker daemon
# host.docker.internal works for macOS and Windows.
# Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
# To have Docker listening through tcp on macOS, install socat and run the following command
# socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
url = "http://127.0.0.1:2375"
# Docker imagee used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20210604"
assets-path = "/myselenium/assets"
container-assets-path = "/opt/selenium/assets"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
#[server]
#host = <ip-from-node-machine>
#port = <port-from-node-machine>
```

One thing of note: When I didn't have `assets-path = "/myselenium/assets"` in my `config.toml`, the directories and the videos weren't getting created. When I added it, the videos started to appear, but no session info still. 
I have tried setting permissions of `/myselenium` to 777 and added `privileged: true` to my docker-compose.yml but still the same exception is thrown. 

## Expected behavior

The session info should be saved alongside video and the exception for saving session capabilities shouldn't have been thrown. 

## Test script reproducing this issue (when applicable)

The related parts I added in python project code: 

```python
def new_driver():
        ...
        config = DesiredCapabilities.CHROME
        config["se:options"] = {
            "name": "mytest",
            "browserName": "chrome",
            "platformName": "linux",
            "se:recordVideo": True,
            "se:timeZone": "US/Pacific",
            "se:screenResolution": "1920x1080"
        }
        config["browserName"] = "chrome"
        config["se:recordVideo"] = True
        config["se:timeZone"] = "US/Pacific"
        config["se:screenResolution"] = "1920x1080"
        ...
        return webdriver.Remote(command_executor=os.environ.get('SLENIUM_HUB_ADDRESS'), desired_capabilities=config, options=options)
        

```

## Environment

OS: Ubuntu 20.04.02
Docker-Selenium image version: 4.0.0-beta-4-prerelease-20210604
Also provide the docker image id 
```
selenium/video               ffmpeg-4.3.1-20210604              08f6e8c752cc   2 weeks ago    296MB
selenium/node-docker         4.0.0-beta-4-prerelease-20210604   8ce727798674   2 weeks ago    364MB
selenium/hub                 4.0.0-beta-4-prerelease-20210604   4d1dd33d11b0   2 weeks ago    364MB
```
-->
Docker version:  `Docker version 20.10.6, build 370c289`
Docker-Compose version (if applicable): `docker-compose version 1.29.1, build c34c88b2`
Exact Docker command to start the containers: `sudo docker-compose up`

**Comment by diemol** [comment]
This should be enough for the `config.toml`

```toml
[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-chrome:4.0.0-beta-4-prerelease-20210604", "{\"browserName\": \"chrome\"}"
    ]

# URL for connecting to the docker daemon
# host.docker.internal works for macOS and Windows.
# Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
# To have Docker listening through tcp on macOS, install socat and run the following command
# socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
url = "http://127.0.0.1:2375"
# Docker imagee used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20210604"
```

If you are running into permissions error, perhaps create the directory in advance before starting the containers.
