### ISSUE TITLE
Dynamic Grid video timeout, add record options. http://gridhub:4444/session timed out after 60 seconds.'

### ISSUE THREAD

**Issue by namilkimfree** [SeleniumHQ/docker-selenium#1325]
## 🐛 Bug Report

[1625465509.749][SEVERE]: bind() failed: Cannot assign requested address (99)

Add option record option (se:*)  and connect remote hub ( url:4444) 
then throw timeout.

but don't add record options , success.

## To Reproduce

1. start dynamic grid docker-compose: https://github.com/SeleniumHQ/docker-selenium#configuration-example
2. add record video option
3. connect docker dynamic hub
4. throw timeout exception

Detailed steps to reproduce the behavior:

1. start dynamic grid docker-compose: https://github.com/SeleniumHQ/docker-selenium#configuration-example
2. drvier add options
3. driverOptions.AddAdditionalOption("se:recordVideo", true); 
4. driverOptions.AddAdditionalOption("se:timeZone", "US/Pacific");
5. driverOptions.AddAdditionalOption("se:screenResolution", "1920x1080");
6. connect remote webdriver
7. driver = new RemoteWebDriver(new Uri("http://dockerUrl"), driverOptions);

Steps to reproduce the behavior (including the command to start the containers):

## Expected behavior
https://github.com/namilkimfree/SeleniumDynamicissueTest

don't throw timeout exception, 
 (OpenQA.Selenium.WebDriverException: 'The HTTP request to the remote WebDriver server for URL http://gridhub:4444/session timed out after 60 seconds.'

## Test script reproducing this issue (when applicable)

```

private IWebDriver GetChromeDriver()
{
      var driverOptions = new ChromeOptions();

      driverOptions.AddAdditionalOption("se:recordVideo", true);
      driverOptions.AddAdditionalOption("se:timeZone", "US/Pacific");
      driverOptions.AddAdditionalOption("se:screenResolution", "1920x1080");

      var driver = new RemoteWebDriver(new Uri("http://172.27.6.37:4444"), driverOptions)
      {
      };

      return driver;
  }

```
```

private void Test()
{

      var driver = GetChromeDriver();    -> throw timeout 
      driver.Navigate().GoToUrl("anything url");

  }

```

```
*[dynamic grid docker.yml]

version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.0.0-rc-1-prerelease-20210618
    volumes:
      - ./assets:/opt/selenium/assets
      - ./NodeDocker/config.toml:/opt/bin/config.toml
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.0.0-rc-1-prerelease-20210618
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

```

*[confing.toml]

[docker]

configs = [
    "selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618", "{\"browserName\": \"chrome\"}"
    ]
url = "http://host.docker.internal:2375"
video-image = "selenium/video:ffmpeg-4.3.1-20210426"

```

## Environment

OS: Windows 10 
Docker-Selenium image version:  https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-dynamic-grid.yml 
Also provide the docker image id 
-->
Docker version:  Docker version 20.10.7, build f0df350
Docker-Compose version (if applicable): docker-compose version 1.29.2, build 5becea4c
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): docker-compose -f .\docker-compose-v3-dynamic-grid.yml up -d
in powersehll
