### ISSUE TITLE
Always report socket hang up when I start a new session to run E2E test.

### ISSUE THREAD

**Issue by Siyu-TW** [SeleniumHQ/docker-selenium#1352]
## 🐛 Bug Report

I always meet socket hang up when I run E2E test in docker using below docker-compose file.
![image](https://user-images.githubusercontent.com/58452439/127817062-b5ced984-7bee-4e22-810f-799ea9f2060a.png)

## To Reproduce

run `docker-compose run \
  node-with-hub  nightwatch
exitCode=$?
docker-compose down
exit $exitCode`

## Expected behavior

I want to have a stable environment to run my e2e test.

## Test script reproducing this issue (when applicable)

`docker-compose run \
  node-with-hub nightwatch
exitCode=$?
docker-compose down
exit $exitCode`

```
version: '2.3'
  services:
      chrome:
          image: selenium/node-chrome:latest
          volumes:
              - /dev/shm:/dev/shm
          depends_on:
              - hub
          environment:
              HUB_HOST: hub
  
      hub:
          image: selenium/hub:latest
          ports:
              - '4444:4444'
  
      node:
          build:
            context: etc
            dockerfile: Dockerfile.node
            args:
              IMAGE_VERSION: 13.6.0-alpine3.10
          volumes:
              - .:/t
          working_dir: /t
  
      node-with-hub:
          extends: node
          entrypoint: wait-for hub:4444 --timeout=60 --
          depends_on:
            - firefox
            - chrome
            - hub
```

## Environment

OS: 
Docker-Selenium image version: 
Docker version: 20.10.7
Docker-Compose version (if applicable):1.29.2
Nightwatch version: 1.6.3
