### ISSUE TITLE
is it valid dynamic video selenium  yaml file of kubernetes? 

### ISSUE THREAD

**Issue by namilkimfree** [SeleniumHQ/docker-selenium#1355]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

Can I write this and run it?

I wish I had a kubernetes dynamic video .yaml file.

this is selenium-daynamic.yaml  file

```

#***************************************
#SELENIUM-HUB
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    name: selenium-hub
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-hub
  ports:
    - name: port1
      protocol: TCP
      port: 4442
      targetPort: 4442
    - name: port2
      protocol: TCP
      port: 4443
      targetPort: 4443
    - name: port3
      protocol: TCP
      port: 4444
      targetPort: 4444

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub-deployment
  labels:
    app: selenium-hub
    name: selenium-hub
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
        name: selenium-hub
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:4.0.0-rc-1-prerelease-20210618
          ports:
            - containerPort: 4442
              protocol: TCP
            - containerPort: 4443
              protocol: TCP
            - containerPort: 4444
              protocol: TCP
      nodeSelector:
        setype: hub
      imagePullSecrets:
      - name: harbor-secret
---
#***************************************
#SELENIUM NODE DOCKER
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-sessions
  labels:
    name: selenium-sessions
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-sessions

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-sessions-deployment
  labels:
    app: selenium-sessions
    name: selenium-sessions
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-node-docker
  template:
    metadata:
      labels:
        app: selenium-node-docker
        name: selenium-node-docker
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-node-docker
          image: selenium/node-docker:4.0.0-rc-1-prerelease-20210618
          env:
            - name: LANGUAGE
              value: ko
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
      nodeSelector:
        setype: hub
      imagePullSecrets:
      - name: harbor-secret
      volumeMounts:
      - name: asset
          mountPath: /opt/selenium/assets
      - name: config
          mountPath: /opt/bin
      volumes:
        - name: asset
          emptyDir: {  }
        - name: config
          emptyDir: {  }
---

```

this is config.toml  file

```
[docker]
configs = [
 "selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618", "{\"browserName\": \"chrome\"}"
    ]

video-image = "selenium/video:ffmpeg-4.3.1-20210618"

[server]
host = 192.168.1.24   (is valid ?)
port = 2376 (is valid ?)
```
