### ISSUE TITLE
Missing tags selenium/<image-name>:4 in Docker Hub

### ISSUE THREAD

**Issue by fkrivsky** [SeleniumHQ/docker-selenium#1365]
## 🐛 Bug Report

We used the tag selenium/hub:4 (and nodes as well) to keep up with the latest release of grid 4.
However, recently the :4 tags disappeared from Docker Hub.
We discovered it when we had a failure after redeploying pre-existing yamls.
Is this intentional please? 

It's breaking our workflow in a couple of aspects:
1. [Diun](https://crazymax.dev/diun/) no longer notifies about image update
2. We cannot simply redeploy existing yamls which was easy and smooth.

## To Reproduce

Try to deploy docker image using previously working tag :4

## Expected behavior

Having :4 tag in Docker Hub that would denote latest image of version 4.x

## Environment

OS: CentOS, Docker Swarm and K3s Kubernetes
Docker version: 20.10.8
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
- Compose example:
```
version: '3.7'
services:
 selenium-hub:
    image: selenium/hub:4
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      TZ: "America/New_York"
    deploy:
      labels:
        - "diun.enable=true"
      placement:
        constraints:
         - node.labels.grid == true

 chrome:
    image: selenium/node-chrome:4
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - TZ=America/New_York
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_HEIGHT=1080
      - SCREEN_WIDTH=1920
      - SCREEN_DEPTH=24
    deploy:
      labels:
        - "diun.enable=true"
      replicas: 40
      placement:
        constraints:
         - node.labels.grid == true
      resources:
        limits:
          cpus: '1.0'
          memory: 800M
        reservations:
          # cpus: '0.25'
          memory: 100M
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'
```
- k8s manifest:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
      annotations:
        diun.enable: "true"
        diun.watch_repo: "false"
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:4
          imagePullPolicy: Always
          ports:
            - containerPort: 4444
              protocol: TCP
            - containerPort: 4443
              protocol: TCP
            - containerPort: 4442
              protocol: TCP
          env:
            - name: TZ
              value: "America/New_York"
          resources:
            limits:
              memory: "1000Mi"
              cpu: ".5"
          livenessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 30
            timeoutSeconds: 5
---
# Hub Service - expose via NodePort
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-hub
  ports:
    - port: 4442
      targetPort: 4442
      nodePort: 32442
      protocol: TCP
      name: event-bus-publish-port
    - port: 4443
      targetPort: 4443
      nodePort: 32443
      protocol: TCP
      name: event-bus-subscribe-port
    - port: 4444
      targetPort: 4444
      nodePort: 32444
      protocol: TCP
      name: grid-webui-port
  type: NodePort
  sessionAffinity: None
---
# Chrome nodes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
  labels:
    app: selenium-node-chrome
    component: "selenium-grid-4"
spec:
  replicas: 48
  selector:
    matchLabels:
      app: selenium-node-chrome
  # nodeSelector:
  #   selenium.grid: true
  template:
    metadata:
      labels:
        app: selenium-node-chrome
      annotations:
        diun.enable: "true"
        diun.watch_repo: "false"
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: selenium-node-chrome
          image: selenium/node-chrome:4
          imagePullPolicy: Always
          ports:
            - containerPort: 5555
              protocol: TCP
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-hub"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: TZ
              value: "America/New_York"
            - name: "SCREEN_HEIGHT"
              value: "1200"
            - name: "SCREEN_WIDTH"
              value: "1920"
            - name: "SCREEN_DEPTH"
              value: "24"
          resources:
            limits:
              memory: "1000Mi"
              cpu: ".5"
```
