### ISSUE TITLE
Session is not being closed even after driver quit

### ISSUE THREAD

**Issue by basiljose1** [SeleniumHQ/docker-selenium#1407]
## 🐛 Bug Report

Node session persists even after `driver.quit()`, Log shows the DELETE requests for the session. but still, the session exists in the hub.
This issue occurs sometimes only but most commonly.

is there any way to cleanup these orphan sessions/ is there any cleanup ??
```
2021-09-27 08:02:50 [selenium.webdriver.remote.remote_connection] DEBUG: DELETE http://selenium-hub:4444/wd/hub/session/d7523dc7992ca847a0b5044cf2e30607 {}
2021-09-27 08:02:50 [urllib3.connectionpool] DEBUG: http://selenium-hub:4444 "DELETE /wd/hub/session/d7523dc7992ca847a0b5044cf2e30607 HTTP/1.1" 200 14
2021-09-27 08:02:50 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
```

## Environment

OS: Linux host.xyz.com 5.4.0-72-generic #80-Ubuntu
Docker-Selenium image version: 4.0.0-rc-2-prerelease-20210916
Docker version: Docker version 20.10.8, build 3967b7d
Docker-Compose version (if applicable): docker-compose version 1.29.2, build 5becea4c
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): [docker-compose-v3.yml](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3.yml)

**Comment by diemol** [comment]
I can have a look if you provide a way to reproduce it. While you provide that, you can also share the Grid logs.

**Comment by hibissscus** [comment]
Same for me, for a long e2e run for more than 2h, after several failed test (but `driver quit` was called after each failed), sessions are still occupied and next tests can not be run due to all sessions are occupied. 
Docker-Selenium image version: `4.0.0-rc-2-prerelease-20210923` same things works well on `4.0.0-beta-3-20210426`

docker-compose.yml 
```
version: "3.9"
services:
  e2e:
    container_name: e2e
    image: gradle:7.0.2-jdk8
    working_dir: /code
    volumes:
      - ./:/code
      - downloads:/code/downloads
    depends_on:
      - selenium-hub
      - chrome1
      - chrome2
      - chrome3
      - chrome4
      - chrome5
      - chrome6
      - chrome7
      - chrome8
      - chrome9
      - chrome10
      - chrome11
      - chrome12
      - chrome13
      - chrome14
    command: "gradle e2e -De2e.selenium=http://selenium-hub:4444"
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:4.0.0-rc-2-prerelease-20210923
    ports:
      - "4444:4444"
      - "4443:4443"
      - "4442:4442"
    environment:
      - TZ=Europe/Berlin
  chrome1:
    container_name: chrome1
    image: selenium/node-chrome:4.0.0-rc-2-prerelease-20210923
    shm_size: 512m
    volumes:
      - downloads:/home/seluser/
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - TZ=Europe/Berlin
    ports:
      - "6901:5900"
  chrome2:
    container_name: chrome2
    image: selenium/node-chrome:4.0.0-rc-2-prerelease-20210923
    shm_size: 512m
    volumes:
      - downloads:/home/seluser/
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - TZ=Europe/Berlin
    ports:
      - "6902:5900"
#....................................................................................
  chrome14:
    container_name: chrome14
    image: selenium/node-chrome:4.0.0-rc-2-prerelease-20210923
    shm_size: 512m
    volumes:
      - downloads:/home/seluser/
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - TZ=Europe/Berlin
    ports:
      - "6914:5900"
volumes:
  downloads:
```
