### ISSUE TITLE
[🐛 Bug]: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/docker-selenium#1478]
### What happened?

I'm getting the following error:

```
[2022-01-08T23:53:02.179Z] Executed 'MyFunction' (Failed, Id=3acab863-d9d9-40a0-ba12-fae6d8a81aa0, Duration=50085ms)
[2022-01-08T23:53:02.180Z] System.Private.CoreLib: Exception while executing function: WordsStartingWithA. WebDriver: An unknown exception was encountered sending an HTTP request to the remote WebDriver server for URL http://xxxxx:4444/session/65092ede-c27f-42a0-8fe2-164a778a23a0/execute/sync. The exception message was: An error occurred while sending the request. System.Net.Http: An error occurred while sending the request. System.Net.Sockets: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. An existing connection was forcibly closed by the remote host.
```

I'm using Kubernetes on Azure.

This is my C# code:

```
var browserOptions = new FirefoxOptions();
var CloudURL = "http://xxxxx:4444/";
var driver = new RemoteWebDriver(new Uri(CloudURL), browserOptions);
var url = $"https://www.somewebsite.com/";
driver.Navigate().GoToUrl(url);
var stuff = driver.FindElementsByCssSelector(CssSelectorPath);
driver.Quit();
```

My Kubernetes deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
spec:
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:4.1.1-20211217
        ports:
          - containerPort: 4444
          - containerPort: 4442
          - containerPort: 4443
          - containerPort: 7900
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet: 
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
```

My Kubernetes service:
```
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
  - name: selenium-hub
    port: 4444
  - name: subscribe
    port: 4443
  - name: publish
    port: 4442
  - name: view
    port: 7900
    targetPort: 7900
  type: LoadBalancer
```

My Kubernetes replica:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-hub
spec:
  replicas: 5
  selector:
    app: selenium-firefox
  template:
    metadata:
      name: selenium-firefox
      labels:
        app: selenium-firefox
    spec:
      containers:
        - name: node-firefox
          image: selenium/node-firefox:95.0-20211217
          ports:
            - containerPort: 5555
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-hub"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
```

### Command used to start Selenium Grid with Docker

```shell
See under "what happened" as it's Kubernetes yaml
```

### Relevant log output

```shell
[2022-01-08T23:53:02.180Z] System.Private.CoreLib: Exception while executing function: WordsStartingWithA. WebDriver: An unknown exception was encountered sending an HTTP request to the remote WebDriver server for URL http://xxxxxx:4444/session/65092ede-c27f-42a0-8fe2-164a778a23a0/execute/sync. The exception message was: An error occurred while sending the request. System.Net.Http: An error occurred while sending the request. System.Net.Sockets: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. An existing connection was forcibly closed by the remote host.
```

### Operating System

Linux

### Docker Selenium version (tag)

See Kubernetes yaml for tags
