### ISSUE TITLE
[🐛 Bug]: Custom Config.toml gets overwritten by generate_config

### ISSUE THREAD

**Issue by MissakaI** [SeleniumHQ/docker-selenium#1481]
### What happened?

I want to add some additional options using the config.toml which I am mounting using the command given below to `/opt/bin/config.toml`. But the problem is it gets overwritten by the following

https://github.com/SeleniumHQ/docker-selenium/blob/a360ce5827203f8b17eb0c052a15dc5d28eca233/NodeBase/generate_config#L16-L19

Then again i noticed that if I set the env variable `GENERATE_CONFIG=false` then it will not generate the default config file.

https://github.com/SeleniumHQ/docker-selenium/blob/a360ce5827203f8b17eb0c052a15dc5d28eca233/NodeBase/start-selenium-node.sh#L34-L37

I don't won't my config.toml to be interfered with the generated config. I want to let the generated values stay the same while i am able to mount any additional configs.

For example

```toml
#Generated Values
[events]
publish = "tcp://selenium-hub:4442"
subscribe = "tcp://selenium-hub:4443"

[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

[[node.driver-configuration]]
display-name = "firefox"
stereotype = '{"browserName": "firefox", "browserVersion": "95.0", "platformName": "Linux"}'
max-sessions = 1

#My Custom Values
[node]
heartbeat-period = 30
```

But my suggested change would be to have pass a additional config.toml to Selenium during startup so both generated and user's custom config can be passed on which allows the file to be mounted read-only as i intend to mount the same config to all firefox, chrome and edge and don't want it to be written with browser specific configs during generate_config.

### Command used to start Selenium Grid with Docker

```shell
docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -v /run/desktop/mnt/host/d/<rest_of_the_path>/node-config.toml:/opt/bin/config.toml \
    -v /run/desktop/mnt/host/d/<rest_of_the_path>/assets:/opt/selenium/assets \
    selenium/node-firefox:4.1.1-20211217
```

### Relevant log output

```shell
...
2022-01-20 20:01:04,502 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-01-20 20:01:04,503 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Generating Selenium Config
Configuring server...
Setting up SE_NODE_HOST...
Setting up SE_NODE_PORT...
Setting up SE_NODE_GRID_URL...
Selenium Grid Node configuration:
[events]
publish = "tcp://selenium-hub:4442"
subscribe = "tcp://selenium-hub:4443"

[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

[[node.driver-configuration]]
display-name = "firefox"
stereotype = '{"browserName": "firefox", "browserVersion": "95.0", "platformName": "Linux"}'
max-sessions = 1

Starting Selenium Grid Node...
20:01:24.004 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
...
```

### Operating System

Windows 10

### Docker Selenium version (tag)

4.1.1-20211217
