### ISSUE TITLE
[🐛 Bug]: selenium parallel testing doesnt work on M1-based macs

### ISSUE THREAD

**Issue by xsoft7** [SeleniumHQ/docker-selenium#1522]
### What happened?

I've switched to new mac (14" m1-pro). 
i've udpated the docker-compose with latest images:
```

`  chromeService:
    image: seleniarm/node-chromium:4.1.2-20220227
    shm_size: 4gb
    volumes:
      - /dev/shm:/dev/shm
      - ../downloads:/home/seluser/Downloads/
    environment:
      - SE_EVENT_BUS_HOST=hubService
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=3
      - SE_NODE_MAX_SESSIONS=6
    ports:
      - "5900"
      - "7900"
    deploy:
      replicas: 4
    depends_on:
      - hubService
    env_file: ./.env

    networks: [ 'selenium-grid-ui-tests' ]

  hubService:
    image: seleniarm/hub:4.1.2-20220227
    container_name: seleniumHub
    ports:
      - "4445:4444"
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

    networks: [ 'selenium-grid-ui-tests' ]


networks: { selenium-grid-ui-tests: { } }`

```

everything works fine, when running single-threaded.

i run with extra params: `-n=4 --dist loadscope`

whenver` n=1` it works fine. whenver `n>1` it crashes.

**I used the same docker-compose on my old intel-base mac . it works fine with seleniarm, **AND n>1****

*using latest python 3.10.2

### Command used to start Selenium Grid with Docker

```shell
docker compose up chromeService
```

### Relevant log output

```shell
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
E       from unknown error: cannot determine loading status
E       from tab crashed
E         (Session info: chrome=98.0.4758.102)
E       Stacktrace:
E       #0 0xaaaab594fce0 <unknown>
E       #1 0xaaaab56c489c <unknown>
E       #2 0xaaaab56b2b50 <unknown>
E       #3 0xaaaab56b259c <unknown>
E       #4 0xaaaab56b1aac <unknown>
E       #5 0xaaaab56b0ca8 <unknown>
E       #6 0xaaaab56b11a8 <unknown>
E       #7 0xaaaab56bcf04 <unknown>
E       #8 0xaaaab56cb350 <unknown>
E       #9 0xaaaab56b14f0 <unknown>
E       #10 0xaaaab56cb05c <unknown>
E       #11 0xaaaab5722cf4 <unknown>
E       #12 0xaaaab56e9164 <unknown>
E       #13 0xaaaab56ea3f8 <unknown>
E       #14 0xaaaab597abc8 <unknown>
E       #15 0xaaaab598b178 <unknown>
E       #16 0xaaaab598af14 <unknown>
E       #17 0xaaaab597c10c <unknown>
E       #18 0xaaaab598b790 <unknown>
E       #19 0xaaaab5971110 <unknown>
E       #20 0xaaaab59a1544 <unknown>
E       #21 0xaaaab59a16fc <unknown>
E       #22 0xaaaab59ba480 <unknown>
E       #23 0xffff9c79bf3c <unknown>
E       #24 0xffff9bd7bcdc <unknown>

../../../../../../venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:247: WebDriverException
```

### Operating System

macos 12.2.1

### Docker Selenium version (tag)

4.1.2-20220227
