### ISSUE TITLE
[🚀 Feature]: Hide cursor in recording

### ISSUE THREAD

**Issue by andreas-mausch** [SeleniumHQ/docker-selenium#1524]
### Feature and motivation

I use selenium/standalone-chrome-debug:3.141.59 via [testcontainers](https://www.testcontainers.org/modules/webdriver_containers/)

The test recording works great, however there is a cursor in the middle in the screen I find intrusive.
It doesn't even move when I call `moveByOffset` or `moveToElement`.
Selenium controls are handled correctly though.

Is there a way to hide the cursor?

![mpv-shot0001](https://user-images.githubusercontent.com/1736847/157868498-2a5468dd-ab86-4cd0-8c65-d6873c9ee351.jpg)

### Usage example

I would use the feature in recordings of tests, which would look much cleaner without the cursor.

**Comment by andreas-mausch** [comment]
Oh, I found this is more likely an issue for https://github.com/testcontainers/testcontainers-java:
https://superuser.com/questions/1194076/xvfb-with-nocursor-shows-cursor-anyway

They use `vnc2flv` and it offers a flag to hide the cursor:
https://github.com/baijum/vnc2flv/blob/015ab7f21ca446c4d942949659cfc387bed779e7/tools/flvrec.py#L105

**Comment by datosh** [comment]
I think it should also be configurable via Selenium containers. As your linked Stackoverflow discussion shows you need to provide the correct parameters to `ffmpeg` command to hide the cursor. I have hijacked the frame rate variable to achieve this:

```yaml
  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20221104
    volumes:
      - /tmp/videos:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4
      - SE_FRAME_RATE=30 -draw_mouse 0 # <<<
```

[Which is passed down to the correct location](https://github.com/SeleniumHQ/docker-selenium/blob/ad2f7482d62fce45eef7a6340507d6589418ce64/Video/video.sh#L26).

Any chance we could provide a more general `SE_FFMPEG_ADDITIONAL_PARAMETERS` environment variable to support `ffmpeg` configuration?

Could we re-open this issue?
