### ISSUE TITLE
[🚀 Feature]: Add Ingress resource(s) and don't use NodePort as a default in Helm chart

### ISSUE THREAD

**Issue by jkirkham-ratehub** [SeleniumHQ/docker-selenium#1546]
### Feature and motivation

Unless you are running kubernetes on bare-metal or similar (like minikube) NodePort services should be avoided.  NodePort services can present some management issues (e.g. node-pool auto-scaling will regularly add and remove IP addresses) and security issues in many scenarios.

The preferred approach is to consistently use ClusterIP services with an Ingress resource routing to the service(s) that need to be exposed.  Alternatively, a LoadBalancer service will behave similarly.

For users who do not have access or ability to create and expose Ingress or LoadBalancer services, the NodePort option should be available, but it should not be the default.

### Usage example

In either case of `isolateComponents` set to true or false, Selenium Grid can be exposed through an Ingress resource that would point to the ClusterIP service of either the Router or the Hub.
The Ingress resource should have the option of being disabled in the Helm values.yaml (or via `--set`).

So the preferred default install would have a ClusterIP Service attached to the `Router` or `Hub` Pods (depending on the `isolateComponents` setting) and this would be exposed through an Ingress resource.
If a NodePort (or LoadBalancer) is required the Ingress should be disabled (not created by the Helm chart).  This should be clearly communicated in the docs for the Helm chart.

**Comment by jkirkham-ratehub** [comment]
To add, there are work arounds.  You can set the Service type to ClusterIP via `--set` or the values file and then externally create and manage an Ingress resource.  The advantage of having it in the Helm chart is that you can ensure the attached Service name matches what is referenced in the Ingress.

**Comment by jkirkham-ratehub** [comment]
I'll see if I can get time to create a PR for this.

**Comment by getsomebread** [comment]
In case it helps, here's a semi-functional ingress with helm variable names I just made up that assume a TLS cert is present. If the existing chart's value of hub.serviceType = ClusterIP, then this works.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selenium-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.hub.ingress.uri }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: selenium-hub
            port:
              number: 4444
  tls:
  - hosts:
    - {{ .Values.hub.ingress.uri }}
    secretName: {{ .Values.hub.ingress.tls }}
```

**Comment by getsomebread** [comment]
Once you set hub.serviceType = ClusterIP, you no longer have the publish & subscribe ports available either. The existing chart just exposed them as random ports anyways, making them less usable. Here's a semi-functional service YAML to expose these with customizable ports; set by variables I just made up:
```
apiVersion: v1
kind: Service
metadata:
  name: selenium-nodeports
  namespace: {{ .Release.Namespace }}
  labels:
    app: selenium-hub
spec:
  type: NodePort
  selector:
    app: selenium-hub
  ports:
  - name: tcp-hub-pub
    nodePort: {{ Values.hub.cluster.publishPort }}
    port: 4442
    protocol: TCP
    targetPort: 4442
  - name: tcp-hub-sub
    nodePort: {{ Values.hub.cluster.subscribePort }}
    port: 4443
    protocol: TCP
    targetPort: 4443
```

**Comment by sercanacar** [comment]
Hi @getsomebread  

I'm trying to enable ingress for the grid as well. Just to clarify, you are setting serviceType to ClusterIP in values.yaml and then creating a new service with above? I see type is set to NodePort though. Guessing I've missed something

Thanks

**Comment by getsomebread** [comment]
Correct, the ingress YAML I provided only makes sense if your values.yaml (or command-line arg) sets to ClusterIP since the chart's default is NodePort, eg values.yaml
```
hub:
  serviceType: ClusterIP
```

**Comment by getsomebread** [comment]
Thanks for adding this functionality in! In case it helps anyone, here's a working TLS config I got by trial & error for the new helm chart:
```
ingress:
  hostname: myapp.example.com
  tls:
    # If multiple addresses, eg [ "url1.example.com", "url2.example.com" ]
    - hosts: [ "myapp.example.com" ]
      secretName: myapp-example-com-crt
```
