### ISSUE TITLE
[🐛 Bug]: Dynamic grid not working in Centos 7

### ISSUE THREAD

**Issue by rdaytoncvent** [SeleniumHQ/docker-selenium#1549]
### What happened?

I'm getting an error "Unable to parse: /opt/bin/config.toml" when trying to run using the dynamic grid.  I'm able to run it locally on a Mac but in our Jenkins nodes we use Centos 7.  I've tried using various combinations of mounting docker.sock / config urls but always get an error in Centos.   I have ssh'ed into a running instance and the config.toml file is present with the correct contents. 

docker-compose:

```
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.1.3-20220405
    volumes:
      - ./assets:/opt/selenium/assets
      - ./config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.1.3-20220405
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```
 

config.toml:
```
[docker]
configs = [
    "selenium/standalone-firefox:4.1.3-20220405", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:4.1.3-20220405", "{\"browserName\": \"chrome\"}",
    "selenium/standalone-edge:4.1.3-20220405", "{\"browserName\": \"MicrosoftEdge\"}"
    ]

url = "http://127.0.0.1:2375"
video-image = "selenium/video:ffmpeg-4.3.1-20220405"
```

### Command used to start Selenium Grid with Docker

```shell
sudo docker-compose up
```

### Relevant log output

```shell
node-docker_1   | 2022-04-14 18:42:42,151 INFO spawned: 'selenium-grid-docker' with pid 11
node-docker_1   | Starting Selenium Grid Node Docker...
node-docker_1   | 2022-04-14 18:42:42,157 INFO success: socat entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
node-docker_1   | 2022-04-14 18:42:42,157 INFO success: selenium-grid-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub    | 18:42:42.166 INFO [UnboundZmqEventBus.<init>] - Sockets created
node-docker_1   | java.lang.reflect.InvocationTargetException
node-docker_1   | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
node-docker_1   | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
node-docker_1   | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
node-docker_1   | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
node-docker_1   | 	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
node-docker_1   | 	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
node-docker_1   | Caused by: org.openqa.selenium.grid.config.ConfigException: Unable to parse: /opt/bin/config.toml
node-docker_1   | 	at org.openqa.selenium.grid.config.TomlConfig.from(TomlConfig.java:63)
node-docker_1   | 	at org.openqa.selenium.grid.config.Configs.from(Configs.java:40)
node-docker_1   | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
node-docker_1   | 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
node-docker_1   | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
node-docker_1   | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
node-docker_1   | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
node-docker_1   | 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
node-docker_1   | 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
node-docker_1   | 	at org.openqa.selenium.grid.config.ConfigFlags.readConfigFiles(ConfigFlags.java:73)
node-docker_1   | 	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:105)
node-docker_1   | 	at org.openqa.selenium.grid.Main.launch(Main.java:83)
node-docker_1   | 	at org.openqa.selenium.grid.Main.go(Main.java:57)
node-docker_1   | 	at org.openqa.selenium.grid.Main.main(Main.java:42)
node-docker_1   | 	... 6 more
```

### Operating System

Centos 7

### Docker Selenium version (tag)

4.1.3-20220405
