### ISSUE TITLE
[🚀 Feature]: Helm Chart hosted in Github Pages

### ISSUE THREAD

**Issue by adriangonciarz** [SeleniumHQ/docker-selenium#1563]
### Feature and motivation

Currently the chart is not hosted anywhere. It's possible to use Github Pages as a Helm Repository for this purpose. More details: 
https://helm.sh/docs/howto/chart_releaser_action/
https://harness.io/blog/devops/helm-chart-repo/

### Usage example

Users want to use Selenium Grid Helm Chart in their organization's IAC. They include it as existing Helm project dependency:
```
dependencies:
  - name: selenium-grid
    version: 0.3.0
    repository: https://seleniumhq.github.io/helm-charts
```
Where https://seleniumhq.github.io/helm-charts points to the Github Page with proper Helm Repository index.yaml
