### ISSUE TITLE
[🚀 Feature]: Max sessions for chart

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/docker-selenium#1602]
### Feature and motivation

Hello!

I use following chart https://github.com/SeleniumHQ/docker-selenium/tree/trunk/charts/selenium-grid
But I didn't find here any parameter to increase max number of concurrent sessions for each node
I have following config for now:

```
chromeNode:
  replicas: "4"
  extraEnvironmentVariables:
    - name: "SE_NODE_SESSION_TIMEOUT"
      value: "70"
    - name: "SE_NODE_MAX_SESSIONS"
      value: "4"
firefoxNode:
  replicas: "4"
  extraEnvironmentVariables:
    - name: "SE_NODE_SESSION_TIMEOUT"
      value: "70"
    - name: "SE_NODE_MAX_SESSIONS"
      value: "4"
```
In this case SE_NODE_SESSION_TIMEOUT works fine, but SE_NODE_MAX_SESSIONS not working at all
I tried different configurations and I can't find a way to set it properly

Is it expected behaviour? If so it would be great to add such configuration for chart 

<img width="1759" alt="image" src="https://user-images.githubusercontent.com/42394366/173776566-efd88f54-6b40-4392-89f1-4c1c80112482.png">

### Usage example

chromeNode:
  replicas: "4"
  extraEnvironmentVariables:
    - name: "SE_NODE_SESSION_TIMEOUT"
      value: "70"
    - name: "SE_NODE_MAX_SESSIONS"
      value: "4"
