### ISSUE TITLE
[🚀 Feature]: Helm chart - ability to specify image pull secrets

### ISSUE THREAD

**Issue by z3k-io** [SeleniumHQ/docker-selenium#1619]
### Feature and motivation

The ability to specify an image pull secret will allow using custom/caches from a corporate container registry that requires authentication.

In our environment anonymous dockerhub is not an option.

### Usage example

```
values:
  global:
    imagePullSecret: <my-secret>  #default
  chromeNode:
    imagePullSecret: <my-secret>  #override
```
