### ISSUE TITLE
[🐛 Bug]: Configuring SE_OPTS to have custom stereotypes isn't respecting the values set in the node when sessions values don't match

### ISSUE THREAD

**Issue by peter-kinzelman** [SeleniumHQ/docker-selenium#1622]
### What happened?

Per the documentation [here](https://github.com/SeleniumHQ/docker-selenium#se_opts-selenium-configuration-options) and [here](https://www.selenium.dev/documentation/grid/configuration/toml_options/#setting-custom-capabilities-for-matching-specific-nodes), i'm passing in an env var via the `spec` of a Chrome Node Deployment (set up in kubernetes) 

```
env:
  - name: SE_OPTS
    value: --driver-configuration stereotype='{"browserName":"chrome","browserVersion":"103.0","platformName":"Linux","networkname:applicationName":"node_1"}'
```

When the nodes come up, logs show 

```
Appending Selenium options: --driver-configuration stereotype='{"browserName":"chrome","browserVersion":"103.0","platformName":"Linux","networkname:applicationName":"node_1"}'
```

But the later logs show 
```
[node]
session-timeout = "10000"
override-max-sessions = true
detect-drivers = false
drain-after-session-count = 0
max-sessions = 2

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "103.0", "platformName": "Linux"}'
max-sessions = 2
```

When I run a new session request to the Hub with the following capability set: 
``` 
self.options.set_capability(name="networkname:applicationName", value="node_2")
```

This session gets put on `node_1`

### Command used to start Selenium Grid with Docker

```shell
helm install selenium-grid . -n selenium-grid

https://github.com/pedrodotmc/docker-selenium/tree/selenium-grid-helm-chart-0.2.0/chart/selenium-grid
```

### Relevant log output

```shell
See above log output
```

### Operating System

linux

### Docker Selenium version (tag)

4.3.0

**Comment by diemol** [comment]
This is one of those corner cases where the default automatically generated configuration is not enough. In this case you could provide your own `config.toml`, mount it and set the env var `GENERATE_CONFIG false`. Another option would be to send a PR to change the logic and allow adding capabilities to be appended to the default configuration.

**Comment by peter-kinzelman** [comment]
Where does that `config.toml` need to live to be read by the node?

**Comment by diemol** [comment]
https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeBase/Dockerfile.txt#L172

**Comment by peter-kinzelman** [comment]
Confirming that the workaround you described above works @diemol. 

For those that come across this later, working with the Helm chart: 
- however you pass in env vars to the Chrome Node deployment, set `GENERATE_CONFIG: false`
- Inside, `templates` create a `configmap.yaml`
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.customNodeConfigMap.name }}
data:
  config.toml: |-
{{ .Files.Get "configs/custom-config.toml" | printf "%s" | indent 4}}
```

Out on chart's `values.yaml`, create a block with an arbitrary name: 
```
customNodeConfigMap:
  name: selenium-custom-node-balancer
```
In `chrome-node-deployment.yaml`, in `volumeMounts`: 
```
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: custom-config
              mountPath: /opt/selenium/config.toml
              subPath: config.toml
```

Then down in `volumes`: 
```
      volumes:
        - name: dshm
          emptyDir: { "medium": "Memory" }
        - name: custom-config
          configMap:
            name: {{ .Values.customNodeConfigMap.name }}
```

Then in that `custom-config.toml` that's in another directory: 
```
[events]
publish = "tcp://selenium-hub:4442"
subscribe = "tcp://selenium-hub:4443"
[node]
session-timeout = "10000"
override-max-sessions = true
detect-drivers = false
drain-after-session-count = 2
max-sessions = 2
[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "102.0", "platformName": "Linux", "networkname:applicationName":"node_1", "nodename:applicationName":"app_1" }'
```

That's all boilerplate except for the `"networkname:applicationName":"node_1", "nodename:applicationName":"app_1" `, and also doesn't have to be both. Can be arbitrary values I thinK?
