### ISSUE TITLE
[🐛 Bug]: Even though the hub and one node is running the ingress gives the error `response 404 (backend NotFound), service rules for the path non-existent`

### ISSUE THREAD

**Issue by rakeshnambiar** [SeleniumHQ/docker-selenium#1718]
### What happened?

I am running on GCP free tier account. Due to the quota limit, all the nodes are not running. However, the hub and chrome POD is in running status. But when I access the ingress URL I am getting the error response 404 (backend NotFound), service rules for the path non-existent` in the UI. I also tried `http://<my-external-ip>/wd/hub`

I also observed, when I excluded the Edge node to save some space it's ignored. I tried with the custom values.yaml like `helm install -name selenium-grid-new -f selenium-grid-values.yaml docker-selenium/selenium-grid`

### Command used to start Selenium Grid with Docker

```shell
helm install selenium-grid docker-selenium/selenium-grid
```

### Relevant log output

```shell
I can see the service and ingress mapping is correct and it's pointed to port 4444
```

### Operating System

Linux

### Docker Selenium version (tag)

latest

**Comment by diemol** [comment]
This error does not come from the Grid `response 404 (backend NotFound),`, not sure where it comes from. Have you tried to deploy locally?

**Comment by rakeshnambiar** [comment]
@diemol thanks for your reply. Unfortunately, I don't have any local environment to try it. Btw - to override the default values I hope I should use the command `helm install -name selenium-grid-new -f selenium-grid-values.yaml docker-selenium/selenium-grid` please confirm.

**Comment by rakeshnambiar** [comment]
@diemol I recreated the cluster with fewer nodes and this time all 4 PODs are running. However, the ingress is not working as expected and getting the same error.

**Comment by rakeshnambiar** [comment]
As per the K8s documentation, this error will appear if the default backend is not defined in the ingress:
https://cloud.google.com/kubernetes-engine/docs/concepts/ingress

I solved it by manually creating the ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sel-ingress-new
spec:
  defaultBackend:
    service:
      name: selenium-hub
      port:
        number: 4444
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: selenium-hub
            port:
              number: 4444
```
