### ISSUE TITLE
[🚀 Feature]: Add Node Affinity to Helm chart Selenium

### ISSUE THREAD

**Issue by yasha-dev1** [SeleniumHQ/docker-selenium#1763]
### Feature and motivation

There is a need to create Affinity for all the nodes which are deployed in selenium helm chart. currently there is no Affinity in default values of the helm chart. It would be a really good feature to add that. a Common pattern is to add it to `global.affinity`. there are some helm charts which already do that already

### Usage example

```
global:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: lke.linode.com/pool-id
                operator: In
                values:
                  - "<POOL_ID>"
```
