### ISSUE TITLE
[🚀 Feature]: Separate Video Recording for Parallel Browsers Tests within Docker Container

### ISSUE THREAD

**Issue by itkhanz** [SeleniumHQ/docker-selenium#1764]
### What happened?

Hi, I am running cross browser tests in Parallel using Docker Selenium Grid. I am running 3 tests in parallel on each of the node i.e. 3 chrome browser instances will open in the docker node-chrome container. Similarly for the FireFox and Edge, 3 browsers will run the tests in parallel in each of the containers.

The issue I am facing is that I need to record separate video for each of the browser instance in the Docker container. But At the moment I am getting just one video recording per docker container (Selenium Node) and because of this issue, in the recorded video the execution for 1 browser is playing while the execution for remaining browsers is running in the background and i cannot visualize the executions in other browsers.

I have added separate video image per each node container and I am getting 3 recorded videos. But I want to get 9 recorded videos as in each of 3 containers, 2 browser instances are running in parallel.Here is my docker-compose.yml file. 

```
# To execute this docker-compose yml file use `docker-compose -f docker-compose-.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose.yml down`
version: "3"
services:
  chrome:
    image: selenium/node-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=3
      - SE_NODE_MAX_SESSIONS=3
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "5900"
      - "7900"


  edge:
    image: selenium/node-edge
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=3
      - SE_NODE_MAX_SESSIONS=3
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "5900"
      - "7900"

  firefox:
    image: selenium/node-firefox
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=3
      - SE_NODE_MAX_SESSIONS=3
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "5900"
      - "7900"

  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20221219
    volumes:
      - ./test-recordings:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4

  edge_video:
    image: selenium/video:ffmpeg-4.3.1-20221219
    volumes:
      - ./test-recordings:/videos
    depends_on:
      - edge
    environment:
      - DISPLAY_CONTAINER_NAME=edge
      - FILE_NAME=edge_video.mp4

  firefox_video:
    image: selenium/video:ffmpeg-4.3.1-20221219
    volumes:
      - ./test-recordings:/videos
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - FILE_NAME=firefox_video.mp4

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

This is my TestNG suite xml where I am running 3 tests in parallel on 3 different browsers, and in each of the test classes 3 cucumber scenarios will run in parallel.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Smoke Test Suite - Dockerized Selenium Grid" thread-count="10" parallel="tests">
    <listeners>
        <listener class-name="framework.listeners.ScenariosParallelTransformer"/>
    </listeners>
    <test  name="Google Chrome Browser Test">
        <parameter name="browser" value="chrome"/>
        <parameter name="platformName" value="linux"/>
        <classes>
            <class name="framework.runners.BaseTestNGRunnerTest"/>
        </classes>
    </test> <!-- Test -->

    <test  name="Mozilla Firefox Browser Test">
        <parameter name="browser" value="firefox"/>
        <parameter name="platformName" value="linux"/>
        <classes>
            <class name="framework.runners.BaseTestNGRunnerTest"/>
        </classes>
    </test> <!-- Test -->

    <test  name="Microsoft Edge Browser Test">
        <parameter name="browser" value="edge"/>
        <parameter name="platformName" value="linux"/>
        <classes>
            <class name="framework.runners.BaseTestNGRunnerTest"/>
        </classes>
    </test> <!-- Test -->

</suite> <!-- Suite -->
```

I started the docker grid with:
**docker compose -f docker-compose.yml up -d**

and run the tests with maven:
**mvn clean test -D"gridMode=true" -D"scenariosInParallel=true" -PsmokeDockergrid**

After test executions finish, I stop the grid with:
**docker compose -f docker-compose.yml down**

OS: Windows 10
Docker Images: latest 4.7.2

Attached Images will show how the browser instances are running in parallel in docker container, but at 1 time only 1 browser is in focus.
![docker-videos](https://user-images.githubusercontent.com/62521743/211105629-9165eefa-6a67-4497-beef-ac26961c2739.png)

![docker-videos-recording](https://user-images.githubusercontent.com/62521743/211106030-36b3ce98-fec7-4d76-9677-65b66a5cbf9f.png)

### Command used to start Selenium Grid with Docker

```shell
docker compose -f docker-compose.yml up -d
```

### Relevant log output

```shell
$ docker compose -f docker-compose.yml up -d
Network cucumberbdd-oc_default  Creating
Network cucumberbdd-oc_default  Created
Container selenium-hub  Creating
Container selenium-hub  Created
Container cucumberbdd-oc-chrome-1  Creating
Container cucumberbdd-oc-edge-1  Creating
Container cucumberbdd-oc-firefox-1  Creating
Container cucumberbdd-oc-chrome-1  Created
Container cucumberbdd-oc-chrome_video-1  Creating
Container cucumberbdd-oc-firefox-1  Created
Container cucumberbdd-oc-firefox_video-1  Creating
Container cucumberbdd-oc-edge-1  Created
Container cucumberbdd-oc-edge_video-1  Creating
Container cucumberbdd-oc-chrome_video-1  Created
Container cucumberbdd-oc-firefox_video-1  Created
Container cucumberbdd-oc-edge_video-1  Created
Container selenium-hub  Starting
Container selenium-hub  Started
Container cucumberbdd-oc-firefox-1  Starting
Container cucumberbdd-oc-edge-1  Starting
Container cucumberbdd-oc-chrome-1  Starting
Container cucumberbdd-oc-firefox-1  Started
Container cucumberbdd-oc-firefox_video-1  Starting
Container cucumberbdd-oc-edge-1  Started
Container cucumberbdd-oc-edge_video-1  Starting
Container cucumberbdd-oc-chrome-1  Started
Container cucumberbdd-oc-chrome_video-1  Starting
Container cucumberbdd-oc-firefox_video-1  Started
Container cucumberbdd-oc-edge_video-1  Started
Container cucumberbdd-oc-chrome_video-1  Started
```

### Operating System

Windows 10

### Docker Selenium version (tag)

latest 4.7.2
