### ISSUE TITLE
[QUESTION]: Validation of downloaded files using docker-selenium and the Bitbucket Pipelines

### ISSUE THREAD

**Issue by andrii-solaris** [SeleniumHQ/docker-selenium#1779]
### Feature and motivation

**Tech stack**: Java, Maven, Linux, TestNG, Chrome

I'm about to execute the automated end-to-end tests using the docker-selenium chrome version.
Some of the tests include file downloads to the Chrome default folder, which in the Linux container case is: `/home/seluser/Downloads`

**Issue:** I am unable to configure the Bitbucket Pipelines to correctly mount the volumes in order to retrieve the downloaded files.

**Expected result:** The volumes are configured and mounted in a way, that the downloaded files would be retrieved by end-to-end tests, executed via Bitbucket Pipelines.

I would appreciate if thoughts on this or a complete solution would be shared.

### Usage example

Here is how it is used now:

```
pipelines:
  default:
    - step:
        name: End-to-end tests
        caches:
          - maven
        script:  
          - mvn clean test -DsuiteXMLFile=test.xml
        services:
          - selenium-chrome
        artifacts:
          - target/surefire-reports/*

definitions:
  services:
    selenium-chrome:
      image: selenium/standalone-chrome:latest
      memory: 2048
```
