### ISSUE TITLE
[🚀 Feature]: Environment variable to specify the folder where the video is recorded

### ISSUE THREAD

**Issue by alb3ric** [SeleniumHQ/docker-selenium#1868]
### Feature and motivation

Adding a environment variable to define the path where the video is record.
It would be usefull for gitlab-ci. 
We are running our test on a gitlab ci execute with a docker executor. The test are execute on php container with a firefox-standalone service and a selenium/video service to record the process.
We would like to get the recorded video as a artefact, but for this the video need to be recorded into a specific folder.

### Usage example

We would like to have an env called : SE_VIDEO_FILE_FOLDER (for example) to be able to specify the folder where the video is recorded.

**Comment by diemol** [comment]
But you need to mount a [volume to the video container](https://github.com/SeleniumHQ/docker-selenium#video-recording), so you need to mount the location you want and the video will be left there. Unless I am missing something.

**Comment by alb3ric** [comment]
It is the giltab runner that mount the service, and you can't mount additional volumes. By default the only volume mount is /builds.
So I would like to specify the /builds folder as the folder for the video recorded, like this the video will be able to be upload as an artefact of the job.

Example : 

```yaml
test:
  variables:
    FF_NETWORK_PER_BUILD: 1
    GIT_DEPTH: 1
    DISPLAY_CONTAINER_NAME: "docker_browser"
    FILE_NAME: "browser_video.mp4"
   SE_VIDEO_FOLDER: "/builds"
    SCREEN_WIDTH: 1920
    SCREEN_HEIGHT: 1080
  services:
    - name: selenium/standalone-firefox:101.0.1
      alias: docker_browser
      pull_policy: if-not-present
    - name: selenium/video:ffmpeg-4.3.1-20211217
      alias: docker_browser_video
      pull_policy: if-not-present
  image: xxxxxxxxxxxxxxx
  stage: tests
  artifacts:
    when: always
    paths:
      - browser_video.mp4
    expire_in: 5 days
```

Artefact has to be in the builds folder
