### ISSUE TITLE
[🐛 Bug]: opentelemetry-exporter-otlp not found on classpath

### ISSUE THREAD

**Issue by Doofus100500** [SeleniumHQ/docker-selenium#1883]
### What happened?

Hi, i'm trying to write traces in OpenTelemetry

### Command used to start Selenium Grid with Docker

```shell
I'm using helm chart v. 0.19.0 to start Grid in distributed mode in Kubernetes. In values file i add:
  extraEnvironmentVariables:
    - name: SE_JAVA_OPTS
      value: "-Dotel.traces.exporter=otlp -Dotel.exporter.otlp.endpoint=https://some.host -Dotel.resource.attributes=service.name=SomeTeam.selenium-grid"
```

### Relevant log output

```shell
io.opentelemetry.sdk.autoconfigure.spi.ConfigurationException: otel.traces.exporter set to "otlp" but opentelemetry-exporter-otlp not found on classpath. Make sure to add it as a dependency.
```

### Operating System

k8s

### Docker Selenium version (tag)

selenium-grid-4.10.0-20230607

**Comment by diemol** [comment]
Seems you are missing `SE_ENABLE_TRACING=true`

https://github.com/SeleniumHQ/docker-selenium#tracing-in-grid

**Comment by Doofus100500** [comment]
> Seems you are missing `SE_ENABLE_TRACING=true`
> 
> https://github.com/SeleniumHQ/docker-selenium#tracing-in-grid

No, i have this:
`    - name: SE_ENABLE_TRACING
      value: "true"`

**Comment by diemol** [comment]
I didn't know, you did not post it.

Seems the dependencies in the images are out of date, we will check this for the next release.

**Comment by Doofus100500** [comment]
> I didn't know, you did not post it.
> 
> Seems the dependencies in the images are out of date, we will check this for the next release.

Thanks a lot, looking forward to it

**Comment by madhankumar866** [comment]
Try This one it's working

chart v. 0.19.0  Distributed mode in Kubernetes
```
  extraEnvironmentVariables:
    - name: SE_ENABLE_TRACING
      value: "true"  
    - name: JAVA_OPTS
      value: "-Dotel.traces.exporter=jaeger -Dotel.exporter.jaeger.endpoint=http://jaegar-collector:14250 -Dotel.resource.attributes=service.name=selenium-grid"
```
