### ISSUE TITLE
[🚀 Feature]: Support livenessProbe for the nodes in the Helm Chart

### ISSUE THREAD

**Issue by brunobritorj** [SeleniumHQ/docker-selenium#1895]
### Feature and motivation

Currently, there is only ```livenessProbe``` option in the Helm Chart values for the ```router``` and ```hub``` components, there is no way to add the probe to ```chromeNode```, ```firefoxNode```, and ```edgeNode```. 

### Usage example

Currently, common properties such as ```imageName```, ```annotations```, ```labels```, ```resources```, ```ports``` are supported and placed into the first level in each node. So, the ```values.yaml``` file could be adapted to support ```livenessProbe```:

```yaml
chromeNode:
  (...)
  livenessProbe: {}
firefoxNode:
  (...)
  livenessProbe: {}
edgeNode:
  (...)
  livenessProbe: {}
```
