### ISSUE TITLE
[🐛 Bug]: Chrome Standalone Docker Image cannot download file

### ISSUE THREAD

**Issue by AsukaWhite** [SeleniumHQ/docker-selenium#1918]
### What happened?

when using the docker image, cannot find the filename.crdownload in anyplace.
I'm using python,and selenium is a module for function not distribution test.
Need help!!!
Code for selenium initilization:

```
prefs = {"download.default_directory": download_path}
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_experimental_option('prefs', prefs)
driver = webdriver.Chrome(options=chrome_options)
```

### Command used to start Selenium Grid with Docker

```shell
FROM selenium/standalone-chrome

WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
USER root

RUN apt-get update -y
RUN apt-get install python3-pip -y
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

RUN useradd -m -u 1000 user
USER user

ENV HOME=/home/user \
	PATH=/home/user/.local/bin:$PATH

WORKDIR $HOME/app

COPY --chown=user . $HOME/app
RUN python3 --version
CMD ["python3", "app.py"]
```

### Relevant log output

```shell
No error log
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

selenium/standalone-chrome

**Comment by stephenarifin-payscore** [comment]
Also facing this issue

Adding a little more info in ruby:

I use `setup headless_for_download` like this:

```
def setup_headless_for_download
    bridge = page.driver.browser.send(:bridge)

    path = "/session/#{bridge.session_id}/chromium/send_command"
    path = ENV['SELENIUM_URL'] + path if ENV['SELENIUM_URL'].present?

    bridge.http.call(
      :post,
      path,
      cmd: 'Page.setDownloadBehavior',
      params: {
        behavior: 'allow',
        downloadPath: PATH
      }
    )
  end
```

And my github actions workflow is set up like this:

```
run_system_tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        volumes:
          - ${{ github.workspace }}:${{ github.workspace }}
```
