### ISSUE TITLE
Selenium access "Problem loading page"

### ISSUE THREAD

**Issue by iGitScor** [SeleniumHQ/docker-selenium#193]
Hi,

I don't know if my issue is relative to the #133 or #174  one but I open this issue because I don't really now why the Selenium test doesn't reach my application.

Docker compose :
`docker-compose version 1.6.2, build 4d72027`

In the `docker-compose.yml` file, I have the following configuration :

``` yml
hub:
    image: selenium/hub
    ports:
        - "4444:4444"
firefox:
    image: selenium/node-firefox
    links:
        - hub
chrome:
    image: selenium/node-chrome
    links:
        - hub
app-src:
    container_name: app-src
    image: busybox
    volumes:
        - .:/var/www
app-web:
    container_name: app-web
    build: docker/web/.
    links:
        - app-src
        - hub
```

The problem is when I launch my Selenium test from `app-web` to the hub address, the Selenium server responds but the test script doesn't reach my `app-web` container. It seems the connectivity is one-way.

✖ Testing if the page title equals "Title".  - expected "Title" but got: Problem loading page

Do you need more information ?
