### ISSUE TITLE
[🐛 Bug]: Video Live Streaming of Node Test Executions runs to a blank page on Kubernetes

### ISSUE THREAD

**Issue by kherath17** [SeleniumHQ/docker-selenium#1991]
### What happened?

I have setup Selenium Hub (selenium/hub:latest)  and  unable to view the live execution happening on the node , runs into a blank page 

![image](https://github.com/SeleniumHQ/docker-selenium/assets/54758666/05dbc5f3-f6aa-47d8-b788-90cb2e6712c0)

### Command used to start Selenium Grid with Docker

```shell
Started through kubernetes , following is my deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        #image: selenium/hub:4.13.0-20231004 #4.1,4.13
        image: selenium/hub:latest
        ports:
          - containerPort: 4444
          - containerPort: 4443
          - containerPort: 4442
        resources:
          limits:
            memory: "4000Mi"
            cpu: "2"
          requests:
            memory: "4000Mi"
            cpu: "2"  
        livenessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5

I have also setup the respective SVCs and Ingress Rules
```

### Relevant log output

```shell
NA
```

### Operating System

Windows 11

### Docker Selenium version (tag)

4.14.1

**Comment by VietND96** [comment]
Hi @kherath17, did you start the grid setup using helm chart selenium-grid? Or have you created your own K8s manifest files for deployment?

**Comment by kherath17** [comment]
@vietnd96 Its my own deployment files I have used

**Comment by VietND96** [comment]
Oh, so could you please also share the deployment file of the browser node for reference?

**Comment by kherath17** [comment]
@vietnd96 FYI I have used a POD as below

apiVersion: v1
kind: Pod
metadata:
  name: selenium-node-chrome
  labels:
    name: selenium-node-chrome
    app: selenium-node-chrome
spec:                 
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:        
      - name: selenium-node-chrome
        image: selenium/node-chrome:4.13.0-20231004
        ports:
          - containerPort: 5555
          #- containerPort: 7900
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: SE_EVENT_BUS_HOST
            value: "selenium-hub"
          - name: SE_EVENT_BUS_SUBSCRIBE_PORT
            value: "4443"
          - name: SE_EVENT_BUS_PUBLISH_PORT
            value: "4442"
          - name: SE_NODE_MAX_SESSIONS 
            value: "2"      
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"

**Comment by VietND96** [comment]
[reproduce.txt](https://github.com/SeleniumHQ/docker-selenium/files/13237868/reproduce.txt)
Based on your input, I created a simple file with hub (deploy, svc) and node deploy. Then deployed it via `kubectl apply`, and started a test execution, I could see the video stream properly.
Can you try the next step checking pod logs of the browser node, is there any error logs related to "start-novnc"?
Moreover, I saw you mentioned above that "ingress rules" is configured. Can you check the ingress handles vnc request properly also?
![image](https://github.com/SeleniumHQ/docker-selenium/assets/23253546/a6a983c3-68ad-4032-9849-e03c9cff0bd9)

**Comment by kherath17** [comment]
@vietnd96 appreciate your effort looking into this , since it works on your end I doubt if its the ingress , would you be able to share me the ingress file you have used

**Comment by VietND96** [comment]
Actually, I didn't apply ingress in above case, only 3 components as .txt that I shared. I access the grid view inside cluster via `ClusterIP` only. So if your end is using ingress and facing that issue, can you share your ingress, so I can take a look?

**Comment by kherath17** [comment]
@vietnd96 here is my ingress

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qlabv2-ingress
  namespace: qlabv2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2 
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: selenium-hub-service
            port:
              number: 80      
        path: /qlabv2(/|$)(.*)
        pathType: ImplementationSpecific

**Comment by kherath17** [comment]
HI @vietnd96 do you see any misconfigurations in my ingress?

**Comment by VietND96** [comment]
Hi @kherath17 , it looks like ingress using path prefix and rewrite-target with regexp caused the issue. Some URL after redirected is incorrect. e.g
When goto `http://hostname/qlabv2`, it should redirect to `http://hostname/qlabv2/ui`, but actually it was `http://hostname/ui`
Similarly, when opening video stream page, vnc request should call `ws://hostname/qlabv2/session/79c652bc117b51a5fefda5b4be0c4854/se/vnc` but it was `ws://hostname/session/79c652bc117b51a5fefda5b4be0c4854/se/vnc` - 404 not found, and no video stream on page

Currently, I only can suggest you use `path: /` - it works on my end.
For the case path prefix with rewrite-target using regexp. I'll let you know if I am able to find a configuration-snippet can handle it.

**Comment by kherath17** [comment]
Thank You @vietnd96 for clarifying the root cause , but unfortunately I'm unable to use **path: /** since there's an already running ingress for that path , hence I will need to use some other path to route it

**Comment by diemol** [comment]
Thank you for troubleshooting, @vietnd96! Are you in the Selenium Slack workspace?

**Comment by VietND96** [comment]
Hi @diemol , I was just aware and joined the Selenium Slack workspace.

**Comment by VietND96** [comment]
Hi @kherath17 , I suggest a workaround for prefix path config
Below sample with selenium grid runs on `http://hostname/qlabv2`
By using [SE_SUB_PATH](https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#setting-sub-path). In the hub deploy, add ENV for hub container
```yaml
          env:
            - name: SE_SUB_PATH
              value: /qlabv2
```
Now, without ingress, grid view can be accessed via `http://ClusterIP:4444/qlabv2/`
The ingress configs would be
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selenium-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /qlabv2
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /qlabv2(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: selenium-hub
                port:
                  number: 4444
          - path: /(/?)(session/.*/se/vnc)
            pathType: Prefix
            backend:
              service:
                name: selenium-hub
                port:
                  number: 4444
```
With this config it will resolve redirect issue we mentioned above
- `http://hostname/qlabv2` -> `http://hostname/qlabv2/ui` - 200 OK
- `ws://hostname/session/79c652bc117b51a5fefda5b4be0c4854/se/vnc` -> `ws://hostname/qlabv2/session/79c652bc117b51a5fefda5b4be0c4854/se/vnc` - 101 Switching Protocols

Deployment file for your reference - [workaround.txt](https://github.com/SeleniumHQ/docker-selenium/files/13255196/workaround.txt)

---
Hi @diemol , I also have a doubt here, even we set `SE_SUB_PATH` but url of session vnc does not contain the sub path.
I also try to set in node this ENV
```
        - name: SE_NODE_GRID_URL
          value: "http://selenium-hub:4444/qlabv2"
```
but in node Capabilities, the URL still not have sub path
```json
  "se:vnc": "ws://selenium-hub:4444/session/623cb93cd9438c195578b7edc5b0b534/se/vnc",
  "se:vncEnabled": true,
```
I saw the same issue discussed in https://github.com/SeleniumHQ/selenium/issues/9980, and there was a commit fixed https://github.com/SeleniumHQ/selenium/commit/ca9b4514013c6c93ec5b6c791c2149404eabb952 by you. Do you know this? @diemol
