### ISSUE TITLE
[🚀 Feature]: Adding port to nodes service

### ISSUE THREAD

**Issue by piotrlaczykowski** [SeleniumHQ/docker-selenium#1995]
### Feature and motivation

Hello,
you gave us an option to open a port for pods. Can you also add this option for service?

### Usage example

We added SSH to our chrome/edge-nodes and there is no option to use it without port opening in service.

**Comment by VietND96** [comment]
Hi, can you confirm that your requirements will have the outcomes something like
`values.yaml`
```yaml
edgeNode:
  ports:
    - 22
```
`selenium-grid/templates/edge-node-service.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: selenium-edge-node
...
spec:
  type: ClusterIP  # or NodePort or LoadBalancer
  ports:
    - port: 22
      targetPort: 22
      # nodePort: 30xxx
```
