### ISSUE TITLE
How to configure video-image?

### ISSUE THREAD

**Issue by alxweis** [SeleniumHQ/docker-selenium#2022]
## My Setup
**docker-compose.yml**
```
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.15.0-20231110
    volumes:
      - ./assets:/opt/selenium/assets
      - ./config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2gb

  selenium-hub:
    image: selenium/hub:4.15.0-20231110
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```
**config.toml**
```
[docker]
configs = [
    "selenium/standalone-chrome:100.0", "{\"browserName\": \"chrome\", \"browserVersion\": \"100.0\"}",
    "selenium/standalone-chrome:93.0", "{\"browserName\": \"chrome\", \"browserVersion\": \"93.0\"}"
]

url = "http://127.0.0.1:2375"
video-image = "selenium/video:ffmpeg-4.3.1-20231016"
```

## Description
With the Simple Grid, a separate video container is started for each node container. The ENV variables of the video containers can therefore easily be adjusted in `docker-compose.yml`.

With the Dynamic Grid, however, the video image is only referenced in the `config.toml` so that it can be used for test sessions.
So the question for me is whether it is possible to set ENV variables for these video containers, for example the frame rate or the name of the video file?

Below is an image of a video container in Docker desktop with `SE_` ENV variables that may be able to be set.
![image](https://github.com/SeleniumHQ/docker-selenium/assets/105790090/33b44109-ba42-4a84-8f20-3534031792dc)

### Command used to start Selenium Grid with Docker

```shell
docker-compose up
```

### Relevant log output

```shell
NA
```

### Operating System

Windows 10

### Docker Selenium version (tag)

4.15.0-20231110
