### ISSUE TITLE
[🐛 Bug]: Regression: imageName variable not working properly in Helm chart v0.25.1+

### ISSUE THREAD

**Issue by durera** [SeleniumHQ/docker-selenium#2035]
### What happened?

In `0.25.0` setting e.g. the following in a values file and running `helm install -n selenium selenium-grid docker-selenium/selenium-grid -f /tmp/selenium-values.yml`:

```yaml
edgeNode:
  imageName: mylocalregistry/selenium/node-edge
  imageTag: 4.15.0-20231122
  imagePullSecret: mypullsecret
```

results in the expected image being used in the deployment:

```yaml
      image: mylocalregistry/selenium/node-chrome:4.15.0-20231122
```

As of 0.25.1 it results in the following - with the namespace prefixed to the image name:
```yaml
      image: selenium/mylocalregistry/selenium/node-chrome:4.15.0-20231122
```

### Command used to start Selenium Grid with Docker

```shell
helm install -n selenium selenium-grid docker-selenium/selenium-grid -f /tmp/selenium-values.yml
```

### Relevant log output

```shell
helm list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION    
selenium-grid   selenium        1               2023-11-29 15:55:13.804552928 +0000 UTC deployed        selenium-grid-0.25.3    4.15.0-20231129
```

### Operating System

Kubernetes

### Docker Selenium version (tag)

selenium-grid-0.25.3 / 4.15.0-20231129

**Comment by diemol** [comment]
0.25.3 is out and I believe that is fixed.

**Comment by durera** [comment]
> 0.25.3 is out and I believe that is fixed.

Afraid not ... hit the same in 0.25.1 and 0.25.3 (reproduced on 0.25.3 just now, as below):

```
helm -n selenium list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION    
selenium-grid   selenium        1               2023-11-29 17:40:37.1863814 +0000 UTC   deployed        selenium-grid-0.25.3    4.15.0-20231129
```

Same result (snippet from `selenium-chrome-node-xxx` deployment, from a 0.25.3):

```yaml
      envFrom:
        - configMapRef:
            name: selenium-event-bus-config
        - configMapRef:
            name: selenium-node-config
      image: >-
        selenium/XXXX/selenium/node-chrome:4.15.0-20231122
  serviceAccount: selenium-serviceaccount
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 1Gi
    - name: kube-api-access-47vz4
```

**Comment by VietND96** [comment]
Hello @durera
I assume the image in your local repo would be `mylocalregistry/selenium/node-edge:4.15.0-20231122`
Can you please try this config with latest chart 0.25.3
```yaml
edgeNode:
  imageRegistry: mylocalregistry/selenium
  imageName: node-edge
  imageTag: 4.15.0-20231122
  imagePullSecret: mypullsecret
```
