### ISSUE TITLE
[🐛 Bug]: Test Execution viewing for Selenium Grid runs into blank page WSS Status turns to Finished Immediately 

### ISSUE THREAD

**Issue by kherath17** [SeleniumHQ/docker-selenium#2124]
### What happened?

I have setup Selenium Grid on K8 and has 2 namespaces for Prod And Test Environments , my whole setup including test execution viewing **is working on the Prod Setup not in Test Environment**, tried troubleshooting and comparing everything looks fine from ingress rules to deployment files used and other configurations.

**Noticed Below on network calls for WSS:**

Runs into finish status as soon as request starts

![image](https://github.com/SeleniumHQ/docker-selenium/assets/54758666/50682cb8-4b61-4a14-afaf-52a2b5d44e6a)

And also shows `Provisional Headers are shown`

![image](https://github.com/SeleniumHQ/docker-selenium/assets/54758666/ed60a16f-3006-4688-9125-82d90298f200)

**Below is my Hub Deployment:**

apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:latest
        ports:
          - containerPort: 4444
          - containerPort: 4443
          - containerPort: 4442
        resources:
          limits:
            memory: "4000Mi"
            cpu: "2"
          requests:
            memory: "4000Mi"
            cpu: "2"  
        livenessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        env:          
          - name: SE_SUB_PATH  
            value: /sandbox_qlabv2
          - name: SE_SESSION_REQUEST_TIMEOUT
            value: "900"
          - name: SE_SESSION_RETRY_INTERVAL
            value: "900"
            
            
**Below is My Ingress:**

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qlabv2-ingress
  #namespace: qlabv2
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/app-root: /qlabv2
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3000"
spec:
  rules:
    - http:
        paths:         
          - path: /sandbox_qlabv2(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: selenium-hub-service
                port:
                  number: 80
          - path: /(/?)(session/.*/se/vnc)
            pathType: Prefix
            backend:
              service:
                name: selenium-hub-service
                port:
                  number: 80

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
Started via Deployment Files
kubectl create -f <deployment.yaml> -n mynamespace
```

### Relevant log output

```shell
No Output, just blank screen with WSS on Finished status
```

### Operating System

Windows 11

### Docker Selenium version (image tag)

4.17.0

**Comment by VietND96** [comment]
After a few fixes related to subPath and Node Websockets, now we need to configure
1. Node deployment
```yaml
...
env:
  - name: SE_NODE_GRID_URL
  - value: http://your.domain.com/subPath
```
2. Ingress: (remove the workaround for path: /(/?)(session/./se/vnc) - it's no need anymore since 4.17.0), something like
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selenium-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /subPath
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: 'selenium-router'
                port:
                  number: 4444
            path: /subPath(/|$)(.*)
            pathType: ImplementationSpecific
```
