### ISSUE TITLE
[🐛 Bug]: Cannot set node stereotype with SE_OPTS for versioned browser nodes

### ISSUE THREAD

**Issue by akhilesh-sivaganesan** [SeleniumHQ/docker-selenium#2150]
### What happened?

I am trying to register a node with a custom capability to the hub using the driver configuration flag added in the `SE_OPTS` environment variable. In the log output, the node doesn't seem to register with the specified configuration. I have only had this problem when trying to add images following the tagging convention `selenium/node-chrome:90.0`, or some other version. 

I am new to selenium and docker-selenium, so this might be a usage issue but I have tried the following:

- **SE_NODE_STEREOTYPE**: `"\"{\"browserName\": \"chrome\", \"browserVersion\": \"90\", \"platformName\": \"Linux\"}\""`
- **SE_OPTS with the --docker flag**: `"--docker selenium/node-chrome:90.0 {\"browserName\": \"chrome\", \"browserVersion\": \"90\", \"platformName\": \"Linux\"}"`
- **GENERATE_CONFIG**: `"false"` This one's from this [issue](https://github.com/SeleniumHQ/docker-selenium/issues/1622) for this variable

I have already looked at the [CLI options ](https://www.selenium.dev/documentation/grid/configuration/cli_options/), and I don't believe to be passing in the arguments incorrectly. I have also found this section from the documentation on custom capability matching using [custom cap](https://www.selenium.dev/documentation/grid/configuration/cli_options/#setting-custom-capabilities-for-matching-specific-nodes), though that option doesn't work either.

Is there a way to properly register a version tagged node image (such as node-chrome:90.0 or node-firefox:100.0) to the hub, _without using config.toml or the hub and node-docker setup_? What would the corrected docker-compose.yml look like?
 
 
 Below is my docker-compose-save.yml file.

```
version: '3'
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    environment:
      SELENIUM_HUB_PORT: 4444
    networks:
      - gen-network

  chrome-90-service:
    image: selenium/node-chrome:90.0
    container_name: chrome-90-node
    shm_size: "2gb"
    ports:
      - "5900:5900"
      - "7900:7900"
    environment:
      SE_OPTS: "--driver-configuration display-name=\"chromename\" stereotype=\"{\"browserName\": \"chrome\", \"browserVersion\": \"90\", \"platformName\": \"Linux\"}\" max-sessions=3"
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

    depends_on:
      - selenium-hub
    networks:
      - gen-network
networks:
  gen-network:
    driver: bridge
```

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
docker-compose -f docker-compose-save.yml up
```

### Relevant log output

```shell
Creating network "mergedb_gen-network" with driver "bridge"
Creating selenium-hub ... done
Creating chrome-90-node ... done
Attaching to selenium-hub, chrome-90-node
selenium-hub         | 2024-02-27 00:52:43,602 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
selenium-hub         | 2024-02-27 00:52:43,605 INFO RPC interface 'supervisor' initialized
selenium-hub         | 2024-02-27 00:52:43,605 CRIT Server 'unix_http_server' running without any HTTP authentication checking
selenium-hub         | 2024-02-27 00:52:43,605 INFO supervisord started with pid 8
chrome-90-node       | 2024-02-27 00:52:43,902 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
chrome-90-node       | 2024-02-27 00:52:43,904 INFO supervisord started with pid 8
selenium-hub         | 2024-02-27 00:52:44,611 INFO spawned: 'selenium-grid-hub' with pid 9
selenium-hub         | Appending Selenium options: --reject-unsupported-caps false
selenium-hub         | Tracing is disabled
selenium-hub         | 2024-02-27 00:52:44,616 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome-90-node       | 2024-02-27 00:52:44,907 INFO spawned: 'xvfb' with pid 10
chrome-90-node       | 2024-02-27 00:52:44,909 INFO spawned: 'vnc' with pid 11
chrome-90-node       | 2024-02-27 00:52:44,911 INFO spawned: 'novnc' with pid 12
chrome-90-node       | 2024-02-27 00:52:44,913 INFO spawned: 'selenium-node' with pid 14
chrome-90-node       | 2024-02-27 00:52:44,950 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome-90-node       | 2024-02-27 00:52:44,950 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome-90-node       | 2024-02-27 00:52:44,950 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome-90-node       | 2024-02-27 00:52:44,950 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub         | 00:52:45.003 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
selenium-hub         | 00:52:45.014 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
selenium-hub         | 00:52:45.153 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://192.168.16.2:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://192.168.16.2:4443]
selenium-hub         | 00:52:45.204 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://192.168.16.2:4442 and tcp://192.168.16.2:4443
selenium-hub         | 00:52:45.257 INFO [UnboundZmqEventBus.<init>] - Sockets created
chrome-90-node       | Appending Selenium options: --driver-configuration display-name="chromename" stereotype="{"browserName": "chrome", "browserVersion": "90", "platformName": "Linux"}" max-sessions=3
chrome-90-node       | Configuring server...
chrome-90-node       | Setting up SE_NODE_HOST...
chrome-90-node       | Setting up SE_NODE_PORT...
chrome-90-node       | Setting up SE_NODE_GRID_URL...
chrome-90-node       | Starting Selenium Grid Node with configuration: 
chrome-90-node       | [events]
chrome-90-node       | publish = "tcp://selenium-hub:4442"
chrome-90-node       | subscribe = "tcp://selenium-hub:4443"
chrome-90-node       | 
chrome-90-node       | [node]
chrome-90-node       | session-timeout = "300"
chrome-90-node       | override-max-sessions = false
chrome-90-node       | max-sessions = 1
chrome-90-node       | 
chrome-90-node       | 00:52:45.602 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
chrome-90-node       | 00:52:45.606 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
chrome-90-node       | 00:52:45.703 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
chrome-90-node       | 00:52:45.769 INFO [UnboundZmqEventBus.<init>] - Sockets created
selenium-hub         | 00:52:46.263 INFO [UnboundZmqEventBus.<init>] - Event bus ready
chrome-90-node       | 00:52:46.771 INFO [UnboundZmqEventBus.<init>] - Event bus ready
selenium-hub         | 00:52:46.780 INFO [Hub.execute] - Started Selenium Hub 4.18.0 (revision b6bf9de7cc): http://192.168.16.2:4444
chrome-90-node       | 00:52:46.870 INFO [NodeServer.createHandlers] - Reporting self as: http://192.168.16.3:5555
chrome-90-node       | 00:52:46.887 INFO [NodeOptions.getSessionFactories] - Detected 4 available processors
chrome-90-node       | 00:52:46.903 INFO [NodeOptions.discoverDrivers] - Discovered 1 driver(s)
chrome-90-node       | java.lang.reflect.InvocationTargetException
chrome-90-node       | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
chrome-90-node       | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
chrome-90-node       | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
chrome-90-node       | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
chrome-90-node       | 	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
chrome-90-node       | 	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
chrome-90-node       | Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
chrome-90-node       | 	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
chrome-90-node       | 	at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:93)
chrome-90-node       | 	at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:125)
chrome-90-node       | 	at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:181)
chrome-90-node       | 	at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:227)
chrome-90-node       | 	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
chrome-90-node       | 	at org.openqa.selenium.grid.Main.launch(Main.java:83)
chrome-90-node       | 	at org.openqa.selenium.grid.Main.go(Main.java:57)
chrome-90-node       | 	at org.openqa.selenium.grid.Main.main(Main.java:42)
chrome-90-node       | 	... 6 more
chrome-90-node       | Caused by: java.lang.reflect.InvocationTargetException
chrome-90-node       | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
chrome-90-node       | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
chrome-90-node       | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
chrome-90-node       | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
chrome-90-node       | 	at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
chrome-90-node       | 	at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
chrome-90-node       | 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
chrome-90-node       | 	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
chrome-90-node       | 	... 14 more
chrome-90-node       | Caused by: org.openqa.selenium.grid.config.ConfigException: Expected each driver config to have three elements (name, stereotype and max-sessions)
chrome-90-node       | 	at org.openqa.selenium.grid.node.config.NodeOptions.lambda$addDriverConfigs$14(NodeOptions.java:231)
chrome-90-node       | 	at java.base/java.util.Optional.ifPresent(Optional.java:183)
chrome-90-node       | 	at org.openqa.selenium.grid.node.config.NodeOptions.addDriverConfigs(NodeOptions.java:229)
chrome-90-node       | 	at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:150)
chrome-90-node       | 	at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:72)
chrome-90-node       | 	... 22 more
chrome-90-node       | 2024-02-27 00:52:47,273 INFO exited: selenium-node (exit status 1; not expected)
```

### Operating System

Ubuntu

### Docker Selenium version (image tag)

4.18.1-20240224

**Comment by diemol** [comment]
The Node configuration is explained in the [README](https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#node-configuration-options). The issue is that `SE_NODE_STEREOTYPE` did not exist when the Chrome 90 image was released. 

What you can do is copy the `config.toml` that exists inside the container, modify it, and then mount it in the next execution. 

If you have more questions, please use the links below.

**Comment by akhilesh-sivaganesan** [comment]
Where is the config.toml located by default in chrome 90? How can I find it and modify it in my docker-compose file? After reading through the node configuration documentation, I understand that I should try to bind a config.toml, but after binding to `opt/bin/config.toml`, node-chrome:90.0 doesn't recognize it.

**Comment by diemol** [comment]
Should be at https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeBase/Dockerfile#L181

But cannot guarantee because you are using a very old version.

**Comment by akhilesh-sivaganesan** [comment]
I found that file useful in better understanding the config process. I tried setting chrome 90's config using the following volume bind. I see that it is being read in the logs evidenced by the custom driver configuration. However, the node doesn't register, it just infinitely keeps sending registration requests. There also seems to be a permission denied error from
`chrome-90-node        | /opt/bin/generate_config: line 6: /opt/selenium/config.toml: Permission denied`

The docker-compose-save.yml file (note I purposefully made the chrome 100, 115 exit since they seem to not need my custom driver configuration.
```
version: '3'
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    environment:
      SELENIUM_HUB_PORT: 4444
    networks:
      - gen-network

  chrome-90-service:
    image: selenium/node-chrome:90.0
    container_name: chrome-90-node
    shm_size: "2gb"
    ports:
      - "5900:5900"
      - "7900:7900"
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443 
      # SE_OPTS: "--config opt/selenium/config2.toml"
    depends_on:
      - selenium-hub
    volumes:
      - ./config-test2.toml:/opt/selenium/config.toml
    networks:
      - gen-network
    # command: ["cat", "opt/bin/config.toml"]
    # command: "echo -n > /opt/selenium/config.toml"


  chrome-100-service:
    image: selenium/node-chrome:100.0
    container_name: chrome-100-node
    shm_size: "2gb"
    ports:
      - "5901:5900"
      - "7901:7900"
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443     
    depends_on:
      - selenium-hub
    networks:
      - gen-network
    command: ["cat", "opt/selenium/config.toml"]
    # command: ["find",  "/",  "-type",  "f", "-name",  "\"config.toml\""]
    # command: ["sh", "-c", "find / -type f -name 'config.toml' 2>/dev/null"]


  
  chrome-115-service:
    image: selenium/node-chrome:115.0
    container_name: chrome-115-node
    shm_size: "2gb"
    ports:
      - "5902:5900"
      - "7902:7900"
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443     
    depends_on:
      - selenium-hub
    networks:
      - gen-network
    command: ["cat", "opt/selenium/config.toml"]


networks:
  gen-network:
    driver: bridge
```

The config-test2.toml being mounted:
```
[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "90", "platformName": "Linux"}'
max-sessions = 3
```

The command used to run:
```
$ docker-compose -f docker-compose-save.yml up
```
The output:
```

Creating network "mergedb_gen-network" with driver "bridge"
Creating selenium-hub ... done
Creating chrome-100-node ... done
Creating chrome-90-node  ... done
Creating chrome-115-node ... done
Attaching to selenium-hub, chrome-100-node, chrome-115-node, chrome-90-node
selenium-hub          | 2024-02-29 00:23:03,722 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
selenium-hub          | 2024-02-29 00:23:03,724 INFO RPC interface 'supervisor' initialized
selenium-hub          | 2024-02-29 00:23:03,724 CRIT Server 'unix_http_server' running without any HTTP authentication checking
selenium-hub          | 2024-02-29 00:23:03,724 INFO supervisord started with pid 8
chrome-90-node        | 2024-02-29 00:23:04,314 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
chrome-90-node        | 2024-02-29 00:23:04,317 INFO supervisord started with pid 8
chrome-100-node exited with code 0
chrome-115-node exited with code 0
selenium-hub          | 2024-02-29 00:23:04,727 INFO spawned: 'selenium-grid-hub' with pid 9
selenium-hub          | Appending Selenium options: --reject-unsupported-caps false
selenium-hub          | Tracing is disabled
selenium-hub          | 2024-02-29 00:23:04,731 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub          | 00:23:05.036 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
selenium-hub          | 00:23:05.042 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
selenium-hub          | 00:23:05.146 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://192.168.32.2:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://192.168.32.2:4443]
selenium-hub          | 00:23:05.214 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://192.168.32.2:4442 and tcp://192.168.32.2:4443
selenium-hub          | 00:23:05.230 INFO [UnboundZmqEventBus.<init>] - Sockets created
chrome-90-node        | 2024-02-29 00:23:05,319 INFO spawned: 'xvfb' with pid 10
chrome-90-node        | 2024-02-29 00:23:05,321 INFO spawned: 'vnc' with pid 11
chrome-90-node        | 2024-02-29 00:23:05,323 INFO spawned: 'novnc' with pid 12
chrome-90-node        | 2024-02-29 00:23:05,324 INFO spawned: 'selenium-node' with pid 14
chrome-90-node        | 2024-02-29 00:23:05,336 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome-90-node        | 2024-02-29 00:23:05,336 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome-90-node        | 2024-02-29 00:23:05,336 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome-90-node        | 2024-02-29 00:23:05,336 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome-90-node        | /opt/bin/generate_config: line 6: /opt/selenium/config.toml: Permission denied
chrome-90-node        | Configuring server...
chrome-90-node        | Setting up SE_NODE_HOST...
chrome-90-node        | Setting up SE_NODE_PORT...
chrome-90-node        | /opt/bin/generate_config: line 26: /opt/selenium/config.toml: Permission denied
chrome-90-node        | Setting up SE_NODE_GRID_URL...
chrome-90-node        | /opt/bin/generate_config: line 33: /opt/selenium/config.toml: Permission denied
chrome-90-node        | /opt/bin/generate_config: line 34: /opt/selenium/config.toml: Permission denied
chrome-90-node        | /opt/bin/generate_config: line 36: /opt/selenium/config.toml: Permission denied
chrome-90-node        | Starting Selenium Grid Node with configuration: 
chrome-90-node        | [[node.driver-configuration]]
chrome-90-node        | display-name = "chrome"
chrome-90-node        | stereotype = '{"browserName": "chrome", "browserVersion": "90", "platformName": "Linux"}'
chrome-90-node        | max-sessions = 300:23:05.940 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
chrome-90-node        | 00:23:05.943 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
chrome-90-node        | 00:23:06.020 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://*:4442 and tcp://*:4443
chrome-90-node        | 00:23:06.098 INFO [UnboundZmqEventBus.<init>] - Sockets created
selenium-hub          | 00:23:06.232 INFO [UnboundZmqEventBus.<init>] - Event bus ready
selenium-hub          | 00:23:06.707 INFO [Hub.execute] - Started Selenium Hub 4.18.0 (revision b6bf9de7cc): http://192.168.32.2:4444
chrome-90-node        | 00:23:07.100 INFO [UnboundZmqEventBus.<init>] - Event bus ready
chrome-90-node        | 00:23:07.198 INFO [NodeServer.createHandlers] - Reporting self as: http://192.168.32.5:5555
chrome-90-node        | 00:23:07.210 INFO [NodeOptions.getSessionFactories] - Detected 4 available processors
chrome-90-node        | 00:23:07.222 INFO [NodeOptions.discoverDrivers] - Discovered 1 driver(s)
chrome-90-node        | 00:23:07.250 INFO [NodeOptions.report] - Adding Custom Slot Config for {"browserName": "chrome","browserVersion": "90","platformName": "Linux"} 3 times
chrome-90-node        | 00:23:07.252 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome","platformName": "LINUX"} 4 times
chrome-90-node        | 00:23:07.264 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
chrome-90-node        | 00:23:07.381 INFO [NodeServer$1.start] - Starting registration process for node id 02a6796c-b4de-49bc-b56d-6b142e59b034
chrome-90-node        | 00:23:07.382 INFO [NodeServer.execute] - Started Selenium node 4.0.0-beta-4 (revision e9c738de8a): http://192.168.32.5:5555
chrome-90-node        | 00:23:07.408 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
chrome-90-node        | 00:23:17.425 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
chrome-90-node        | 00:23:27.436 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
chrome-90-node        | 00:23:37.440 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
chrome-90-node        | 00:23:47.443 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
chrome-90-node        | 00:23:57.445 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
chrome-90-node        | 00:24:07.449 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
chrome-90-node        | 00:24:17.455 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
chrome-90-node        | 00:24:27.462 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
chrome-90-node        | 00:24:37.466 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
chrome-90-node        | 00:24:47.469 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
chrome-90-node        | 00:24:57.474 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
chrome-90-node        | 00:25:07.384 INFO [NodeServer$1.lambda$start$1] - Sending registration event...



```
