### ISSUE TITLE
[🐛 Bug]: VNC process keeps crashing

### ISSUE THREAD

**Issue by cmavromoustakos** [SeleniumHQ/docker-selenium#2170]
### What happened?

Hello, I am working with our QA engineer to try to debug why VNC is not working on his machine. We are running the same exact docker images:

```
# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-dev-channel.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-dev-channel.yml down`
version: "3"
services:
  chrome:
    image: selenium/node-chrome:dev
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900:5900"
  edge:
    image: selenium/node-edge:dev
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:dev
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

He is on an M1 mac and I am on an Ubuntu machine. When he runs `docker-compose up chrome` he keeps getting the below error nexia_development-chrome-1  `vnc (terminated by SIGTRAP; not expected)`. 

We tried a random version which I got from https://github.com/SeleniumHQ/docker-selenium/issues/1076#issuecomment-1002301688 thinking it was an M1 issue but then when I looked again realized that the images were not seleniarm images. So I think this might be a bug with the :dev and :latest images.

This worked for him 
```
  selenium-hub:
    image: selenium/hub:4.1.1-20211217
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    env_file:
      - .env
    environment:
      - GRID_DEBUG=true

  chrome:
    depends_on:
      - hub
    image: selenium/node-chrome:4.1.1-20211217
    shm_size: 2gb
```

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
docker-compose up chrome
```

### Relevant log output

```shell
Attaching to nexia_development-chrome-1
nexia_development-chrome-1  | 2024-03-14 19:17:31,705 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
nexia_development-chrome-1  | 2024-03-14 19:17:31,709 INFO RPC interface 'supervisor' initialized
nexia_development-chrome-1  | 2024-03-14 19:17:31,710 CRIT Server 'unix_http_server' running without any HTTP authentication checking
nexia_development-chrome-1  | 2024-03-14 19:17:31,710 INFO supervisord started with pid 8
nexia_development-chrome-1  | 2024-03-14 19:17:32,714 INFO spawned: 'xvfb' with pid 9
nexia_development-chrome-1  | 2024-03-14 19:17:32,717 INFO spawned: 'vnc' with pid 10
nexia_development-chrome-1  | 2024-03-14 19:17:32,720 INFO spawned: 'novnc' with pid 11
nexia_development-chrome-1  | 2024-03-14 19:17:32,724 INFO spawned: 'selenium-node' with pid 12
nexia_development-chrome-1  | 2024-03-14 19:17:32,877 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
nexia_development-chrome-1  | 2024-03-14 19:17:33,468 INFO exited: novnc (terminated by SIGTRAP; not expected)
nexia_development-chrome-1  | Appending Selenium options: --session-timeout 300
nexia_development-chrome-1  | Appending Selenium options: --heartbeat-period 30
nexia_development-chrome-1  | Generating Selenium Config
nexia_development-chrome-1  | Configuring server...
nexia_development-chrome-1  | Setting up SE_NODE_HOST...
nexia_development-chrome-1  | Setting up SE_NODE_PORT...
nexia_development-chrome-1  | Setting up SE_NODE_GRID_URL...
nexia_development-chrome-1  | Tracing is disabled
nexia_development-chrome-1  | Selenium Grid Node configuration:
nexia_development-chrome-1  | 2024-03-14 19:17:33,847 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
nexia_development-chrome-1  | 2024-03-14 19:17:33,847 INFO success: vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
nexia_development-chrome-1  | [events]
nexia_development-chrome-1  | publish = "tcp://selenium-hub:4442"
nexia_development-chrome-1  | subscribe = "tcp://selenium-hub:4443"
nexia_development-chrome-1  |
nexia_development-chrome-1  | [node]
nexia_development-chrome-1  | session-timeout = "300"
nexia_development-chrome-1  | override-max-sessions = false
nexia_development-chrome-1  | detect-drivers = false
nexia_development-chrome-1  | drain-after-session-count = 0
nexia_development-chrome-1  | max-sessions = 1
nexia_development-chrome-1  |
nexia_development-chrome-1  | [[node.driver-configuration]]
nexia_development-chrome-1  | display-name = "chrome"
nexia_development-chrome-1  | stereotype = '{"browserName": "chrome", "browserVersion": "124.0", "platformName": "Linux", "goog:chromeOptions": {"binary": "/usr/bin/google-chrome"}}'
nexia_development-chrome-1  | max-sessions = 1
nexia_development-chrome-1  |
nexia_development-chrome-1  | Starting Selenium Grid Node...
nexia_development-chrome-1  | 2024-03-14 19:17:34,513 INFO spawned: 'novnc' with pid 86
nexia_development-chrome-1  | 2024-03-14 19:17:34,626 INFO exited: novnc (terminated by SIGTRAP; not expected)
nexia_development-chrome-1  | 19:17:35.573 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
nexia_development-chrome-1  | 2024-03-14 19:17:35,582 INFO exited: vnc (terminated by SIGTRAP; not expected)
nexia_development-chrome-1  | 19:17:35.591 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
nexia_development-chrome-1  | 2024-03-14 19:17:35,599 INFO spawned: 'vnc' with pid 121
nexia_development-chrome-1  | 19:17:35.875 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
nexia_development-chrome-1  | 19:17:36.001 INFO [UnboundZmqEventBus.<init>] - Sockets created
nexia_development-chrome-1  | 19:17:37.007 INFO [UnboundZmqEventBus.<init>] - Event bus ready
nexia_development-chrome-1  | 2024-03-14 19:17:37,008 INFO success: vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
nexia_development-chrome-1  | 2024-03-14 19:17:37,009 INFO spawned: 'novnc' with pid 146
nexia_development-chrome-1  | 2024-03-14 19:17:37,075 INFO exited: novnc (terminated by SIGTRAP; not expected)
nexia_development-chrome-1  | 19:17:37.345 INFO [NodeServer.createHandlers] - Reporting self as: http://172.18.0.3:5555/
nexia_development-chrome-1  | 19:17:37.376 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
nexia_development-chrome-1  | 19:17:37.485 INFO [NodeOptions.report] - Adding chrome for {"browserName": "chrome","browserVersion": "124.0","goog:chromeOptions": {"binary": "\u002fusr\u002fbin\u002fgoogle-chrome"},"platformName": "linux","se:noVncPort": 7900,"se:vncEnabled": true} 1 times
nexia_development-chrome-1  | 19:17:37.541 INFO [Node.<init>] - Binding additional locator mechanisms: relative
nexia_development-chrome-1  | 19:17:37.744 INFO [NodeServer$1.start] - Starting registration process for Node http://172.18.0.3:5555/
nexia_development-chrome-1  | 2024-03-14 19:17:37,745 INFO exited: vnc (terminated by SIGTRAP; not expected)
nexia_development-chrome-1  | 19:17:37.747 INFO [NodeServer.execute] - Started Selenium node 4.18.1 (revision b1d3319b48): http://172.18.0.3:5555/
nexia_development-chrome-1  | 2024-03-14 19:17:37,749 INFO spawned: 'vnc' with pid 161
nexia_development-chrome-1  | 19:17:37.781 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
nexia_development-chrome-1  | 19:17:38.041 INFO [NodeServer.lambda$createHandlers$2] - Node has been added
nexia_development-chrome-1  | 2024-03-14 19:17:39,348 INFO success: vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
nexia_development-chrome-1  | 2024-03-14 19:17:39,793 INFO exited: vnc (terminated by SIGTRAP; not expected)
nexia_development-chrome-1  | 2024-03-14 19:17:40,795 INFO spawned: 'vnc' with pid 189
nexia_development-chrome-1  | 2024-03-14 19:17:40,797 INFO spawned: 'novnc' with pid 190
nexia_development-chrome-1  | 2024-03-14 19:17:41,403 INFO exited: novnc (terminated by SIGTRAP; not expected)
nexia_development-chrome-1  | 2024-03-14 19:17:42,406 INFO success: vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
nexia_development-chrome-1  | 2024-03-14 19:17:42,406 INFO gave up: novnc entered FATAL state, too many start retries too quickly
nexia_development-chrome-1  | 2024-03-14 19:17:42,827 INFO exited: vnc (terminated by SIGTRAP; not expected)
nexia_development-chrome-1  | 2024-03-14 19:17:42,829 INFO spawned: 'vnc' with pid 215
nexia_development-chrome-1  | 2024-03-14 19:17:44,426 INFO success: vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
nexia_development-chrome-1  | 2024-03-14 19:17:44,798 INFO exited: vnc (terminated by SIGTRAP; not expected)
nexia_development-chrome-1  | 2024-03-14 19:17:45,802 INFO spawned: 'vnc' with pid 239
```
```


### Operating System

Mac OS Sonoma 14.4

### Docker Selenium version (image tag)

latest dev

### Selenium Grid chart version (chart version)

_No response_
