### ISSUE TITLE
[🐛 Bug]: ScaledObject errors out when ServiceName has been used - GKE

### ISSUE THREAD

**Issue by devqaio** [SeleniumHQ/docker-selenium#2231]
### What happened?

I have setup my Cluster in GKE. Attached are my Configs fro my cluser and selenium grid.

When I use the service name in my ScaledObject trigger, it doesn't instantiate the POD. However, if I use the ClusterIP directly, then only it works.

It should work with the service name as well unless I am missing anything. It adds the request to queue using the service name. Hence I am ruling out the connectivity issues with service name. However, it doesn't create a new node/pod that was suppossed to be spinned up by ScaledObject making the node available for execution.

![image](https://github.com/SeleniumHQ/docker-selenium/assets/10003447/d6d43336-f231-4eaf-8ba7-7c963c516405)
[selenium-grid-config.txt](https://github.com/SeleniumHQ/docker-selenium/files/15141210/selenium-grid-config.txt)

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
Added to description
```

### Relevant log output

```shell
Attached in Description
```

### Operating System

Kubernetes (GKE)

### Docker Selenium version (image tag)

4.20

### Selenium Grid chart version (chart version)

0.29

**Comment by VietND96** [comment]
How about if you try this config for the triggers as below?

```yaml
  triggers:
    - type: selenium-grid
      metadata:
        browserName: chrome
        sessionBrowserName: chrome
        unsafeSsl: 'true'
        url: 'http://selenium-hub-ci:4444/graphql'
```
