### ISSUE TITLE
set screen_width and screen_height doesn't seem to work

### ISSUE THREAD

**Issue by roydekleijn** [SeleniumHQ/docker-selenium#233]
Hi,

I like to set the width and height of my nodes. This is my docker-compose.yml file:

```
seleniumhub:
  image: selenium/hub
  ports:
    - 4444:4444
firefoxnode:
  image: selenium/node-firefox
  ports:
    - 5900
  links:
    - seleniumhub:hub
  environment:
     SCREEN_WIDTH: 1920
     SCREEN_HEIGHT: 1080
chromenode:
  image: selenium/node-chrome
  ports:
    - 5900
  links:
    - seleniumhub:hub
  environment:
     SCREEN_WIDTH: 1920
     SCREEN_HEIGHT: 1080
```

When I do: `docker-compose up --remove-orphans` and run my test (which prints the width and height).

```
driver.get("http://www.google.nl");
driver.manage().window().maximize();
System.out.println(driver.manage().window().getSize().width);
System.out.println(driver.manage().window().getSize().height);
```

I get:
width 1440
height 810

What can I do ?

Roy

**Comment by roydekleijn** [comment]
Any one?

**Comment by soniacepedano** [comment]
what do you want to do?

**Comment by roydekleijn** [comment]
Good question... I did some more experiments.

I set it to this:
```
  environment:
     SCREEN_WIDTH: 1920
     SCREEN_HEIGHT: 1080
```
In my script I maximize my window, however the output of driver.manage().window().getSize().width and driver.manage().window().getSize().height is:
width 1440
height 810


What could be the reason ? or am I missing something ?

**Comment by smccarthy** [comment]
I don't have docker setup on this machine yet, but what happens when you don't give the SCREEN_WIDTH or SCREEN_HEIGHT? Does it default to 1360x1020?

Maybe the maximize isn't working correctly in the docker container?

**Comment by ddavison** [comment]
I'm not able to reproduce.. using the latest `node-chrome` and `node-firefox` containers,

**docker-compose.yml**
```yaml
---
hub:
  image: selenium/hub
  ports:
    - 4444:4444

firefox:
  image: selenium/node-firefox
  links:
    - hub
  environment:
    SCREEN_WIDTH: 1200
    SCREEN_HEIGHT: 768

chrome:
  image: selenium/node-chrome
  links:
    - hub
  environment:
    SCREEN_WIDTH: 1200
    SCREEN_HEIGHT: 768
```

Using these parameters, I got: 

```
Chrome: #<struct Selenium::WebDriver::Dimension width=1050, height=748>
Firefox: #<struct Selenium::WebDriver::Dimension width=1080, height=691>
```

When I specified

```yaml
  ...
  environment:
    SCREEN_WIDTH: 800
    SCREEN_HEIGHT: 600
```

for both nodes, I got

```
Chrome: #<struct Selenium::WebDriver::Dimension width=780, height=580>
Firefox: #<struct Selenium::WebDriver::Dimension width=720, height=540>
```

besides the disparity of the browsers and their toolbars (the viewport is smaller in firefox because of the toolbars and address bar), everything looks normal.
