### ISSUE TITLE
cannot spin chrome node using docker-compose

### ISSUE THREAD

**Issue by bizmate** [SeleniumHQ/docker-selenium#240]
docker-compose orchestration is great for obvious reasons. However, the docker run instructions given in the README are not working when spinning the container from a docker-compose file.

Example in docker compose

```
version: '2'

services:
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium
    links:
      - selenium:hub
    command: bash -c "sleep 20 && /opt/bin/entry_point.sh"
  selenium:
    image: selenium/hub
    ports:
      - 4444
```

This fails with error 
```
vagrant@vagrant-ubuntu-trusty-64:/data$ docker-compose up
Creating network "data_default" with the default driver
Creating data_selenium_1
Creating data_chrome_1
Attaching to data_selenium_1, data_chrome_1
selenium_1  | starting selenium hub with configuration:
selenium_1  |
selenium_1  | {
selenium_1  |   "host": null,
selenium_1  |   "port": 4444,
selenium_1  |   "prioritizer": null,
selenium_1  |   "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
selenium_1  |   "throwOnCapabilityNotPresent": true,
selenium_1  |   "newSessionWaitTimeout": -1,
selenium_1  |   "jettyMaxThreads": -1,
selenium_1  |   "nodePolling": 5000,
selenium_1  |   "cleanUpCycle": 5000,
selenium_1  |   "timeout": 30000,
selenium_1  |   "browserTimeout": 0,
selenium_1  |   "maxSession": 5,
selenium_1  |   "unregisterIfStillDownAfter": 30000
selenium_1  | }
selenium_1  | 14:34:16.635 INFO - Launching Selenium Grid hub
selenium_1  | 2016-07-01 14:34:17.732:INFO::main: Logging initialized @1572ms
selenium_1  | 14:34:17.775 INFO - Will listen on 4444
selenium_1  | 14:34:17.898 INFO - Will listen on 4444
selenium_1  | 2016-07-01 14:34:17.906:INFO:osjs.Server:main: jetty-9.2.z-SNAPSHOT
selenium_1  | 2016-07-01 14:34:17.990:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@150c158{/,null,AVAILABLE}
selenium_1  | 2016-07-01 14:34:18.019:INFO:osjs.ServerConnector:main: Started ServerConnector@709a38e8{HTTP/1.1}{0.0.0.0:4444}
selenium_1  | 2016-07-01 14:34:18.020:INFO:osjs.Server:main: Started @1861ms
selenium_1  | 14:34:18.023 INFO - Nodes should register to http://172.18.0.2:4444/grid/register/
selenium_1  | 14:34:18.023 INFO - Selenium Grid hub is up and running
chrome_1    | Not linked with a running Hub container
data_chrome_1 exited with code 1
```

Any suggestions on how this could run through compose? I have also added a wait in the node entry point but it didnt make a difference as you can see.

**Comment by eroshenkoam** [comment]
here is workaround https://github.com/SeleniumHQ/docker-selenium/issues/133

**Comment by eroshenkoam** [comment]
```
version: '2'

networks:
  private:
    driver: bridge

services:
  hub:
    image: "selenium/hub:2.53.0"
    ports:
      - 4444:4444
    networks:
      - private

  chrome:
    image: "selenium/node-chrome:2.53.0"
    networks:
      - private
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub

  firefox:
    image: "selenium/node-firefox:2.53.0"
    networks:
      - private
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
```
