### ISSUE TITLE
[🐛 Bug]: Can only specify option --bind-host once

### ISSUE THREAD

**Issue by edison12a** [SeleniumHQ/docker-selenium#2448]
### What happened?

Docker compose:
```
  selenium-hub:
    image: selenium/hub:4.25.0-20240922
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      SE_GRID_MAX_SESSION: "15"
      SE_NODE_PORT: "5555"
      GRID_NEW_SESSION_WAIT_TIMEOUT: "30"
      SE_NODE_SESSION_TIMEOUT: "300"
      SE_GRID_SEASONING_REGISTERING_ATTEMPTS: "5"
      SE_GRID_SEASONING_REGISTERING_RETRY_INTERVAL: "5"
      SE_ENABLE_TRACING: "false"
      SE_OPTS: "--host selenium-hub --http-logs true --log-level FINEST --bind-host false "
    platform: linux/amd64  # Specify platform here
```

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
docker-compose up --force-recreate --remove-orphans --build
```

### Relevant log output

```shell
[+] Running 2/2
 ✔ Network bfloat-selenium-pod_default  Created                                                                                                                                                                0.0s 
 ✔ Container selenium-hub               Created                                                                                                                                                                0.0s 
Attaching to selenium-hub
selenium-hub  | 2024-10-30 18:41:12,887 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
selenium-hub  | 2024-10-30 18:41:12,890 INFO RPC interface 'supervisor' initialized
selenium-hub  | 2024-10-30 18:41:12,890 INFO supervisord started with pid 8
selenium-hub  | 2024-10-30 18:41:13,910 INFO spawned: 'selenium-grid-hub' with pid 9
selenium-hub  | Starting Selenium Grid Hub...
selenium-hub  | 2024-10-30 18:41:13,988 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub  | Appending Selenium options: --host selenium-hub --http-logs true --log-level FINEST --bind-host false 
selenium-hub  | Selenium option: --log-level already set in env variable SE_OPTS. Ignore new option: --log-level INFO
selenium-hub  | Selenium option: --http-logs already set in env variable SE_OPTS. Ignore new option: --http-logs false
selenium-hub  | Appending Selenium option: --structured-logs false
selenium-hub  | Appending Selenium option: --reject-unsupported-caps false
selenium-hub  | Appending Selenium option: --tracing false
selenium-hub  | Tracing is disabled
selenium-hub  | Can only specify option --bind-host once.
selenium-hub  | Usage: hub [options]
selenium-hub  |   Options:
selenium-hub  |     --allow-cors
selenium-hub  |       Whether the Selenium server should allow web browser connections from 
selenium-hub  |       any host
selenium-hub  |       Default: false
selenium-hub  |     --bind-bus

selenium-hub  | 2024-10-30 18:41:14,702 INFO exited: selenium-grid-hub (exit status 0; expected)
```

### Operating System

MacOS and Ubuntu

### Docker Selenium version (image tag)

hub:4.25.0-20240922
