### ISSUE TITLE
[🚀 Feature]: Allow multiple nodes of the same type in Helm configuration

### ISSUE THREAD

**Issue by adriannowak** [SeleniumHQ/docker-selenium#2456]
### Feature and motivation

Currently, we define browser nodes in the Helm configuration like this:
```yaml
        chromeNode:
          replicas: 3
          nodeMaxSessions: 3
        firefoxNode:
          enabled: false
        edgeNode:
          enabled: false
```
This setup is limited, as it doesn’t allow us to configure multiple versions of the same browser. 
To increase flexibility, I propose extending the configuration by using arrays:
```yaml
        chromeNodes:
         - replicas: 3
           extraEnvironmentVariables:
            - name: SE_NODE_STEREOTYPE
              value: '{"browserName":"chrome","platformName":"linux","app":"app1"}'
         - replicas: 3
           extraEnvironmentVariables:
            - name: SE_NODE_STEREOTYPE
              value: '{"browserName":"chrome","platformName":"linux","app":"app2"}'
```

With this pattern we can configure dedicated pool for apps, override configurations etc.

### Usage example

To test the UI of the same feature across different browser versions
