### ISSUE TITLE
[🐛 Bug]: Wrong firefox version in selenium/node-firefox images.

### ISSUE THREAD

**Issue by SergeyMokhov** [SeleniumHQ/docker-selenium#2457]
### What happened?

I pulled an image that was supposed to have Firefox 132, but it contains Firefox 134 Nightly.
Image I used was ` selenium/node-firefox:132.0-geckodriver-0.35` but on Dockerhub it has same image hash as all other "version 132" images. `cb0c87ccf175`
Other versions might be affected too.
![image](https://github.com/user-attachments/assets/70c5bafb-333b-4ab5-8bc8-ff21802b263d)

```yaml
services:
  firefox:
    image: selenium/node-firefox:132.0-geckodriver-0.35
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy
      firefox_video:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false
  firefox_video:
    image: selenium/video:ffmpeg-7.1-20241101
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_VIDEO_FILE_NAME=auto
      - SE_ENABLE_TRACING=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s
      start_interval: 1s
  selenium-hub:
    image: selenium/hub:4.26.0
    container_name: selenium-hub
    environment:
      - SE_ENABLE_TRACING=false
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:4444/status"]
      interval: 30s
      timeout: 2s
      retries: 2
      start_period: 10s
      start_interval: 1s
```

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
docker compose up
```

### Relevant log output

```shell
docker pulling the image...
```

### Operating System

macOS

### Docker Selenium version (image tag)

selenium/node-firefox:132.0-geckodriver-0.35
