### ISSUE TITLE
[🚀 Feature]: Use selenium hub with postgresql as external data store, and configured in helm

### ISSUE THREAD

**Issue by hussein-mimi** [SeleniumHQ/docker-selenium#2472]
### Feature and motivation

Selenium grid helm chart helps us to deploy selenium grid into our K8S cluster, but by default data is not persistent, so for any reason pod that running hub rebooted or deleted, all existing sessions in queue will be lost, also session-node map will be lost.

so from existing helm chart i can't deploy high available selenium hub with 2 pods, also i can't use external data store advanced feature out of the box.

So i suggest to support external data store in helm, by only add db settings in values.yml.

### Usage example

```yml
hub:
  backend_engine: postgres
  postgres:
    username: seluser
    password: seluser
    host: 10.10.2.4
    port: 5432
    ssl_cert:
```
