### ISSUE TITLE
Issues running selenium grid on Docker 1.12 swarm mode cluster

### ISSUE THREAD

**Issue by jalmansor** [SeleniumHQ/docker-selenium#255]
I reported the following issue to Docker while trying to get a selenium grid running on a new docker swarm mode cluster. I'm not sure if this is something you've tried doing yet or not, but any input would be much appreciated. I suspect it's a networking issue related to the hub port being exposed and then expecting communications to/from the Chrome nodes to go over the ingress network, but exposing 5555 for them now causes them all to appear as coming from the same VIP (which I'm gathering is expected behavior for the way they're handling service load balancing). 

[https://github.com/docker/docker/issues/25311](https://github.com/docker/docker/issues/25311)

**Comment by iamluc** [comment]
Using a normal Swarm (not swarm mode)
I launch my nodes like this:
```
    selenium:
        image: selenium/node-firefox-debug
        environment:
            HUB_PORT_4444_TCP_ADDR: "seleniumhub"
            HUB_PORT_4444_TCP_PORT: "4444"
        entrypoint: 'bash -c "REMOTE_HOST=\"http://$$HOSTNAME:5555\" /opt/bin/entry_point.sh"'
```

It fixes my problem with neworking. I hope it can help you.
