### ISSUE TITLE
node-chrome entry point breaks Docker Compose v2

### ISSUE THREAD

**Issue by leebenson** [SeleniumHQ/docker-selenium#258]
The node-chrome and node-firefox [entry_point.sh](https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeBase/entry_point.sh) rely on $HUB_PORT_4444_TCP_ADDR being available to connect to an upstream grid.

If using Docker Compose v2 config YAML, env vars are no longer populated by linked containers, so this always returns:

> Not linked with a running Hub container

Short-term workaround is something like this:

```
  selenium:
    image: selenium/hub:2.53.0
    links:
      - test_server
  chrome:
    image: selenium/node-chrome:2.53.0
    links:
      - selenium
    environment:
      - no_proxy=""
      - HUB_PORT_4444_TCP_ADDR=selenium
```

It might be a good idea to remove any assumptions about the environment altogether, and simply allow passing a variable like `SELENIUM` which points to a FQN with host/port.

We could always use the previous mechanism as a fall-back.
