### ISSUE TITLE
Creating multiple instance with docker-compose

### ISSUE THREAD

**Issue by macroking** [SeleniumHQ/docker-selenium#263]
I'm trying to spin up multiple chrome and firefox nodes with docker-compose and is working fine if all the containers are in the same machine.
docker-compose.yml file
```yaml
hub:
  image: selenium/hub
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox
  links:
    - hub
chrome:
  image: selenium/node-chrome
  links:
   - hub
```

I'm unable to find a way to link my selenium grid (Jenkins Not a container) which is running on a different server.

Is it something possible to do?

**Comment by ddavison** [comment]
if that is your docker-compose.yml file, then they will be running on the same docker host, and that should run just fine.

i just created a  docker-compose.yml with the following contents
```yaml
---
hub:
  image: selenium/hub:2.53.1
  ports:
    - "4444:4444"
nodeone:
  image: selenium/node-chrome:2.53.1
  links:
    - hub

nodetwo:
  image: selenium/node-chrome:2.53.1
  links:
    - hub 
```

and worked just fine.  if your hub is on a different server entirely, and not being run the docker-compose file, then you are able to specify the hub by specifying a couple env variables

```yaml
---
nodeone:
  image: selenium/node-chrome:2.53.1
  env:
    - HUB_PORT_4444_TCP_ADDR=10.0.0.x
    - HUB_PORT_4444_TCP_PORT=4444
nodetwo:
  image: selenium/node-chrome:2.53.1
    env:
    - HUB_PORT_4444_TCP_ADDR=10.0.0.x
    - HUB_PORT_4444_TCP_PORT=4444
```
