### ISSUE TITLE
[🚀 Feature]: Ability to configure OTLP endpoint to OTLP agent running on Node host as daemonset

### ISSUE THREAD

**Issue by amardeep2006** [SeleniumHQ/docker-selenium#2656]
### Feature and motivation

We have our observability collector agents running on the Kubernetes Nodes as daemonsets. The issue is that by default IP address for kubernetes node is not available to the pods. I am looking for a solution that can help me with this.
I could find out that we can inject the Node IP via helm chart like this 
```yaml
            - name: KUBERNETES_NODE_HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
```
How do i point the exporter endpoint to this env variable via config?
I am not sure following will work. Because I feel this should also be inject via Helm only .

```yaml
  - name: SE_OTEL_EXPORTER_ENDPOINT
    value: "http://$KUBERNETES_NODE_HOST_IP:4317"
```

I feel some changes are required to handle this.

### Usage example

Ability to export traces data to OTLP endpoint on Node host.
