### ISSUE TITLE
[🚀 Feature]: Add option to disable nginx.ingress.kubernetes.io/proxy-ssl-secret annotation in selenium chart

### ISSUE THREAD

**Issue by LluisCalm** [SeleniumHQ/docker-selenium#2720]
### Feature and motivation

The ingress resource created by the chart adds always the `nginx.ingress.kubernetes.io/proxy-ssl-secret` annotation which makes this ingress inaccessible by default if the tls secret is created, for example, by cert manager.

Code cample showing that the annotation is mandatory:
```
    {{- if not (empty .sslSecret) }}
nginx.ingress.kubernetes.io/proxy-ssl-secret: {{ tpl .sslSecret $ | quote }}
    {{- else if (empty $.Values.ingress.tls) }}
nginx.ingress.kubernetes.io/proxy-ssl-secret: {{ tpl (printf "%s/%s" $.Release.Namespace (include "seleniumGrid.tls.fullname" $)) $ | quote }}
    {{- else }}
nginx.ingress.kubernetes.io/proxy-ssl-secret: {{ tpl (printf "%s/%s" $.Release.Namespace (index $.Values.ingress.tls 0).secretName) $ | quote }}
    {{- end }}
```

I propose that if `.sslSecret `is empty, that annotation should not be added. This can be achieved in multiple ways, one could be by simply disabling the default value:

```
    {{- if not (empty .sslSecret) }}
nginx.ingress.kubernetes.io/proxy-ssl-secret: {{ tpl .sslSecret $ | quote }}
    {{- else if (empty $.Values.ingress.tls) }}
nginx.ingress.kubernetes.io/proxy-ssl-secret: {{ tpl (printf "%s/%s" $.Release.Namespace (include "seleniumGrid.tls.fullname" $)) $ | quote }}
    {{- end }}
```

### Usage example

I would use this feature to be able to create an ingress resource without the `nginx.ingress.kubernetes.io/proxy-ssl-secret` annotation.

**Comment by VietND96** [comment]
Hi, as my understanding, when you configure the ingress like
```yaml
ingress:
  hostname: selenium-grid.prod.domain.com
  tls:
    - secretName: my-external-tls-secret
      hosts:
        - selenium-grid.prod.domain.com
```
The secretName here will not pass to ingress annotation, right?

**Comment by LluisCalm** [comment]
The configuration you provided would work since you specify a `secretName`, and it could be a solution to the problem I was experimenting, thanks! But, if someone use cert manager and do not specify a `secretName` in the TLS config, cert manager will automatically create a secret for the ingress and the annotation would look like:
```yaml
nginx.ingress.kubernetes.io/proxy-ssl-secret: my-namespace/%!s(<nil>)
```

**Comment by VietND96** [comment]
Thanks for your input. So, below config should be considered as valid
```yaml
ingress:
  hostname: selenium-grid.prod.domain.com
  tls:
    - hosts:
        - selenium-grid.prod.domain.com
```
And template should deal with this case properly to avoid `nil` value
