### ISSUE TITLE
Node browser [ff and chrome] unable to resolve another containers host information

### ISSUE THREAD

**Issue by DavidTolley** [SeleniumHQ/docker-selenium#274]
Hello!
I've been trying to integrate this into our CI process, but I'm running into a bit of an issue. I'm using docker-compose, and I am unable to get the browser (both ff and chrome) to interact with my app which is running in another container. Here is my compose file where I have everything laid out:

```yaml
version: "2"
services:
  selenium-hub:
    image: selenium/hub
    networks:
      - pi_default
    ports:
      - 4444:4444
    external_links:
      - "app:pi.localhost.com"
      - "app:preview.localhost.com"
  chrome:
    image: selenium/node-chrome
    networks:
      - pi_default
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
    links:
      - "selenium-hub:hub"
    external_links:
      - "app:pi.localhost.com"
      - "app:preview.localhost.com"
  pardriver:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      PI_URL: "app"
    networks:
      - pi_default
    links:
      - "selenium-hub:hub"
    external_links:
      - "app:pi.localhost.com"
      - "app:preview.localhost.com"
      - "app:testdata.localhost.com"
networks:
  pi_default:
    external: true
```

When I use docker selenium grid, and access say an external site like google.com, everything works fine. When I run a command such as: docker-compose exec chrome wget -qO- http://pi.localhost.com/user/login | less everything is fine, I can also ping pi.localhost.com correctly from the chrome container - it correctly hits my running app in the app container, from the chrome node. However when the browser is used, i receive the error: ERR_NAME_NOT_RESOLVED

I've tried using extra_hosts to set the mapping up in /etc/hosts, but the same thing happens: ping and wget work, but not the browser.
