### ISSUE TITLE
Grid UI inaccessible during scale down event, slow unregister

### ISSUE THREAD

**Issue by mjgorman** [SeleniumHQ/docker-selenium#275]
Hello! Sticky issue. Running a hub + several node-chrome containers. Everything works great. Scaling up i get a new node available in ~12 seconds(most of that is orchestration overhead in Rancher).  

I am experiencing some issues when I test out shrinking the number of nodes. Reducing by 1 renders the grid console a ever loading page, never returning till browser timeout. This goes on for a few minutes.  If i am also trying to run things on the nodes it seems to still try and use that node that has been removed, causing timeouts and exceptions for 'No Route to host' on the webdriver in my app(python). 

As soon as the grid console loads again, the scaled down node is removed and all goes back to normal. Problem is obviously for that 2+ minute window I could have serious issues for running processes using the grid. 

I've tried setting GRID_BROWSER_TIMEOUT and GRID_TIMEOUT both to 3000, still same behavior. Anyway to solve this? Something else i can tweak on the hub or the nodes themselves to try and remove this behavior?

**Comment by eXorus** [comment]
Hello,

Don't use the lastest images it's not working with GRID_TIMEOUT and GRID_BROWSER_TIMEOUT.

I'm using images 2.50.0 and it's OK with this docker-compose.yml:

```
hub:
  image: selenium/hub:2.50.0
  ports:
    - "4446:4444"
  environment:
    - GRID_BROWSER_TIMEOUT=600000
    - GRID_TIMEOUT=600000
    - GRID_MAX_SESSION=6
    - GRID_CLEAN_UP_CYCLE=600000
    - GRID_UNREGISTER_IF_STILL_DOWN_AFTER=600000
firefox:
  image: selenium/node-firefox:2.50.0
  ports:
    - "5900"
  environment:
    - SCREEN_WIDTH=1920
    - SCREEN_HEIGHT=1080
  links:
    - hub

```

**Comment by mjgorman** [comment]
Thanks for the reply! I've tried swapping down the version 2.50.0 and I do see all the settings being applied to nodes, but I still get the non-responsive UI and timeout issues when requesting a node that is down. I've set all the timeouts really low, 5000, to try and see if that fixes it and still the same exact behavior. This is a bummer, makes it hard to rely on this if i'll be doing any scaling automatically down.

**Comment by eXorus** [comment]
I have the same issue I don't understand why.
I try with 2.53.0 it's work very well on my laptop but failed on the cloud.

**Comment by tommywo** [comment]
thats because nodes arent shutdown gracefully

**Comment by ddavison** [comment]
@eXorus that issue was actually fixed this past weekend, and newer versions have been released.  2.53.1 is stable now.  @mjgorman could you let me know if this still exists with the newest version?

**Comment by mjgorman** [comment]
Still have this problem on 2.53.1, browser just spins and spins on the hub grid console before it times out a few minutes later and removes the node.

**Comment by ddavison** [comment]
could you share your commands that you are using to run the hub and nodes?

**Comment by mjgorman** [comment]
docker-compose:
```
chrome:
  log_driver: syslog
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=chrome
  tty: true
  log_opt:
    syslog-address: tcp://xxxxx
    tag: selenium-chrome
  image: selenium/node-chrome:2.53.1
  links:
  - 'hub:'
  stdin_open: true
hub:
  ports:
  - 4444:4444/tcp
  environment:
    GRID_BROWSER_TIMEOUT: '0'
    GRID_TIMEOUT: '300000'
  log_driver: syslog
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt:
    tag: selenium-hub
    syslog-address: tcp://xxxx
  image: selenium/hub:2.53.1
  stdin_open: true
```
