### ISSUE TITLE
What happened to the config.json files and why are they no longer available?

### ISSUE THREAD

**Issue by testphreak** [SeleniumHQ/docker-selenium#296]
After a recent change, the config.json files are missing from node-chrome and node-firefox images. We use these files to automate certain workflows (see my comment [here](https://github.com/SeleniumHQ/docker-selenium/issues/248#issuecomment-252403312)) and this has caused our automation runs to fail. There is nothing in the release notes that point to this change.

It would be nice if a breaking change such as this one is communicated a few days in advance via a roadmap file or some other means. Is there some mailing list,  group, chat etc that users need to be part of so they're aware of the changes?

**Comment by ddavison** [comment]
see change note in the release: https://github.com/SeleniumHQ/docker-selenium/releases/tag/2.53.1-americium

also, this is one of the dangers of using the `latest` tag.  by using the latest tag, you have the danger of pulling in something that is less than ideal like this situation :)  

instead of mapping your own json file, just use the built-in functionality.

*docker-compose.yml*
```yaml
---
selhub:
  image: selenium/hub
  ports:
    - 4444:4444

firefox:
  image: selenium/node-firefox
  privileged: true
  ports:
    - 5900
  environment:
    NODE_MAX_INSTANCES: 3
    NODE_MAX_SESSION: 3
  links:
    - selhub:hub
```
