### ISSUE TITLE
REMOTE_HOST env var not available in 3.0.0

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [SeleniumHQ/docker-selenium#307]
## Meta -
Image(s):  selenium/node-firefox

Docker Version:  3.0.0-cerium

## Expected Behavior -
Setting REMOTE_HOST will configure the node to use a specific ip address:port to register into the selenium grid. 

## Actual Behavior -

Setting REMOTE_HOST causes this exception

```
firefox_1  | REMOTE_HOST variable is set, appending -remoteHost
firefox_1  | Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -remoteHost
firefox_1  | 	at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
firefox_1  | 	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
firefox_1  | 	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
firefox_1  | 	at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
firefox_1  | 	at org.openqa.grid.selenium.GridLauncherV3$3.setConfiguration(GridLauncherV3.java:257)
firefox_1  | 	at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:147)
firefox_1  | 	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:73)
firefox_1 exited with code 1
```

Example docker-compose file 

```
 version: '2'
 services:
   firefox:
     image: selenium/node-firefox:3.0.0-cerium
     ports:
      - "4444:4444"
     environment:
      - HUB_PORT_4444_TCP_PORT=4444
      - HUB_PORT_4444_TCP_ADDR=foo.com
      - REMOTE_HOST=bar.com:4444
```

**Comment by ddavison** [comment]
this looks like it's not specific to the docker containers. this option also isn't available in the generally downloaded `selenium-server-standalone-3.0.0.jar` file.  i'm investigating.

**Comment by ddavison** [comment]
ok, so `REMOTE_HOST` should actually not be used at all.  All it is, is an amalgam of the `-host` and `-port` variables.  Use these instead.  I'll update the dockerfile's to not be able to specify this parameter.

**Comment by chris-smith-zocdoc** [comment]
Thanks for looking into this @ddavison Are there environment variables for host and port already available?

**Comment by ddavison** [comment]
yes.

```yaml
...
environment:
  SE_OPTS: "-host <host> -port <port>"
```

**Comment by chris-smith-zocdoc** [comment]
I don't think those are the correct options @ddavison , I think the equivalents are `-host` and `-port`

From the docs 

```
-host <IP | hostname> specify the host name or IP. usually not needed and determined automatically. For exotic network configuration, network with VPN, specifying the host might be necessary.
```

Trying to set these from `SE_OPTS` doesn't seem to be working for me, I get this exception
```
docker-compose up
Recreating desktop_node1_1
Attaching to desktop_hub_1, desktop_node1_1
node1_1  | appending selenium options: "-host bar.com -port 4445"
node1_1  | Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '"-host' but no main parameter was defined
node1_1  |      at com.beust.jcommander.JCommander.getMainParameter(JCommander.java:914)
node1_1  |      at com.beust.jcommander.JCommander.parseValues(JCommander.java:759)
node1_1  |      at com.beust.jcommander.JCommander.parse(JCommander.java:282)
node1_1  |      at com.beust.jcommander.JCommander.parse(JCommander.java:265)
node1_1  |      at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
node1_1  |      at org.openqa.grid.selenium.GridLauncherV3$3.setConfiguration(GridLauncherV3.java:257)
node1_1  |      at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:147)
node1_1  |      at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:73)
desktop_node1_1 exited with code 1
```

For this compose file 


```
 version: '2'
 services:
   node1:
     image: selenium/node-firefox:3.0.0-cerium
     ports:
      - "4445:5555"
      - "4443:5900"
     environment: 
      - HUB_PORT_4444_TCP_ADDR=bar.com
      - HUB_PORT_4444_TCP_PORT=4444
      - SE_OPTS="-host bar.com -port 4445"
   hub:
     image: selenium/hub:3.0.0-cerium
     ports: 
      - "4444:4444"
```

**Comment by ddavison** [comment]
**For Nodes**...

You don't specify  `-host` and `-port`. only `-hubHost` and `-hubPort`

**For the Grid**...

You can specify `-host` and `-port` but not `-hubHost` and `-hubPort`

**Comment by testphreak** [comment]
@chris-smith-zocdoc  @ddavison still can't get it to work. Tried a couple of things with SE_OPTS.

Attempt 1: 
```
docker service create --network gridnet --endpoint-mode dnsrr --name nodes \
            --mount type=bind,source=/dev/shm,target=/dev/shm \
            -e HUB_PORT_4444_TCP_ADDR=hub -e HUB_PORT_4444_TCP_PORT=4444 -e NODE_MAX_INSTANCES=5 -e NODE_MAX_SESSION=5 \
            -e SE_OPTS="-hubHost $HOSTNAME" \
            --replicas 2 selenium/node-chrome:3.0.0-cerium
```

Attempt 2: 
```
docker service create --network gridnet --endpoint-mode dnsrr --name nodes \
            --mount type=bind,source=/dev/shm,target=/dev/shm \
            -e HUB_PORT_4444_TCP_ADDR=hub -e HUB_PORT_4444_TCP_PORT=4444 -e NODE_MAX_INSTANCES=5 -e NODE_MAX_SESSION=5 \
            --replicas 2 selenium/node-chrome:3.0.0-cerium bash -c 'HOSTIP=$(ip -4 addr show eth0 | grep -Po "inet \K[\d.]+") SE_OPTS="-hubHost $HOSTIP" /opt/bin/entry_point.sh'
```

**Comment by testphreak** [comment]
@ddavison This is how it looks like on the console page after setting up the grid in the 2 ways I specified above. See the connection refused error. The node should be connecting to 10.x.x.x (host ip address) instead of 172.x.x.x.

![image](https://cloud.githubusercontent.com/assets/10567800/19452904/b1c993bc-9467-11e6-9755-93cff167c6f0.png)

**Comment by chris-smith-zocdoc** [comment]
@ddavison I need to set the `-host` and `-port` for the nodes so that they report their locations correctly to the hub. My use case is running the containers inside of AWS ECS. ECS doesn't have a network overlay but does have docker port forwarding. Docker links don't work on ECS because the hub and nodes are running on separate hosts. 


Without setting these options, the nodes pick up the docker bridge network address which is incorrect. They need to be set to the EC2 instances IP and the forwarded port. Currently I'm getting the EC2 IP from the EC2 metadata api and have a statically assigned port forwarded. 

Setting `-host` and `-port` on the nodes does allow me to run on ECS, but so far I've been unable to get the 3.0.0 containers to set those options without modifying the container image.

**Comment by ddavison** [comment]
sorry, @chris-smith-zocdoc you're right.  You can specify `-host <host> -port <port>` in the `SE_OPTS` environment variable to start the node on a specific ip/host and port.

This worked for me in a docker-compose.yml

```yaml
---
hub:
  image: selenium/hub:3.0.0-dubnium
  ports:
    - 4444:4444
  
chrome:
  image: selenium/node-chrome:3.0.0-dubnium
  links:
    - hub
  environment:
    SE_OPTS: "-host something -port 5556"  # connected to grid as http://something:5556
```
