### ISSUE TITLE
Firefox webdriver gives "Insecure Connection" using HTTPS

### ISSUE THREAD

**Issue by Chaoste** [SeleniumHQ/docker-selenium#313]
## Meta - Images and versions

Docker-compose file:

```
...
selenium-hub:
  image: selenium/hub:3.0.0-dubnium
  ports:
    - "4444:4444"
  links:
    - superserver:mytargeturl.com

nodefirefox:
  image: selenium/node-firefox:3.0.0-dubnium
  ports:
    - 5900
  links:
    - selenium-hub:hub
    - superserver:mytargeturl.com

test:
  build: ./..
  dockerfile: dockerfiles/images/test
  links:
    - selenium-hub
    - nodefirefox
    - superserver:mytargeturl.com
```

Docker Version:  

```
docker-compose version 1.8.0, build f3628c7
```

Testing:
I'm having a node container ("test") and several other node containers running. I have a container "superserver" which is a nginx instance allowing only https access. In my integration tests I'm using nightwatch to execute tests using selenium.
## Expected Behavior

Example test:

```
client
  .url('https://mytargeturl.com')
  .waitForElementVisible('body', 5000)
  .getTitle((title) => {
    client.assert.equal(title, 'Expected title')
  })
```

If the site loads successfully it will be the expected title.
## Actual Behavior

I'll get the page title "Insecure Connection".

[This](http://stackoverflow.com/questions/38122777/firefox-insecure-channel-warning#comment63677967_38122777) comment on SO pointed out that I require a HTTPS access but the webpage itself is actually served via HTTP and firefox gives a warning for security reasons.
I wanted firefox to ignore this alert, so I found [this](http://stackoverflow.com/a/25063706/4816930) answer on SO which mentions the firefox option "accept_untrusted_certs". I've added this option to my nightwatch.json (test_settings.default.desiredCapabilitied.accept_untrusted_certs = true) - I tried camel case, too.
When I still got the "Insecure Connection" error I found out that it might be a problem of the firefox version (mentioned [here](http://stackoverflow.com/a/37868534/4816930)).
To achieve an older firefox version (currently its firefox 49 in node-firefox:3.0.0-dubnium) I switched to node-firefox:2.50.0 which uses firefox 44.

Is there anything I did wrong and the solution is easier than mine or is this the right way to open a webpage via HTTPS which serves content via HTTP .

I know this might be a problem with firefox and not selenium or webdriver but this problem was so hard to solve and maybe someone else runs into the some problem.
