### ISSUE TITLE
Not able to launch more than 1 browser session at a time on hub

### ISSUE THREAD

**Issue by finspin** [SeleniumHQ/docker-selenium#328]
I'm launching my selenium grid and chrome instances with the following docker-compose.yml but I'm not able to launch more than 1 chrome session at a time. Second session always waits for the first one to be completed. Is there any settings I'm missing here?

**docker-compose.yml**
```
seleniumhub:
  image: selenium/hub
  environment:
    - GRID_MAX_SESSION=5
    - GRID_BROWSER_TIMEOUT=100000
    - GRID_TIMEOUT=90000
    - GRID_NEW_SESSION_WAIT_TIMEOUT=300000
  ports:
    - 4444:4444

chromenode:
  image: selenium/node-chrome-debug
  ports:
    - 5900:5900
  environment:
    - NODE_MAX_INSTANCES=10
  links:
    - seleniumhub:hub
  volumes:
    - /dev/shm:/dev/shm
```

**grid config**
```
1 requests waiting for a slot to be free.
Capabilities [{count=1, browserName=chrome}]
Config for the hub :
browserTimeout : 100000
debug : false
help : false
jettyMaxThreads : -1
port : 4444
role : hub
timeout : 90000
cleanUpCycle : 5000
host : 172.17.0.2
maxSession : 5
hubConfig : /opt/selenium/config.json
capabilityMatcher : org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout : 300000
throwOnCapabilityNotPresent : true
Config details :
hub launched with : -browserTimeout 100000 -debug false -help false -jettyMaxThreads -1 -port 4444 -role hub -timeout 90000 -cleanUpCycle 5000 -host 172.17.0.2 -maxSession 5 -hubConfig /opt/selenium/config.json -capabilityMatcher org.openqa.grid.internal.utils.DefaultCapabilityMatcher -newSessionWaitTimeout 300000 -throwOnCapabilityNotPresent true
the final configuration comes from :
the default :
browserTimeout : 0
debug : false
help : false
jettyMaxThreads : -1
role : hub
timeout : 1800
cleanUpCycle : 5000
maxSession : 1
capabilityMatcher : org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout : -1
throwOnCapabilityNotPresent : true

updated with params :
browserTimeout : 100000
debug : false
help : false
jettyMaxThreads : -1
role : hub
timeout : 90000
cleanUpCycle : 5000
maxSession : 5
capabilityMatcher : org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout : 300000
throwOnCapabilityNotPresent : true
```
