### ISSUE TITLE
Could not rewrite NODE_MAX_INSTANCES nor NODE_MAX_SESSION via docker-compose?

### ISSUE THREAD

**Issue by pachamaker** [SeleniumHQ/docker-selenium#357]
## Meta -
Image(s):  node-chrome:2.53.0
Docker Version:  Docker version 1.11.2, build b9f10c9

I have docker-compose.yml
```
hub:
  image: selenium/hub:2.53.0
  ports:
    - "4444:4444"
  environment:
    - GRID_MAX_SESSION=5

chrome:
  image: selenium/node-chrome:2.53.0
  environment:
    - NODE_MAX_INSTANCES=10
    - NODE_MAX_SESSION=10
  links:
    - hub

```
I start docker-selenium-grid: docker-compose up -d
I see it in env of my container:
```
docker inspect f0aa77a19e84 | grep -A 14 Env
            "Env": [
                "NODE_MAX_INSTANCES=10",
                "NODE_MAX_SESSION=10",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive",
                "DEBCONF_NONINTERACTIVE_SEEN=true",
                "TZ=US/Pacific",
                "SCREEN_WIDTH=1360",
                "SCREEN_HEIGHT=1020",
                "SCREEN_DEPTH=24",
                "DISPLAY=:99.0",
                "CHROME_VERSION=google-chrome-stable",
                "CHROME_DRIVER_VERSION=2.23",
                "DBUS_SESSION_BUS_ADDRESS=/dev/null"
            ],
```

But did not see in chrome-node's config file. maxSession nor maxInstances did not rewrite.
Could you help me, where I did wrong? Thank you.

## Expected Behavior -
```
cat /opt/selenium/config.json
{
  "capabilities": [
    {
      "browserName": "*googlechrome",
      "maxInstances": 10,
      "seleniumProtocol": "Selenium"
    },
    {
      "browserName": "chrome",
      "maxInstances": 10,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "configuration": {
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 10,
    "port": 5555,
    "register": true,
    "registerCycle": 5000
  }
}
```
## Actual Behavior -
```
cat /opt/selenium/config.json
{
  "capabilities": [
    {
      "browserName": "*googlechrome",
      "maxInstances": 1,
      "seleniumProtocol": "Selenium"
    },
    {
      "browserName": "chrome",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "configuration": {
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 1,
    "port": 5555,
    "register": true,
    "registerCycle": 5000
  }
}
```

**Comment by ddavison** [comment]
that functionality was released first in [2.53.1-americium](https://github.com/SeleniumHQ/docker-selenium/commit/e423b4b9557891c9d2791c0327a408f793b10bf0).  when releasing americium, we didn't have the fleshed out release process, so the image version you have "2.53.1" doesn't have that functionality to add `"NODE_MAX_INSTANCES"` and such.  You can get this functionality by using the version `2.53.1-americium` or `2.53.1-beryllium` whichever you wish.

**Comment by thomas-lee** [comment]
I have tried the similar things using the latest docker images, it happens too.

```
selenium/node-firefox-debug                                            latest              a1dbf5f50ed2        7 days ago          733 MB
selenium/node-chrome-debug                                             latest              3ccba7094ae9        7 days ago          939 MB
selenium/node-firefox                                                  latest              76693a8995ed        7 days ago          672 MB
```

```
selenium-hub:
  image: selenium/hub
  environment:
    - GRID_MAX_SESSION=5
  ports:
    - "4444:4444"

chrome:
  image: selenium/node-chrome-debug
  links:
    - selenium-hub:hub
  ports:
    - "7000:5900"
  environment:
    - NODE_MAX_INSTANCES=5
    - NODE_MAX_SESSION=5
  volumes:
    - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
```

In the /opt/selenium/config.json
```
seluser@1abb06820c99:/opt/selenium$ cat config.json
{
  "capabilities": [
    {
      "version": "60.0.3112.113",
      "browserName": "chrome",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver",
      "applicationName": ""
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 1,
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "nodePolling": 5000,
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2
}
seluser@1abb06820c99:/opt/selenium$ cat config.json
{
  "capabilities": [
    {
      "version": "60.0.3112.113",
      "browserName": "chrome",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver",
      "applicationName": ""
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 1,
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "nodePolling": 5000,
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2
}
```
