### ISSUE TITLE
Multiple requests within one second do not work - help request

### ISSUE THREAD

**Issue by ScreamingDev** [SeleniumHQ/docker-selenium#360]
## Meta -
Image(s):  
node-chrome & hub & standalone-firefox
Docker Version:  
1.12.5

As I don't find any other way this ticket shall be a help request to debug
a problem.

Question is:

- What is failing?
- Am I stuck in a deadlock?
- How do I release requests when the client decides to disconnect (due to timeout after 30s)?

Hint:

- There are some fallbacks to quit the browser session.
- There is none to close the connection to the HUB. - Didn't find anythin about it.
- The more worker the more problems:
  - 1 worker successfully does his job
  - 2 worker fail at a 20% rate.
  - 4 worker fail at a 80% rate.

## Expected Behavior -

Server "Manager" has 8 processes running, reading configs and asking the hub to open a URL (nothing more by now).
Server "Selenium" has Docker running with the Hub using `docker-compose scale chrome=16 firefox=16`.

When I fire 10 configs on the manager, then it shall just do his job.
The Manager should ask Selenium for opening a URL and within the hub some browser shall open the URL.

## Actual Behavior -

This fails while creating a new session in the hub.
When I have 8 worker on the "Manager" side then the Hub refuses to work correctly. Maybe and only sometimes one session is successful.
Otherwise I see this:

```
hub_1      | 08:08:15.904 INFO - Got a request to create a new session: Capabilities [{browserName=chrome, chromeOptions={binary=}, platform=ANY}]
hub_1      | 08:08:16.130 INFO - Got a request to create a new session: Capabilities [{browserName=chrome, chromeOptions={binary=}, platform=ANY}]
hub_1      | 08:08:16.878 INFO - Got a request to create a new session: Capabilities [{browserName=chrome, chromeOptions={binary=}, platform=ANY}]
hub_1      | 08:08:17.285 INFO - Got a request to create a new session: Capabilities [{browserName=chrome, chromeOptions={binary=}, platform=ANY}]
hub_1      | 08:08:47.367 INFO - Got a request to create a new session: Capabilities [{browserName=chrome, chromeOptions={binary=}, platform=ANY}]
hub_1      | 08:08:47.491 INFO - Got a request to create a new session: Capabilities [{browserName=chrome, chromeOptions={binary=}, platform=ANY}]
hub_1      | 08:08:48.692 INFO - Got a request to create a new session: Capabilities [{browserName=chrome, chromeOptions={binary=}, platform=ANY}]
hub_1      | 08:08:48.835 INFO - Got a request to create a new session: Capabilities [{browserName=chrome, chromeOptions={binary=}, platform=ANY}]
hub_1      | 08:08:48.991 INFO - Got a request to create a new session: Capabilities [{browserName=chrome, chromeOptions={binary=}, pl
```

Over and over again. The "Manager" or each worker has a timeout after 30 seconds.
Trying again 30 seconds later for at most 3 times.

This is the docker-compose.yml config:

```
hub:
  image: selenium/hub
  ports:
    - "4444:4444"
  environment:
    # defaults: https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/Dockerfile.txt
    # description: http://stackoverflow.com/a/34438747/1494794
    # wait for new session (default: -1)
    - GRID_NEW_SESSION_WAIT_TIMEOUT=10
    # wait for client until releasing browser (default: 30000ms)
    - GRID_TIMEOUT=10000
    # The timeout in seconds a browser can hang (default: 0)
    - GRID_BROWSER_TIMEOUT=10000
firefox:
  image: selenium/node-firefox
  links:
    - hub
chrome:
  image: selenium/node-chrome
  links:
    - hub
```

As you can see I played with some constants.
