### ISSUE TITLE
Firefox has problems / ipc_channel_posix

### ISSUE THREAD

**Issue by ScreamingDev** [SeleniumHQ/docker-selenium#388]
## Meta -
Image(s):  
- hub
- node-chrome
- node-firefox

Docker Version:  
1.12.6
OS: 
Ubuntu 15.10

## Expected Behavior -

Firefox opens website.

## Actual Behavior -

```
firefox_1    | 13:29:31.484 INFO - Executing: [get: http://mike-pretzlaw.de])
firefox_1    | [Parent 119] WARNING: pipe error (55): Connection reset by peer: file /builds/slave/m-rel-l64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 323
firefox_1    | [Parent 119] WARNING: pipe error: Broken pipe: file /builds/slave/m-rel-l64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 687
firefox_1    | [Parent 119] WARNING: pipe error (48): Connection reset by peer: file /builds/slave/m-rel-l64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 323
firefox_1    | [Parent 119] WARNING: pipe error (45): Connection reset by peer: file /builds/slave/m-rel-l64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 323
```

**Comment by ddavison** [comment]
we'll need a little more information before we can see what exactly is going wrong here.  can you provide a little more information on your image versions you're using, your docker-compose.yml file, and possibly the relevant section of your test you are using to create the sessions

e.g.: `FirefoxDriver driver = new FirefoxDriver()`..

**Comment by brandomr** [comment]
@sourcerer-mike did you ever resolve this? I'm getting the same thing.

**Comment by peterstory** [comment]
I am also getting these errors. Here is my compose file, and my configuration details:

Image(s):  `selenium/node-phantomjs:3.3` and `selenium/hub:3.3`
Docker Version:  17.03.1-ce-mac5 (16048)
OS: macOS Sierra

My compose file:
```
version: '2'
services:
  selenium-hub:
    image: "selenium/hub:3.3"
    ports:
      - "127.0.0.1:4444:4444"
    restart: always
    environment:
      # Reclaims resources if download code crashes
      GRID_TIMEOUT: 30
      # Needed in case Firefox tries to update itself...
      GRID_BROWSER_TIMEOUT: 60
  ff1:
    image: "selenium/node-firefox:3.3"
    links:
      - "selenium-hub:hub"
    restart: always
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
  ff2:
    image: "selenium/node-firefox:3.3"
    links:
      - "selenium-hub:hub"
    restart: always
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
```

And my error messages:
```
selenium-hub_1  | 18:52:24.422 INFO - Got a request to create a new session: Capabilities [{marionette=true, acceptInsecureCerts=true, browserName=firefox, javascriptEnabled=true, version=, platform=ANY}]
selenium-hub_1  | 18:52:24.423 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, browserName=firefox, maxInstances=1, version=52.0.2, applicationName=, platform=LINUX}
ff1_1           | 18:52:24.425 INFO - Executing: [new session: Capabilities [{marionette=true, acceptInsecureCerts=true, browserName=firefox, javascriptEnabled=true, version=, platform=ANY}]])
ff1_1           | 18:52:24.427 INFO - Creating a new session for Capabilities [{marionette=true, acceptInsecureCerts=true, browserName=firefox, javascriptEnabled=true, version=, platform=ANY}]
ff1_1           | 1492541544453	geckodriver	INFO	Listening on 127.0.0.1:20643
ff1_1           | 1492541544518	mozprofile::profile	INFO	Using profile path /tmp/rust_mozprofile.KZ7U81MsaePK
ff1_1           | 1492541544520	geckodriver::marionette	INFO	Starting browser /usr/bin/firefox with args []
ff1_1           | 1492541544524	geckodriver::marionette	INFO	Connecting to Marionette on localhost:39605
ff1_1           | 1492541545276	Marionette	INFO	Listening on port 39605
ff1_1           | 1492541545525	Marionette	WARN	TLS certificate errors will be ignored for this session
ff1_1           | 18:52:26.762 INFO - Detected dialect: W3C
ff1_1           | 18:52:26.764 INFO - Done: [new session: Capabilities [{marionette=true, acceptInsecureCerts=true, browserName=firefox, javascriptEnabled=true, version=, platform=ANY}]]
ff1_1           | 18:52:26.769 INFO - Executing: [page load wait: 15000])
ff1_1           | 18:52:26.774 INFO - Done: [page load wait: 15000]
ff1_1           | 18:52:26.779 INFO - Executing: [get: http://www.frojoapps.com/privacy-policy])
ff1_1           | 18:52:28.370 INFO - Done: [get: http://www.frojoapps.com/privacy-policy]
ff1_1           | 18:52:28.375 INFO - Executing: [get page source])
ff1_1           | 18:52:28.388 INFO - Done: [get page source]
ff1_1           | 18:52:28.393 INFO - Executing: [get current url])
ff1_1           | [Parent 12282] WARNING: pipe error (55): Connection reset by peer: file /builds/slave/m-rel-l64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322
ff1_1           | [Parent 12282] WARNING: pipe error (48): Connection reset by peer: file /builds/slave/m-rel-l64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322
ff1_1           | 
ff1_1           | ###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0085,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
ff1_1           | 
```
