### ISSUE TITLE
Unknown error: session deleted because of page crash

### ISSUE THREAD

**Issue by lasotaartur** [SeleniumHQ/docker-selenium#431]
I have error while I'm running many behat scenarios. I'm using selenium/standalone-chrome:3.0.

**docker-compose.yml**
```
version: '2'
services:
  web:
    image: myimagewithphp
    links:
      - selenium
  selenium:
    image: selenium/standalone-chrome:3.0
    ports:
      - "4444:4444"
    environment:
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 1g
```

**Error**
```unknown error: session deleted because of page crash
      from unknown error: cannot determine loading status
      from tab crashed
        (Session info: chrome=56.0.2924.87)
        (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.9.16-coreos-r1 x86_64) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 934 milliseconds
      Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
      System info: host: 'c6e76c6d7648', ip: '172.19.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.16-coreos-r1', java.version: '1.8.0_121'
      Driver info: org.openqa.selenium.chrome.ChromeDriver
      Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320), userDataDir=/tmp/.org.chromium.Chromium.1vOvfW}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=56.0.2924.87, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
      Session ID: adfecf1949130acc353224ee3acfa2eb
      *** Element info: {Using=xpath, value=//html/descendant-or-self::*[@id = 'sylius_product_translations_pl_PL_slug']} (WebDriver\Exception\UnknownError)```
