### ISSUE TITLE
Unable to pass `-firefoxProfileTemplate` via SE_OPTS to standalone-selenium-firefox

### ISSUE THREAD

**Issue by dmitrygusev** [SeleniumHQ/docker-selenium#489]
## Meta -
Image(s): 
standalone-firefox-debug

Docker-Selenium Image Version(s):  
2.53.1-beryllium

OS: 
macOS Sierra 10.12.4

## Docker compose configuration -
```yml
version: '2.1'
services:

    selenium:
      image: selenium/standalone-firefox-debug:2.53.1-beryllium
      ports:
        - 4444 # Selenium server
#        - 5900 # VNC for `standalone-firefox-debug`
      volumes:
        # Firefox profile templates dir for self-signed certificates
        - ${SELENIUM_DATA}:/data:ro
      environment:
        # https://github.com/SeleniumHQ/docker-selenium/issues/227
        no_proxy: localhost
        # There's a bug that prevents passing these options in debug mode,
        # with `standalone-firefox-debug` image
        SE_OPTS: "-firefoxProfileTemplate /data/${FF_PROFILE_TEMPLATE_DIR}"
```

## Expected Behavior -
`SE_OPTS` environment variable acknowledged and consumed by selenium.

## Actual Behavior -
Container fails to start with the following error in docker logs:
```
$ docker logs -f selenium_1
appending selenium options: -firefoxProfileTemplate /data/build/test/conf/ff_profile_template_filtered
-bash: /data/build/test/conf/ff_profile_template_filtered: Is a directory
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
```

The same configuration works as expected with `standalone-firefox`.

I suspect the error is somewhere in the `entry_point.sh` where some pre-processing of environment variables is happening: https://github.com/SeleniumHQ/docker-selenium/blob/2.53.1-beryllium/StandaloneDebug/entry_point.sh#L21-L29
