### ISSUE TITLE
Cannot connect to docker.for.mac.localhost

### ISSUE THREAD

**Issue by alxlu** [SeleniumHQ/docker-selenium#511]
## Meta -
Image(s):  
node-chrome(-debug)
Docker-Selenium Image Version(s):  
latest

OS: 
macOS

## Expected Behavior -
Navigating to `docker.for.mac.localhost:PORT` on Google Chrome [will resolve to the internal IP used by the host](https://docs.docker.com/docker-for-mac/networking/).

## Actual Behavior -
`docker.for.mac.localhost refused to connect.`
If I connect to the container with VNC and run wget docker.for.mac.localhost:8080, it's able to successfully resolve the IP and download the file. It also seems to be working properly on node-firefox.

**Comment by ddavison** [comment]
could we see the command you are using / script that you're using to run against that uri?

**Comment by alxlu** [comment]
Sure! I'm running my tests with `webdriver.io`, and just navigating to it using
```javascript
browser.url(`${URL}/upload`);
// URL is passed in as an env variable--in this case pointing to
// http://docker.for.mac.localhost:8080
```

Also, the issue can be reproduced by using the config below, VNCing into them and then manually navigating to the URL.

`docker-compose.yml`
```yaml
selenium-hub:
  image: selenium/hub
  ports:
    - "4444:4444"
chrome:
    image: selenium/node-chrome-debug
    ports:
      - "9000:5900"
    links:
      - selenium-hub:hub
firefox:
    image: selenium/node-firefox-debug
    ports:
      - "9001:5900"
    links:
      - selenium-hub:hub
```
You can start any kind local web server on the host (e.g. `python -m SimpleHTTPServer` in any directory, then VNC into both the Firefox and Chrome containers and launch their respective browsers and manually navigate them to `http://docker.for.mac.localhost:8000`

Firefox navigates to it properly, but Chrome does not

![screen shot 2017-06-30 at 2 57 32 pm](https://user-images.githubusercontent.com/3271834/27755435-87272032-5da4-11e7-86ed-2aeadbb1c944.png)
