### ISSUE TITLE
How to allow to accept insecure certificates from the config?

### ISSUE THREAD

**Issue by Krzysiaczek-at-theFoundry** [SeleniumHQ/docker-selenium#518]
## Meta -
Image(s):  selenium/standalone-firefox-debug 
Docker-Selenium Image Version(s):  latest, 3.4.0-dysprosium
OS: OSX Sierra
## Expected Behavior
According to closed ticket #313 there should be no more issue with Insecure Connection when accessing HTTPS with self-signed certificate
## Actual Behavior
Any attempt to connect the site ends up with the warning: 

> Your connection is not secure
> The owner of 172.19.0.1 has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
> 

I was using another docker image from elsewhere with Firefox 45 which didn't produce such warning.

I'm using Behat test. As soon as it tries to open the page the error is thrown:
```
bin/behat -p local features/homepage.feature
@blackbox
Feature: homepage
  Check subscription purchase process

  Scenario:                           # features/homepage.feature:5
    Given I am on "homepage"          # FeatureContext::visit()
      Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
      System info: host: '84aaa2dfcb3c', ip: '172.18.0.5', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.31-moby', java.version: '1.8.0_131'
      Driver info: org.openqa.selenium.firefox.FirefoxDriver
      Capabilities [{moz:profile=/tmp/rust_mozprofile.xMWPfWyr2LWV, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0, platformVersion=4.9.31-moby, moz:processID=446.0, browserName=firefox, javascriptEnabled=true, platformName=linux}]
      Session ID: 36b39433-474b-43ec-91d5-6e9114b619f6 (WebDriver\Exception\UnknownError)

```
Is there a way to enable this acceptInsecureCerts=true?
Either from Behat yaml config file or docker-compose.yml file ideally?

I've tried to add this to .env file 
`ACCEPT_INSECURE_CERTS=1`
but no luck either.

P.S.
I've tried to post into ticket #313 but as is has got closed status decided to raise the new case.

**Comment by lmtierney** [comment]
`acceptInsecureCerts` is a capability that needs to be passed upon driver instantiation, you would need to do this somehow through Behat. You will need to check with the Behat people on how to do this as it is not officially supported by Selenium

**Comment by Krzysiaczek-at-theFoundry** [comment]
Thanks for the answer, but wouldn't it be possible to add it during compilation process? into a Docker file to build the image on my own? 

I was hoping such option is possible but hidden somewhere similar to this:
PHANTOMJS_OPTS="--ignore-ssl-errors=true"

**Comment by lmtierney** [comment]
Afaik, the only way to build it into the container would be to set that setting within the default Firefox profile itself which I wouldn't know how to go about doing.. @diemol ?

**Comment by fluentwait** [comment]
Hi,
I'm also having similar issue, even though I have set capability to ignore errors but still its does not work with 'docker-compose' setup. But if I starts individual containers with 'docker' command then it's work perfectly. 

Docker Compose File
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.4.0-einsteinium
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.4.0-einsteinium
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  firefox:
    image: selenium/node-firefox:3.4.0-einsteinium
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444

**Comment by Krzysiaczek-at-theFoundry** [comment]
For me, it was OK to switch to chrome. All certificate issues are being ignored now

```
  selenium:
    # image: selenium/standalone-firefox-debug:3.4.0-dysprosium
    image: selenium/standalone-chrome-debug
    ports:
      - "4444"
      - "5900"
```

I thought at first that maybe it was made due to ineffective changes in Behat 
```
default:
  extensions:
    Behat\MinkExtension:
      browser_name: chrome
      selenium2:
        # capabilities: { "browser": "chrome", "acceptSslCerts": true}
        wd_host: http://selenium:4444/wd/hub
      goutte: ~
      default_session: selenium2
      javascript_session: selenium2
```
but it seems that it doesn't make any difference as Chrome ignores certificates even when this line is commented out in Behat settings.

Other than this I also had to add some wait steps in Behat tests when the page is changed (e.g. When I follow link ...) as with Chrome in most cases it fails - doesn' wait for the page to load unlike it did with Firefox.

**Comment by joejoseph00** [comment]
I too am running this selenium docker image, when I try to add "acceptInsecureCerts" to the behat.yml config file 'capabilities' section for selenium2, try running behat
get the following message:

In ArrayNode.php line 319:

  Unrecognized options "acceptInsecureCerts" under "testwork.mink.sessions.my_session.selenium2.capabilities"

Unfortunately switching to Chrome does not allow me to test our apps for firefox compatibility.

It's been a real grind to even get this far with the docker and ci configuration.  Wondering what the easiest way to use acceptInsecureCerts is.

I'll keep digging and if I find something I'll post it back here.

**Comment by joejoseph00** [comment]
one clue: 
find -name ArrayNode.php
./vendor/symfony/config/Definition/ArrayNode.php
./behat/vendor/symfony/config/Definition/ArrayNode.php
comes from symfony.

**Comment by joejoseph00** [comment]
Ok, I pretty much figured out a better way.

For those using behat /selenium with firefox
and you want acceptInsecureCerts to be used

for some reason this setting is not accepted in the behat.yml , 
get this error
In ArrayNode.php line 319:

  Unrecognized option "acceptInsecureCerts" under "testwork.mink.sessions.selenium2.selenium2.capabilities"

The solution for those using php/behat/selenium/firefox and you are not using gecko (might work with gecko too, not sure, confused a bit about the number of drivers available) 
for me I had to to patch the `vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php`

add this code at the beginning of the constructor  public function __construct(....stuff
right after open {
(approximately line 77)
```
         if ($browserName == 'firefox') {
           $acceptInsecureCerts = array('acceptInsecureCerts' => TRUE);
           $desiredCapabilities = array_merge($acceptInsecureCerts, $desiredCapabilities);
           var_dump($desiredCapabilities, true);
         }
```

**Comment by joejoseph00** [comment]
here's what the patch would look like
diff --git a/behat/mink-selenium2-driver/src/Selenium2Driver.php b/behat/mink-selenium2-driver/src/Selenium2Driver.php
index b0d7ca7..4503b59 100755
--- a/behat/mink-selenium2-driver/src/Selenium2Driver.php
+++ b/behat/mink-selenium2-driver/src/Selenium2Driver.php
@@ -74,6 +74,11 @@ class Selenium2Driver extends CoreDriver
      */
     public function __construct($browserName = 'firefox', $desiredCapabilities = null, $wdHost = 'http://localhost:4444/wd/hub')
     {
+        if ($browserName == 'firefox') {
+          $acceptInsecureCerts = array('acceptInsecureCerts' => TRUE);
+          $desiredCapabilities = array_merge($acceptInsecureCerts, $desiredCapabilities);
+          //var_dump($desiredCapabilities, true);
+        }
         $this->setBrowserName($browserName);
         $this->setDesiredCapabilities($desiredCapabilities);
         $this->setWebDriver(new WebDriver($wdHost));

**Comment by joejoseph00** [comment]
and for IE11 , here is another way to do it from FeatureContext.php

```
  public function visit($page)
  {
      $this->visitPath($page);
      try {
        $driver = $this->getSession()->getDriver();
        $driver->executeScript("javascript:try {document.getElementById('overridelink').click();} catch (err) {console.log('probably cert warn already accepted');}");
      }
        // rethrow it
        throw $e;
      }
  }

```

**Comment by seyfer** [comment]
@joejoseph00 thanks
have you created PR in `mink-selenium2-driver`? was it merged?

**Comment by joejoseph00** [comment]
No I didn't make a pull request for that.

**Comment by karthik101** [comment]
I'm looking if there is an env to allow insecure urls, What env should i be passing to docker to make this work ?

**Comment by joejoseph00** [comment]
what browser?  I found this Chromium docker version to work the best for us:

selenium/standalone-chrome-debug:3.5.3-boron

behat.yml below:
```
qachrome:
  suites:
    default:
      contexts:
        - FeatureContext:
            parameters:
                base_url: "https://DOMAIN-NAME-HERE"
  extensions:
    Behat\MinkExtension:
      default_session: selenium2
      base_url: "https://DOMAIN-NAME-HERE"
      goutte: ~
      javascript_session: selenium2
      browser_name: chrome
      selenium2:
        wd_host: http://chrome:4444/wd/hub
        capabilities: {"browser": "chrome", "marionette": true}
      base_url: "https://DOMAIN-NAME-HERE"
      sessions:
        my_session:
           selenium2:
             wd_host: http://chrome:4444/wd/hub
             capabilities: {"browser": "chrome", "version": "*", "marionette": true}
    Lakion\Behat\MinkDebugExtension:
      directory: /tmp/debug-chrome
```


and launched like:
vendor/bin/behat --verbose -p qachrome features
