### ISSUE TITLE
selenium docker containers are slow on Kubernetes

### ISSUE THREAD

**Issue by bdshibly** [SeleniumHQ/docker-selenium#527]
We deployed selenium hub and chrome debug container in kubernetes cluster. We are using m4.xlarge for kubernetes nodes. Only selenium containers have been deployed on the cluster. But it is performing slowly. Here are out deployment scripts 

Selenium Hub:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: selenium-hub-debug
  namespace: selenium
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: selenium-hub-debug
        environment: prod
        department: qa
    spec:
      containers:
      - name: selenium-hub-debug
        image:  selenium/hub:2.53.1
        ports:
          - containerPort: 4444
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1"
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
      nodeSelector:
        selenium: grid
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
```
Selenium chrome grid

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: selenium-node-chrome-debug-1
  namespace: selenium
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: selenium-node-chrome-debug-1
        environment: prod
        department: qa
    spec:
      containers:
      - name: selenium-node-chrome-debug-1
        image:  selenium/node-chrome-debug:2.53.1
        ports:
          - name: chrome-debug
            containerPort: 5900
        resources:
          limits:
            memory: "1000Mi"
            cpu: "3"
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: HUB_PORT_4444_TCP_ADDR
            value: "selenium-hub-debug"
          - name: HUB_PORT_4444_TCP_PORT
            value: "4444"
          - name: NODE_MAX_INSTANCES
            value: "5"
          - name: NODE_MAX_SESSION
            value: "5"
      nodeSelector:
        selenium: node
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
```

Any help will be appreciated. 

Cheers
Ferdous Shibly
