### ISSUE TITLE
Chrome does not respect http proxy environment variables

### ISSUE THREAD

**Issue by tnguyen14** [SeleniumHQ/docker-selenium#537]
## Meta -
Image(s):  
node-chrome, node-chrome-debug
Docker-Selenium Image Version(s):  
3.4
OS: 
RHEL7.3

Chrome does not respect `http_proxy`, `https_proxy` and `no_proxy` environment variables that are set on the docker image. If these properties are passed to webdriver settings, chrome does respect them however.

I first asked about this in #478.

**Comment by diemol** [comment]
Hi @tnguyen14,

Can you please share the docker command you are using to start the images?
How are you able to see that those env vars are not respected?

**Comment by AndreSteenbergen** [comment]
Latest version actually does. I have spun up 2 azure machines, one with squid proxy, one without. Following that I created 2 nodes with different applicationName (NoProxy and WithProxy). After which I created a test console app, To first browse to https://whatismyipaddress.com/ and create a screenshot. Both screenshots showed a different ip address.

these are working settings (copy pasted from rancher)

![image](https://user-images.githubusercontent.com/7676790/32413864-8f44d608-c21a-11e7-9685-c25207a9fd89.png)

**Comment by AndreSteenbergen** [comment]
Without proxy:
![image](https://user-images.githubusercontent.com/7676790/32413990-13f83794-c21d-11e7-80b8-ab92510f8a4b.png)


With Proxy
![image](https://user-images.githubusercontent.com/7676790/32413983-edef8c3c-c21c-11e7-8499-e9bd4482fd4a.png)

**Comment by AndreSteenbergen** [comment]
I actually don't know which are the correct env variables, with or without CAPS ...

**Comment by AndreSteenbergen** [comment]
Test script: (c#)
I created a custom image with ublock standard enabled, but that shouldn't be too big of a difference (just extra files under the /tmp/ folder.) 

```
Console.WriteLine("Hello World!");

            ChromeOptions options = new ChromeOptions();
            options.AddArguments("disable-infobars");
            options.AddArguments("load-extension=/tmp/ublock/");

            var dc = options.ToCapabilities() as DesiredCapabilities;
            dc.SetCapability("applicationName", "WithProxy");            

            var prop = dc.GetType().GetField("isSpecCompliant", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            prop.SetValue(dc, false);

            var driver = new RemoteWebDriver(new HttpCommandExecutor(new Uri("http://xxxxx.xxxxx.xxxx.138:4444/wd/hub/"), TimeSpan.FromMinutes(1)), dc);
            driver.Manage().Cookies.DeleteAllCookies();

            Task.Delay(250).Wait();
            driver.Navigate().GoToUrl("chrome://extensions/");

            var s = driver.GetScreenshot();
            File.WriteAllBytes(@"c:\temp\testip3.png", s.AsByteArray);
            
            Task.Delay(250).Wait();
            driver.Navigate().GoToUrl("https://whatismyipaddress.com/");
            Task.Delay(250).Wait();
            
            s = driver.GetScreenshot();
            File.WriteAllBytes(@"c:\temp\testip4.png", s.AsByteArray);

            driver.Quit();
            Console.WriteLine("Returning driver");
```

**Comment by diemol** [comment]
I tried the same as @AndreSteenbergen and got the same results.

@tnguyen14 please reopen if you have more information about it.

**Comment by tnguyen14** [comment]
Apologies for the late response.

I've tried again with the latest version `3.7.1`, and can confirm that when I set `http_proxy`, `https_proxy` and `no_proxy` as environment variables, Chrome now respects this.

**Comment by YancyGo** [comment]
I use 3.11.0，got the same results, chrome does not respect http proxy environment variables

**Comment by ddavison** [comment]
@YancyGo does this happen with the most recent version(s)?  we are up to 3.14.0.  if so, at @diemol 's consent, we can reopen

**Comment by diemol** [comment]
Reopening to investigate, also since there is a long standing PR that should solve this. #699

**Comment by diemol** [comment]
OK, so I started a hub and a Chrome node with the following docker-compose file (without any proxy config):

```
version: '2'
services:
  chrome:
    image: selenium/node-chrome-debug:3.14.0-arsenic
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.14.0-arsenic
    ports:
      - "4444:4444"
```
and then I checked my IP and I got (as expected):
![without-proxy-config-chrome](https://user-images.githubusercontent.com/5992658/44423421-5da38b80-a586-11e8-95b8-6dbf153a545e.png)

Then, I went to https://free-proxy-list.net/ to get a random proxy to use in my test:
![free-proxy-list](https://user-images.githubusercontent.com/5992658/44423473-790e9680-a586-11e8-8a4c-14d67c549a8f.png)

and I started a hub and a Chrome node with proxy configuration:
```
version: '2'
services:
  chrome:
    image: selenium/node-chrome-debug:3.14.0-arsenic
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      HTTP_PROXY: "http://167.114.56.169:80"
      HTTPS_PROXY: "https://167.114.56.169:80"
      NO_PROXY: "localhost,127.0.0.1,localaddress,.localdomain.com"

  hub:
    image: selenium/hub:3.14.0-arsenic
    ports:
      - "4444:4444"
```

and I checked my IP again:
![with-proxy-config-chrome](https://user-images.githubusercontent.com/5992658/44423544-a0656380-a586-11e8-988c-d6cfa39b5c2c.png)

This shows that Chrome is not ignoring the proxy environment variables.

In any case that Chrome is actually not doing it, please open a new issue with complete information on how to reproduce the issue. 

Closing this issue again then.
