### ISSUE TITLE
Is there a benchmark of hardware/configuration for proper running selenium grid?

### ISSUE THREAD

**Issue by pammismail** [SeleniumHQ/docker-selenium#549]
is there a guideline or benchmark on optimal usage of selenium grid w.r.t to a specific configuration. 

eg. 

if host machine has 2 CPU, 8 GB RAM - it can run 4 selenium containers(assume selenium-chrome-debug) without much problems on RAM, CPU and can run for several hours?. 

The reason for posting questions is, we either always overload hub with too many containers that ultimately leads to slow running tests/skipping tests or don't use the existing capability. Most of it currently is trial and error method, which needs some patience. 

If the above question requires little more information, I'll be happy to provide.

**Comment by Zechtitus** [comment]
I've found that in aws using a C4 2xlarge was decent for running 15 chrome containers. I've actually had more luck running the node-chrome-debug containers than the node-chrome (the docs say the debug shouldn't be used).

I still end up having the EC2 container crash after several days though and have not figured out what the best setup is currently for running. My company used to have an internal hypervisor that was used for hosting the selenium grid bank of my chrome containers and it was much more reliable.

here is my config I use for the chrome containers that I have.

common.yaml
```
version: "2"

services:
  chrome:
    image: selenium/node-chrome-debug:latest
    volumes:
      - $PWD/shared_files:/shared
      - /dev/shm:/dev/shm
      - /dev/urandom:/dev/random
    shm_size: 2G
    privileged: true
    environment:
      JAVA_OPTS: -Xmx512m
      DBUS_SESSION_BUS_ADDRESS: /dev/null
      HUB_PORT_4444_TCP_ADDR: selenium-hub.use1.dev.inv.iacp.io
      HUB_PORT_4444_TCP_PORT: 4444
      no_proxy: localhost
      HUB_ENV_no_proxy: localhost
      SCREEN_WIDTH: 1600
      SCREEN_HEIGHT: 1200
```

docker-compose.yaml (repeat chrome 1 thru to chrome 15)
```
services:
  chrome1:
    extends:
      file: common.yml
      service: chrome
    ports:
      - "13001:5900"
      - "5001:5001"
    environment:
      SE_OPTS: -host xxx.xxx.xxx.xxx -port 5001

...
```
