### ISSUE TITLE
Fail to set maxInstances and maxSession in docker chrome image

### ISSUE THREAD

**Issue by thomas-lee** [SeleniumHQ/docker-selenium#554]
## Meta -
Image(s):  

Docker-Selenium Image Version(s):  node-chrome:3.5.2-antimony

```
selenium/node-firefox-debug                                            latest              a1dbf5f50ed2        7 days ago          733 MB
selenium/node-chrome-debug                                             latest              3ccba7094ae9        7 days ago          939 MB
selenium/node-firefox                                                  latest              76693a8995ed        7 days ago          672 MB
```

OS:  MacOS

docker-compose.yaml setting which set NODE_MAX_INSTANCES and NODE_MAX_SESSION.
```
selenium-hub:
  image: selenium/hub
  environment:
    - GRID_MAX_SESSION=5
  ports:
    - "4444:4444"

chrome:
  image: selenium/node-chrome-debug
  links:
    - selenium-hub:hub
  ports:
    - "7000:5900"
  environment:
    - NODE_MAX_INSTANCES=5
    - NODE_MAX_SESSION=5
  volumes:
    - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
```

Those values are set to the docker container.
```
"Env": [
                "NODE_MAX_INSTANCES=5",
                "NODE_MAX_SESSION=5",
                "no_proxy=*.local, 169.254/16",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive",
                "DEBCONF_NONINTERACTIVE_SEEN=true",
                "TZ=UTC",
                "SCREEN_WIDTH=1360",
                "SCREEN_HEIGHT=1020",
                "SCREEN_DEPTH=24",
                "DISPLAY=:99.0",
                "NODE_PORT=5555",
                "NODE_REGISTER_CYCLE=5000",
                "NODE_POLLING=5000",
                "NODE_UNREGISTER_IF_STILL_DOWN_AFTER=60000",
                "NODE_DOWN_POLLING_LIMIT=2",
                "NODE_APPLICATION_NAME=",
                "DBUS_SESSION_BUS_ADDRESS=/dev/null",
                "LANGUAGE=en_US.UTF-8",
                "LANG=en_US.UTF-8"
            ],
```

## Expected Behavior -
Expect in the /opt/selenium/config.json still maxInstances to be 5 but now it is 1

## Actual Behavior -
```
seluser@1abb06820c99:/opt/selenium$ cat config.json
{
  "capabilities": [
    {
      "version": "60.0.3112.113",
      "browserName": "chrome",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver",
      "applicationName": ""
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 1,
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "nodePolling": 5000,
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2
}
seluser@1abb06820c99:/opt/selenium$ cat config.json
{
  "capabilities": [
    {
      "version": "60.0.3112.113",
      "browserName": "chrome",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver",
      "applicationName": ""
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 1,
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "nodePolling": 5000,
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2
}
```
