### ISSUE TITLE
Failure to provide SCREEN_WIDTH & SCREEN_HEIGHT for node-firefox-debug will not work with maximize window calls

### ISSUE THREAD

**Issue by Zechtitus** [SeleniumHQ/docker-selenium#562]
Image(s):  node-firefox-debug
Docker-Selenium Image Version(s): 3.4+
OS: OSX

## Expected Behavior -
When launching firefox with vnc and not having provided SCREEN_WIDTH & SCREEN_HEIGHT to the docker run/compose env - the calls to maximize should work.

my snippet from docker-compose with firefox connecting to dockerized hub for reference
```
  firefox:
    depends_on:
      - hub    image: selenium/node-firefox-debug:3.4
    shm_size: 2G
    environment:
      JAVA_OPTS: -Xmx512m
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      no_proxy: localhost
      GRID_BROWSER_TIMEOUT: 300000
      GRID_TIMEOUT: 300000
      SE_OPTS: -host firefox -port 5001
      SCREEN_WIDTH: 1600
      SCREEN_HEIGHT: 1200
    ports:
      - "13101:5900"
      - "5001:5001"
    links:
      - hub

  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    environment:
      PORT: 4444
      GRID_BROWSER_TIMEOUT: 300000
      GRID_TIMEOUT: 300000
      GRID_CLEAN_UP_CYCLE: 300000
      GRID_UNREGISTER_IF_STILL_DOWN_AFTER: 300000
      SE_OPTS: -browserTimeout 86400 -timeout 100
```

## Actual Behavior -
If a user does not provide SCREEN_WIDTH and SCREEN_HEIGHT the vnc view into the window will show the maximize call briefly maximize the screen then shrink back down. I did not notice this behaviour on selenium 3.3 images. Ideally a user would not need to provide these params and be able to have the window maximize (node-debug-chrome works properly this way).

Screenshot without providing SCREEN_WIDTH & SCREEN_HEIGHT
![screen shot 2017-09-08 at 9 34 39 am](https://user-images.githubusercontent.com/10325856/30219612-d8751366-9479-11e7-8b25-055af913125e.png)

Screenshot providing SCREEN_WIDTH & SCREEN_HEIGHT
![screen shot 2017-09-08 at 9 35 45 am](https://user-images.githubusercontent.com/10325856/30219629-eb22fc1c-9479-11e7-9e5b-f69e83139a14.png)

## Workaround - 
Seems the env vars SCREEN_WIDTH & SCREEN_HEIGHT need to be some value above the defaults. I tried 1600 x 1200 and this seems to work but lower values as noted in comments below - still have issues.

## Other -
Is it possible to get a complete list of available env params that we can provide to the containers? Find I have to look through google or browse through the repo source to find items... might be worth it to have a highlevel list with how it influences the container?

**Comment by diemol** [comment]
Hi @Zechtitus,

Here is my docker compose file:

```
  version: '2'
  services:
    firefox:
      image: selenium/node-firefox-debug:3.6
      depends_on:
        - hub    
      shm_size: 2G
      environment:
        JAVA_OPTS: -Xmx512m
        HUB_PORT_4444_TCP_ADDR: hub
        HUB_PORT_4444_TCP_PORT: 4444
        no_proxy: localhost
        GRID_BROWSER_TIMEOUT: 300000
        GRID_TIMEOUT: 300000
        SE_OPTS: -host firefox -port 5001
        SCREEN_WIDTH: 1600
        SCREEN_HEIGHT: 1200
      ports:
        - "13101:5900"
        - "5001:5001"
      links:
        - hub

    hub:
      image: selenium/hub:latest
      ports:
        - "4444:4444"
      environment:
        PORT: 4444
        GRID_BROWSER_TIMEOUT: 300000
        GRID_TIMEOUT: 300000
        GRID_CLEAN_UP_CYCLE: 300000
        GRID_UNREGISTER_IF_STILL_DOWN_AFTER: 300000
        SE_OPTS: -browserTimeout 86400 -timeout 100
``` 

And I can reproduce what you say when removing the env vars.

Nevertheless, if I set the env vars like this (which are the [default values](https://github.com/SeleniumHQ/docker-selenium/blob/3.6.0-americium/NodeBase/Dockerfile#L35):

```
        SCREEN_WIDTH: 1360
        SCREEN_HEIGHT: 1020
```

The issue still happens, so it is not related to passing the vars or not. It seems that it is related to Firefox (since it works well with Chrome), maybe it needs a bigger viewport to work properly. I'll try the next week with FF 57 beta to see if it is solved.
