### ISSUE TITLE
disable-infobars cannot be used in composer file

### ISSUE THREAD

**Issue by renereichenbach** [SeleniumHQ/docker-selenium#570]
## Meta -
Image(s):  
node-chrome-debug

Docker-Selenium Image Version(s):  
:3.5.3-astatine

OS: 
Windows 10 Host (docker for windows used) with an Ubuntu docker-machine

## Expected Behavior -
Using the disable-infobar parameter is deactivating in Chrome the message bar "Chrome is being controlled by automated test software".

This is one part of my docker-compose.yml file. I tried different variations of:

      SE_OPTS: "disable-infobars"
      SE_OPTS: "-disable-infobars"
      SE_OPTS: "--disable-infobars"
      SE_OPTS:  'SE_OPTS "-disable-infobars"'

```
...
... selenium hub ...
... node firefox ...
...
  nodechrome:
    image: selenium/node-chrome-debug:3.5.3-astatine
    ports:
      - 5901:5900
    links:
      - selhub:hub
    environment:
      SCREEN_WIDTH: 1360
      SCREEN_HEIGHT: 1020
      SE_OPTS: "disable-infobars"
```

## Actual Behavior -

Chrome container crashes after start with error message the parameter / option is not recognized. I checked already the entry_point.sh and it should work. Also I tried to add this parameter to the hub config instead of the Chrome one. 

By checking this here: https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/generate_config

I found out the disable-infobar is not a supported param. Please let me know how I can use this param if I spawn the container via a composer file instead of using: docker run.

Thanks

**Comment by diemol** [comment]
Hi @renereichenbach,

`SE_OPTS` are [Selenium Configuration Options](https://github.com/seleniumhq/docker-selenium#se_opts-selenium-configuration-options), so they will only alter how the Hub/Node will start, it won't have any effect in Chrome.

To achieve what you want, use the `"--disable-infobars"` flag in the ChromeOptions, I found this good [post](http://support.applitools.com/customer/en/portal/articles/2783976-%22chrome-is-being-controlled-by-automated-test-software%22-notification?t=628019) that shows you how to do it.

**Comment by renereichenbach** [comment]
Thanks for your answer. I am using Behat and if I apply the changes in the config yml file it works for me. Super cool.

```
docker:
  extensions:
    Behat\MinkExtension:
      selenium2:
        wd_host: selhub:4444/wd/hub
        capabilities:
          extra_capabilities:
            chromeOptions:
              args:
                - "--disable-infobars"
```
Enjoy
