### ISSUE TITLE
Selenium Grid configuration broken in swarm mode after upgrading to Docker 17.09.0-ce ('service name not known')

### ISSUE THREAD

**Issue by ConquerOR2** [SeleniumHQ/docker-selenium#586]
## Meta -
Image(s):  
hub, node-chrome, node-firefox
Docker-Selenium Image Version(s):  
3.6.0-americium (latest)
Docker Version:  
17.09.0-ce
OS: 
Ubuntu Server 16.04 LTS

Hi,
my Selenium Grid configuration in swarm mode got broken after upgrading Docker to version 17.09.0-ce. Hub service name that was used as env variable value - HUB_PORT_4444_TCP_ADDR is not being resolved now ('Name or service not known').

My docker-selenium.yml file is the following:
```
version: '3.0'

services:
  hub:
    image: selenium/hub
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == testhost
    ports:
      - "4444:4444"
    networks:
      - selenium-nw

  firefox:
    image: selenium/node-firefox
    deploy:
      replicas: 1
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5555" /opt/bin/entry_point.sh'
    ports:
      - "5555:5555"
    networks:
      - selenium-nw

  chrome:
    image: selenium/node-chrome
    deploy:
      replicas: 1
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5556" /opt/bin/entry_point.sh'
    ports:
      - "5556:5556"
    networks:
      - selenium-nw
	  
networks:
  selenium-nw:
    external: true
```

## Expected Behavior -
Normally, after running
`docker stack deploy -c docker-selenium.yml grid`
Selenium Grid was set up and could be successfully used.

## Actual Behavior -
After upgrading docker, hub is set up normally, but nodes cannot register to the hub. It looks as if HUB_PORT_4444_TCP_ADDR variable is not set properly (hub service name is not resolved). Log from node (issue refers to both node-chrome and node-firefox) is the following:
```
INFO - Registering the node to the hub: http://hub:4444/grid/register
INFO - Couldn't register this node: Error sending the registration request: hub
INFO - Couldn't register this node: The hub is down or not responding: hub
INFO - Couldn't register this node: The hub is down or not responding: hub: Name or service not known
```
With previous version of Docker registration url was the same, but node was being successfully registered.

Do you have any ideas how to fix this issue?
