### ISSUE TITLE
Openshift Selenium HUB 3.4.0 incorrectly display configured parameters in console

### ISSUE THREAD

**Issue by jared-ziqxu** [SeleniumHQ/docker-selenium#611]
## Meta -
Image(s):  Selenium Hub 3.4.0
A Selenium hub is configured in my openshift using the template at the bottom.
The parameters of Selenium hub can be displayed correctly while using oc command line,
or check from the web console of openshift. However, the configuration displayed by Grid console is always different from this. E.g. the browserTimeout can never be changed. It always equal 0 in grid console, while equal 60 in openshift yaml template, oc command line, and openshift webgui. 
It shows:
```
    Environment:
      JAVA_OPTS:				-Xmx512m
      POOL_MAX:					30000
      GRID_NEW_SESSION_WAIT_TIMEOUT:		30
      GRID_JETTY_MAX_THREADS:			100
      GRID_NODE_POLLING:			150
      GRID_CLEAN_UP_CYCLE:			300
      GRID_TIMEOUT:				300
      GRID_BROWSER_TIMEOUT:			60
      GRID_MAX_SESSION:				3
      GRID_UNREGISTER_IF_STILL_DOWN_AFTER:	500
```

## Expected Behavior -
The Selenium Grid Console should also display the parameters, such as browserTimeout=60, timeout=30 etc.
## Actual Behavior -
The Selenium Grid Console always displays no matter how I modify the openshift configure via yaml or webGUI. 
The Selenium Hub configuration displayed by Gird Console never changes accordingly.
```
Config for the hub :
browserTimeout : 0
debug : false
help : false
jettyMaxThreads : -1
port : 4444
role : hub
timeout : 30
cleanUpCycle : 5000
host : 10.128.3.60
maxSession : 5
hubConfig : /opt/selenium/config.json
capabilityMatcher : org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout : -1
throwOnCapabilityNotPresent : true
```
## Openshift Template
I also tried template from[ this link](https://github.com/ddavison/selenium-openshift-templates/blob/master/selenium-hub.yaml).
```
apiVersion: v1
kind: Template
metadata:
  name: selenium-hub 
objects:
- apiVersion: v1
  kind: Route
  metadata:
    name: ${SELENIUM_HUB_NAME}-route
  spec:
    host: ${SELENIUM_HUB_NAME}.url.com
    to:
      kind: Service
      name: ${SELENIUM_HUB_NAME}-service
    port:
      targetPort: web
- apiVersion: v1
  kind: DeploymentConfig
  metadata: 
    name: ${SELENIUM_HUB_NAME}
  spec:
     replica: 1
     strategy:
       type: Recreate
     triggers:
       - type: ConfigChange
     template:
       metadata:
         name: ${SELENIUM_HUB_NAME} 
         labels:
           service: ${SELENIUM_HUB_NAME}
       spec:
         restartPolicy: Always
         containers:
         - image: selenium/hub:${SELENIUM_VERSION}
           name: ${SELENIUM_HUB_NAME}
           env:
           - name: JAVA_OPTS
             value: -Xmx512m
           - name: POOL_MAX
             value: "30000"
           - name: GRID_NEW_SESSION_WAIT_TIMEOUT
             value: "30"
           - name: GRID_JETTY_MAX_THREADS
             value: "100"
           - name: GRID_NODE_POLLING
             value: "150"
           - name: GRID_CLEAN_UP_CYCLE
             value: "300"
           - name: GRID_TIMEOUT
             value: "300"
           - name: GRID_BROWSER_TIMEOUT
             value: "60"
           - name: GRID_MAX_SESSION
             value: "4"
           - name: GRID_UNREGISTER_IF_STILL_DOWN_AFTER
             value: "500"
           ports:
           - containerPort: 4444
             protocol: TCP
           livenessProbe:
             failureThreshold: 3
             httpGet:
               path: /
               port: 4444
               scheme: HTTP
             periodSeconds: 10
             successThreshold: 1
             timeoutSeconds: 5
             initialDelaySeconds: 15
           readinessProbe:
             failureThreshold: 3
             httpGet:
               path: /
               port: 4444
               scheme: HTTP
             periodSeconds: 10
             successThreshold: 1
             timeoutSeconds: 5
             initialDelaySeconds: 15
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: ${SELENIUM_HUB_NAME}
    name: ${SELENIUM_HUB_NAME}-service
  spec:
    selector:
      service: ${SELENIUM_HUB_NAME}
    type: ClusterIP
    ports:
    - name: web
      port: 4444
      targetPort: 4444
      protocol: TCP
    - name: node
      port: 5555
      targetPort: 5555
      protocol: TCP
parameters:
- description: Specific name of the Selenium hub application
  displayName: Selenium Hub Service Name
  name: SELENIUM_HUB_NAME
  value: selenium-hub-sandbox
  required: true
- description: Version of Selenium Hub
  displayName: Version of Selenium Hub
  name: SELENIUM_VERSION
  value: 3.4.0
  required: true
```
