### ISSUE TITLE
UnknownServerException: Session [(null externalkey)] not available and is not among the last 1000 terminated sessions. Active sessions are[ext. key 0e526d85-b3e9-4395-8961-02cbe5962dde]

### ISSUE THREAD

**Issue by liyuanzao** [SeleniumHQ/docker-selenium#651]
## Meta -
Image(s):  
selenium/hub:latest
selenium/node-chrome-debug:latest
selenium/node-firefox-debug:latest
selenium/node-firefox-debug:3.7.1

Docker-Selenium Image Version(s):  
selenium/hub:latest
selenium/node-chrome-debug:latest
selenium/node-firefox-debug:latest
selenium/node-firefox-debug:3.7.1

Docker Version:  
15.05.0-0367

OS: 
LINUX

## Expected Behavior -
all should works with my simple test script.

## Actual Behavior -
chrome node works fine
firefox node not work, and error info is 

UnknownServerException: Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.
Active sessions are[ext. key 0e526d85-b3e9-4395-8961-02cbe5962dde]

======

Here's my simple test script.

```
<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use RemoteWebDriver;

class UserTest extends TestCase
{

    /**
     * @var \RemoteWebDriver
     */
    
    protected $webDriver;

	public function setUp()
    {
        $capabilities = array(\WebDriverCapabilityType::BROWSER_NAME => 'firefox');
        $this->webDriver = RemoteWebDriver::create('http://192.168.2.165:4444/wd/hub', $capabilities, 50000, 50000);
    }

    protected $url = 'https://whoer.net';

    public function testGitHubHome()
    {
        $this->webDriver->get($this->url);
        // checking that page title contains word 'GitHub'
        $this->assertContains('IP', $this->webDriver->getTitle());
    }    
    
}

```

**Comment by diemol** [comment]
Hi @liyuanzao,

Do you know if this also happens with the latest images (3.8.1-erbium)? 
And does this happen always or does one need to execute the script several times?

**Comment by liyuanzao** [comment]
Hi @diemol 
I tested a whole day today, this issues happened all version I tested in Firefox Node ( both debug and non-debug, 3.7.1 and 3.8.1 version), and I tried on my Synology NAS system (Linux) and Centos 7.

it always happen, but only for firefox which I tested above, I haven't tested more version so far. 

if you need any test about it, feel free to let me know

**Comment by xMutaGenx** [comment]
I was also able to replicate this issue with the following `docker-compose.yml`
```
version : '3'
services:
    selenium-hub:
      image: selenium/hub:3.8.1-erbium
      container_name: local-selenium-hub
      ports:
        - '4444:4444'
      environment:
        - SE_OPTS=-enablePassThrough false
    firefox:
      image: selenium/node-firefox:3.8.1-erbium
      environment:
        - HUB_PORT_4444_TCP_ADDR=local-selenium-hub
        - HUB_PORT_4444_TCP_PORT=4444
      depends_on:
        - selenium-hub
```

FF: v57.0.4
Gecko: v0.19.1.20171103

*Note*: SE_OPTS are there for our project, as Facebook Webdriver doesn't have support for W3C

Interestingly this doesn't seem to be failing when running the standalone version installed via `brew install selenium-server-standalone` (which runs Selenium v3.8.1)
