### ISSUE TITLE
Cannot connect to selenium server - Selenium Grid hangs when queuing many sessions

### ISSUE THREAD

**Issue by madjam002** [SeleniumHQ/docker-selenium#654]
## Meta -
Image(s):  
node-chrome, hub
Docker-Selenium Image Version(s):  
3.6
Docker Version:  
17.09.0-ce
OS: 
Windows 10

## Expected Behavior -
Not to hang

## Actual Behavior -
Selenium Grid hangs when queuing a couple of hundred sessions and test runs fail with "cannot connect to selenium server".

`docker-compose.yml`:
```
version: '2'

services:
  hub:
    image: selenium/hub:3.6.0-copper
    ports:
      - "45444:4444"
    environment:
      JAVA_OPTS: "-Xmx4g -Xms1g"

  chrome:
    image: selenium/node-chrome:3.6.0-copper
    depends_on:
      - hub
    ports:
      - "5900"
    shm_size: 4G
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5

      # fix for not running on macOS
      no_proxy: localhost
      HUB_ENV_no_proxy: localhost

      # turn off selenium debug logs to stop verbose base64 screenshots going in logs
      JAVA_OPTS: "-Dselenium.LOGGER.level=WARNING -Xmx4g -Xms1g"
```

Loading the hub console page after starting the containers works fine and shows the chrome node running, but as soon as ~200 sessions are queued, the page no longer loads and hangs, and test runners trying to start sessions time out with "Cannot connect to selenium server".

It's worth noting that monitoring CPU and memory usage shows around ~20% CPU usage max, and the memory tops out at 440MB/4GB allocated to the Docker for Windows Hyper-V VM, despite the Java heap memory settings in the `docker-compose.yml` files.

We are also seeing this behaviour on a Linux box with 64GB of memory and a 32 core CPU so I doubt this has anything to do with resource limitations or use of Docker for Windows.
