### ISSUE TITLE
Nodes will not connect to hub when using docker-compose f

### ISSUE THREAD

**Issue by diamantn** [SeleniumHQ/docker-selenium#667]
Image(s):  
hub + chrome + firefox (not the standalone)
Docker-Selenium Image Version(s):  
latest
Docker Version:  
17.09.0-ce
docker-compose version:
1.17.1

issue:
when using a docker-compose file, the nodes will not connect to the hub.
"Not linked with a running Hub container"
```

version: '2'

services:
  hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome-debug
    container_name: selenium-chrome
    links:
      - hub

  firefox:
    image: selenium/node-firefox-debug
    container_name: selenium-firefox
    links:
      - hub

```

default bridge configuration works:

```
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": [
                "/selenium-hub:/nervous_torvalds/hub"
            ]

"Networks": {
                "opt_default": {
                    "IPAMConfig": null,
                    "Links": [
                        "selenium-hub:hub",
                        "selenium-hub:selenium-hub"
                    ]
```

docker-compose configuration does not:

```
 "HostConfig": {
            "Binds": [],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "opt_default",
            "PortBindings": {
                "5900/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": ""
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,

"Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
```

in this file:
https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeBase/entry_point.sh
$HUB_HOST is used.
so a workaround is to add to the docker-compose.yml the line:
`environment:
      - HUB_HOST=hub`
and the containers connect just fine.
still, getting this to work with a user defined bridge would be very useful...
