### ISSUE TITLE
Unable to set NODE_MAX_INSTANCES, NODE_MAX_SESSION, GRID_MAX_SESSION using docker-compose

### ISSUE THREAD

**Issue by dave00galloway** [SeleniumHQ/docker-selenium#685]
## Meta -
Image(s):  
node-chrome & hub
Docker-Selenium Image Version(s):  
3.10.0-argon
Docker Version:  
Version 17.12.0-ce-mac49 (21995)
OS: 
OSX High Sierra

I don't really want to have to create one node per chrome/chromedriver instance, and I've read elsewhere [ #554 and #328 ] that this should be possible and has been fixed in the past. Has this regressed, or has there been a design decision to remove this capability, or have I just got the yml wrong?

## Expected Behavior -

### Given I am using this yml:-
$ vim docker-compose.yml 
```

version: '2'
services:
  chrome:
    image: selenium/node-chrome:3.10.0-argon
    volumes:
       - /dev/shm:/dev/shm
    depends_on:
       - hub
    environment:
       - NODE_MAX_INSTANCES=10
       - NODE_MAX_SESSION=10
       - HUB_HOST=hub

  hub:
    image: selenium/hub:3.10.0-argon
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=10
```
                                                                                                                                                                                                                                         
"docker-compose.yml" 20L, 368C written 

### When I start the hub and node:-
```
$ docker-compose restart
Restarting seleniumdocker_chrome_1 ... done
Restarting seleniumdocker_hub_1    ... done
```
### Then I should see that the hub and nodes can run 10 instances of chromedriver/chrome:-
extracts form docker inspect should look something like this
```
...
"Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive",
                "DEBCONF_NONINTERACTIVE_SEEN=true",
                "TZ=UTC",
                "GRID_MAX_SESSION=10",
                "GRID_NEW_SESSION_WAIT_TIMEOUT=-1",
                "GRID_THROW_ON_CAPABILITY_NOT_PRESENT=true",
                "GRID_JETTY_MAX_THREADS=-1",
                "GRID_CLEAN_UP_CYCLE=5000",
                "GRID_BROWSER_TIMEOUT=0",
                "GRID_TIMEOUT=30",
                "GRID_DEBUG=false",
                "GRID_HUB_PORT=4444"
            ],
            "Cmd": [
                "/opt/bin/entry_point.sh"
            ],
...
``` 
for the hub and
```
...
"Env": [
                "HUB_HOST=hub",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive",
                "DEBCONF_NONINTERACTIVE_SEEN=true",
                "TZ=UTC",
                "SCREEN_WIDTH=1360",
                "SCREEN_HEIGHT=1020",
                "SCREEN_DEPTH=24",
                "DISPLAY=:99.0",
                "NODE_MAX_INSTANCES=10",
                "NODE_MAX_SESSION=10",
                "NODE_PORT=5555",
                "NODE_REGISTER_CYCLE=5000",
                "NODE_POLLING=5000",
                "NODE_UNREGISTER_IF_STILL_DOWN_AFTER=60000",
                "NODE_DOWN_POLLING_LIMIT=2",
                "NODE_APPLICATION_NAME=",
                "DBUS_SESSION_BUS_ADDRESS=/dev/null"
            ],
            "Cmd": [
                "/opt/bin/entry_point.sh"
            ],
...
```
for the node
## Actual Behavior -

```
...
"Env": [
                ...
                "GRID_MAX_SESSION=5",
                ...
            ],
            "Cmd": [
                "/opt/bin/entry_point.sh"
            ],
...
``` 
for the hub and
```
...
"Env": [
                "HUB_HOST=hub",
                ...
                "NODE_MAX_INSTANCES=1",
                "NODE_MAX_SESSION=1",
                ...
            ],
            "Cmd": [
                "/opt/bin/entry_point.sh"
            ],
...
```

**Comment by lmtierney** [comment]
I'm no yml expert, but try defining them in `key: variable` in your yml file. I don't think `=` works:

```
    environment:
       - NODE_MAX_INSTANCES: 10
       - NODE_MAX_SESSION: 10
       - HUB_HOST: hub
```

**Comment by dave00galloway** [comment]
@lmtierney - thanks for the suggestion. I tried

```
version: '2'
services:
  chrome:
    image: selenium/node-chrome:3.10.0-argon
    volumes:
       - /dev/shm:/dev/shm
    depends_on:
       - hub
    environment:
       - NODE_MAX_INSTANCES: 10
       - NODE_MAX_SESSION: 10
       - HUB_HOST: hub

  hub:
    image: selenium/hub:3.10.0-argon
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION: 10
```

but this fails to load:-

```
$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.hub.environment contains {"GRID_MAX_SESSION": 10}, which is an invalid type, it should be a string
services.chrome.environment contains {"NODE_MAX_INSTANCES": 10}, which is an invalid type, it should be a string
```

**Comment by dave00galloway** [comment]
I think I've got it, at least it looks like the grid max sessions is configured correctly:-

```
version: '2'
services:
  chrome:
    image: selenium/node-chrome:3.10.0-argon
    volumes:
       - /dev/shm:/dev/shm
    depends_on:
       - hub
    environment:
       NODE_MAX_INSTANCES: 10
       NODE_MAX_SESSION: 10
       HUB_HOST: hub

  hub:
    image: selenium/hub:3.10.0-argon
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 10
```
results in 

```
$ docker-compose up
Recreating seleniumdocker_hub_1 ... done
Recreating seleniumdocker_chrome_1 ... done
Attaching to seleniumdocker_hub_1, seleniumdocker_chrome_1
hub_1     | starting selenium hub with configuration:
hub_1     | {
hub_1     |   "port": 4444,
hub_1     |   "role": "hub",
hub_1     |   "maxSession": 10,
hub_1     |   "newSessionWaitTimeout": -1,
hub_1     |   "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
hub_1     |   "throwOnCapabilityNotPresent": true,
hub_1     |   "jettyMaxThreads": -1,
hub_1     |   "cleanUpCycle": 5000,
hub_1     |   "browserTimeout": 0,
hub_1     |   "timeout": 30,
hub_1     |   "debug": false
hub_1     | }
```
and docker inspect shows:-
```
"Env": [
                "NODE_MAX_INSTANCES=10",
                "HUB_HOST=hub",
                "NODE_MAX_SESSION=10",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive",
                "DEBCONF_NONINTERACTIVE_SEEN=true",
                "TZ=UTC",
                "SCREEN_WIDTH=1360",
                "SCREEN_HEIGHT=1020",
                "SCREEN_DEPTH=24",
                "DISPLAY=:99.0",
                "NODE_PORT=5555",
                "NODE_REGISTER_CYCLE=5000",
                "NODE_POLLING=5000",
                "NODE_UNREGISTER_IF_STILL_DOWN_AFTER=60000",
                "NODE_DOWN_POLLING_LIMIT=2",
                "NODE_APPLICATION_NAME=",
                "DBUS_SESSION_BUS_ADDRESS=/dev/null"
            ],
```
and
```
"Env": [
                "GRID_MAX_SESSION=10",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive",
                "DEBCONF_NONINTERACTIVE_SEEN=true",
                "TZ=UTC",
                "GRID_NEW_SESSION_WAIT_TIMEOUT=-1",
                "GRID_THROW_ON_CAPABILITY_NOT_PRESENT=true",
                "GRID_JETTY_MAX_THREADS=-1",
                "GRID_CLEAN_UP_CYCLE=5000",
                "GRID_BROWSER_TIMEOUT=0",
                "GRID_TIMEOUT=30",
                "GRID_DEBUG=false",
                "GRID_HUB_PORT=4444"
            ],
```
