### ISSUE TITLE
Session [....] not available and is not among the last 1000 terminated sessions

### ISSUE THREAD

**Issue by eyalzek** [SeleniumHQ/docker-selenium#695]
## Meta -
Image(s):  
hub/node-chrome
Docker-Selenium Image Version(s):  
3.5.3-boron, 3.9.1-actinium
Docker Version:  
17.09.1-ce

I've been seeing this issue for a while now, happening randomly. I'm testing with webdriverio + mocha, running in docker. I've seen this happen when running 2 chrome nodes, but I think the problem occurs more often (but not reproducible) when I run 5 chrome nodes.

Example of the error that I'm seeing:
```
Session [95635190928628f91d62dab7595e271d] not available and is not among the last 1000 terminated sessions. Active sessions are[ext. key 4304cbbbd14fcb10fd6a6866baaf22c6, ext. key 6e5afdf576a0249056ad69d89e7ad154, ext. key e2260047ddd1461aec6c3f7986eda7b3, 85a10aad-9e02-4bcf-a567-59817ccb0865 (int. key, remote not contacted yet.)]
```

I've noticed that every time this error happens, the following message is logged by the hub:
`INFO - Removed a session that had not yet assigned an external key b9dba954-9635-4bff-b338-655f727baffc, indicates failure in session creation BROWSER_TIMEOUT`

I've tried setting `BROWSER_TIMEOUT` to 0/-1/30000, I don't think it's actually related to it. After setting the hub's log level to `DEBUG` I managed to get a bit more insight, but I'm still unsure what's exactly happening. The following gist contains part of that log, I only left the thread that failed and another thread that I think is related to the issue. If any other information is required please let me know and I will supply it:
https://gist.github.com/anonymous/d570b0eb57143c03d9f8256eeb2865bb

From my limited understanding of how the hub works, I think this is timeline of what happens:
-  session requested by 75: `10:38:20.286 DEBUG - http-outgoing-75 >> POST /wd/hub/session HTTP/1.1`
- 86 is requesting a connection but not creating a new one?:
```10:38:25.949 DEBUG - Connection request: [route: {}->http://172.18.0.7:5555][total kept alive: 0; route allocated: 1 of 2000; total allocated: 5 of 2000]
10:38:25.949 DEBUG - Connection leased: [id: 86][route: {}->http://172.18.0.7:5555][total kept alive: 0; route allocated: 2 of 2000; total allocated: 6 of 2000]
```
- 75 times out and deletes the session for some reason:
```10:38:25.956 DEBUG - http-outgoing-75 << "[read] I/O error: Read timed out"
10:38:25.956 DEBUG - http-outgoing-75: set socket timeout to 0
10:38:25.956 DEBUG - Executing request DELETE /wd/hub/session/7e54a0292efc104182ab778f2fa4e7cc HTTP/1.1
```
- at the same time 86 is trying to get that session: `10:38:25.962 DEBUG - http-outgoing-86 >> GET /wd/hub/session/7e54a0292efc104182ab778f2fa4e7cc/window/current/size HTTP/1.1`
- which is returning 200 for the first 2 requests, but in the middle is actually getting deleted by 75: `10:38:25.963 DEBUG - http-outgoing-75 >> "DELETE /wd/hub/session/7e54a0292efc104182ab778f2fa4e7cc HTTP/1.1[\r][\n]"`
- 86 at some point times out and retries the requests:
```10:38:26.003 DEBUG - http-outgoing-86 << "[read] I/O error: Read timed out"
10:38:26.003 DEBUG - http-outgoing-86: set socket timeout to 0
10:38:26.003 DEBUG - Executing request POST /wd/hub/session/7e54a0292efc104182ab778f2fa4e7cc/execute HTTP/1.1
```
- this returns the following message: `10:38:26.202 DEBUG - http-outgoing-86 << "{"sessionId":"","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 3.13.0-143-generic x86_64)"}}"`
- next it seems like 86 tries to initialize a new sessions: `10:38:26.257 DEBUG - http-outgoing-86 >> POST /wd/hub/session HTTP/1.1`
- and it looks like the hub is giving it a new session: `10:38:33.513 DEBUG - http-outgoing-86 << "{"status":0,"sessionId":"95635190928628f91d62dab7595e271d","value":{"applicationCacheEnabled":false,"rotatable":false,"mobileEmulationEnabled":false,"networkConnectionEnabled":false,"chrome":{"chromedriverVersion":"2.35.528139 `
- and then fails:
```10:38:33.514 DEBUG - Connection [id: 86][route: {}->http://172.18.0.7:5555] can be kept alive indefinitely
10:38:33.514 DEBUG - Connection released: [id: 86][route: {}->http://172.18.0.7:5555][total kept alive: 1; route allocated: 1 of 2000; total allocated: 5 of 2000]
10:38:33.593 DEBUG - Session [95635190928628f91d62dab7595e271d] not available and is not among the last 1000 terminated sessions.
Active sessions are[ext. key 4304cbbbd14fcb10fd6a6866baaf22c6, ext. key 6e5afdf576a0249056ad69d89e7ad154, ext. key e2260047ddd1461aec6c3f7986eda7b3, 85a10aad-9e02-4bcf-a567-59817ccb0865 (int. key, remote not contacted yet.)]
10:38:33.710 DEBUG - Session [95635190928628f91d62dab7595e271d] not available and is not among the last 1000 terminated sessions.
Active sessions are[ext. key 4304cbbbd14fcb10fd6a6866baaf22c6, ext. key 6e5afdf576a0249056ad69d89e7ad154, ext. key e2260047ddd1461aec6c3f7986eda7b3, 85a10aad-9e02-4bcf-a567-59817ccb0865 (int. key, remote not contacted yet.)]
10:38:33.725 DEBUG - Session [95635190928628f91d62dab7595e271d] not available and is not among the last 1000 terminated sessions.
Active sessions are[ext. key 4304cbbbd14fcb10fd6a6866baaf22c6, ext. key 6e5afdf576a0249056ad69d89e7ad154, ext. key e2260047ddd1461aec6c3f7986eda7b3, 85a10aad-9e02-4bcf-a567-59817ccb0865 (int. key, remote not contacted yet.)]
10:38:33.750 DEBUG - Session [95635190928628f91d62dab7595e271d] not available and is not among the last 1000 terminated sessions.
Active sessions are[ext. key 4304cbbbd14fcb10fd6a6866baaf22c6, ext. key 6e5afdf576a0249056ad69d89e7ad154, ext. key e2260047ddd1461aec6c3f7986eda7b3, 85a10aad-9e02-4bcf-a567-59817ccb0865 (int. key, remote not contacted yet.)]
```

Any information/suggestions on how to debug this further would be appreciated !

**Comment by loghen41** [comment]
+1 here. I haven't taken the time to dive into the debug log like @eyalzek But I have been experiencing the same error for about the last two weeks or so.

We're testing using protractor and behave, and I specifically only see this issue when I start up multiple sessions (5+) to test in parallel.

```23:50:12 [chrome #01-24] [23:50:12] I/runnerCli - Session [564a337b0773f8f8273510a48e1c3b79] not available and is not among the last 1000 terminated sessions.
23:50:12 [chrome #01-24] Active sessions are[ext. key f174e45b117e359a66ccc99043fb10ce, ext. key cf505647975e2f8162a15f31c80d21e0, ext. key cd98c8aac51adf41b413a1adc601e2c5, ext. key e4d688a4b4db6c7544be4d309214dec7, ext. key f4ca8698b3fe328984a2f2d7ec42b353, e8699ff8-8abc-4858-b51a-ee36f64bd61c (int. key, remote not contacted yet.)]```

**Comment by diemol** [comment]
Hi @eyalzek, @loghen41 

Would it be possible to have a script and the test runner configuration so we can try to reply this? Is this also happening with the latest releases? (3.11.0)?

**Comment by loghen41** [comment]
Augmenting my previous comment here: This is our Docker-compose file we're using to set up our Selenium Grid
```
hub:
  image: selenium/hub:${GRID_VERSION}
  ports:
    - "4444:4444"
  environment:
    - GRID_TIMEOUT=30000
    - GRID_BROWSER_TIMEOUT=30000
chrome:
  image: selenium/node-chrome:${GRID_VERSION}
  links:
    - hub
  shm_size: 128M
```

**Comment by eyalzek** [comment]
@diemol in my case it's a complicated testing suite that isn't written by me, which also makes it harder to debug, so it's not that straightforward to try and get a minimum reproducible example... Better go with the example given by @loghen41 . In any case, this is an example of my compose file (though I'm running 5 chrome instances, A-E):

```
version: '2.1'

networks:
  e2e:

services:
  hub:
    image: selenium/hub:3.9.1-actinium
    container_name: hub
    ports:
      - 4444:4444
    environment:
      - GRID_MAX_SESSION=20
      - GRID_TIMEOUT=12000
      - GRID_NEW_SESSION_WAIT_TIMEOUT=30000
      - GRID_DEBUG=true
      - GRID_CLEAN_UP_CYCLE=20000
    networks:
      - e2e

  chrome-A:
    image: selenium/node-chrome${CI--debug}:3.9.1-actinium
    container_name: chrome-A
    depends_on:
      - hub
    environment:
      - NODE_APPLICATION_NAME=@A
      - NODE_MAX_INSTANCES=10
      - NODE_MAX_SESSION=10
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - e2e
```
