### ISSUE TITLE
Large Number of Hung Firefox Processes

### ISSUE THREAD

**Issue by peterstory** [SeleniumHQ/docker-selenium#720]
## Meta -
Image(s):  selenium/node-firefox:3.6.0-americium
Docker Version:  Docker version 17.12.1-ce, build 7390fc6
OS: Ubuntu 16.04.4 LTS

## Expected Behavior -
Firefox containers should use a consistent amount of memory. 

## Actual Behavior -

After several days, my Firefox containers use more and more memory, until they eventually exit. Upon closer examination, this appears to be because there are a large number of hung Firefox processes in the containers. Although I've configured each container to run a single Firefox processes, after several days I observed 16 processes running! 

I'm not sure if this is a Docker-specific bug, or a problem with the Selenium Hub parent process not cleaning up its child processes properly. 

Compare the attached output from running ps in a newly started container and in a container which has been running for 3 days. 

[ps_new.txt](https://github.com/SeleniumHQ/docker-selenium/files/1890478/ps_new.txt)
[ps_3days.txt](https://github.com/SeleniumHQ/docker-selenium/files/1890479/ps_3days.txt)

**Comment by ddavison** [comment]
How are you running your containers? could you share your run command?  (docker-compose file, docker run command)

**Comment by peterstory** [comment]
I am using Docker Swarm. Here is an excerpt from my stack file:
```
  firefox-1:
    build:
      context: "./privacy-policy-retrieval"
      dockerfile: "dockerfiles/firefox.Dockerfile"
    image: mobilecommercelab/retrieval-firefox
    depends_on:
      - nginx-blacklist
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
    logging: *default-logging
    volumes:
      # Share the host's shared memory, as described here:
      #   https://github.com/moby/moby/issues/26714#issuecomment-346257988
      # Needed to prevent tabs from crashing:
      #   https://github.com/SeleniumHQ/docker-selenium/pull/485
      - "/dev/shm:/dev/shm"
```

I have a custom Dockerfile, entrypoint, and command which blacklist certain hostnames by appending to `/etc/hosts`. However, my custom command ends with the following, so I think my container will (aside from the blacklisting) behave as a vanilla node container would:

```
su - seluser
# Thanks to:
# https://github.com/SeleniumHQ/docker-selenium/issues/255#issuecomment-254417125
export SE_OPTS="-host $HOSTNAME"
exec /opt/bin/entry_point.sh
```

**Comment by peterstory** [comment]
And here is my hub configuration:

```
  selenium-hub:
    image: "selenium/hub:3.6.0-americium"
    # To see which configuration options are available:
    # https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/generate_config
    # For advice on tuning these parameters:
    # https://github.com/SeleniumHQ/selenium/wiki/Grid2#configuring-timeouts-version-221-required
    environment:
      # "ensure all resources are reclaimed 30 seconds after a client crashes"
      GRID_TIMEOUT: 30
      # "the maximum time a node is willing to hang inside the browser"
      GRID_BROWSER_TIMEOUT: 60
      # Amount of time requests will wait in the queue before being kicked out.
      # Unlike the other stats, this is in milliseconds.
      GRID_NEW_SESSION_WAIT_TIMEOUT: 75000
    logging: *default-logging
```
