### ISSUE TITLE
GRID_TIMEOUT and GRID_BROWSER_TIMEOUT not being passed to nodes

### ISSUE THREAD

**Issue by jsa34** [SeleniumHQ/docker-selenium#727]
Docker-Selenium Image Version(s):  
3.9.0 onwards

OS: 
RHEL7

## Expected Behavior -
Using the following yml, the timeouts should be passed to the nodes in the grid when spun up.

```
seleniumhub:
  image: selenium/hub:3.9.0-antimony
  ports:
    - 4444:4444
  environment:
    - GRID_BROWSER_TIMEOUT=3400
    - GRID_TIMEOUT=3600
firefox:
  image: selenium/node-firefox-debug:3.9.0-antimony
  ports:
    - 5900
  links:
    - seleniumhub:hub
chrome:
  image: selenium/node-chrome-debug:3.9.0-antimony
  ports:
    - 5900
  links:
    - seleniumhub:hub

```

## Actual Behavior -
From selenium 3.9.0 onwards the browser/node timeouts stay at the default value of 1800, but earlier version inherit the hub timeout.

e.g. the following DOES pass the timeout to the nodes

```
seleniumhub:
  image: selenium/hub:3.8.1-francium
  ports:
    - 4444:4444
  environment:
    - GRID_BROWSER_TIMEOUT=3400
    - GRID_TIMEOUT=3600
firefox:
  image: selenium/node-firefox-debug:3.8.1-francium
  ports:
    - 5900
  links:
    - seleniumhub:hub
chrome:
  image: selenium/node-chrome-debug:3.8.1-francium
  ports:
    - 5900
  links:
    - seleniumhub:hub

```

Problem is fixed by downgrading to 3.8.1.

**Comment by vv-p** [comment]
I added a bit logging to selenium-server and It looks like hub getting browserTimeout value for web-interface metrics from nodes too early:

Stage 1: hub getting browserTimeout values to show it in a web interface
```
hub_1      | 09:13:32.998 INFO [BaseRemoteProxy.<init>] - request.getConfiguration().browserTimeout = 0
hub_1      | 09:13:32.998 INFO [BaseRemoteProxy.<init>] - request.getConfiguration().browserTimeout = 0
```

Stage 2: node getting browserTimeout value from the hub and setting it:

```
chrome_1   | 09:13:33.038 INFO [SelfRegisteringRemote.registerToHub] - Updating the node configuration from the hub
chrome_1   | 09:13:33.160 INFO [SelfRegisteringRemote.registerToHub] - Got browserTimeout = 36000
chrome_1   | 09:13:33.160 INFO [SelfRegisteringRemote.registerToHub] - Set registrationRequest.getConfiguration().browserTimeout = 36000
```

**Comment by vv-p** [comment]
Does anybody know is there a method to get browsetTimeout value from a node directly ?

**Comment by kshahani** [comment]
Having the same issue, which means we're stuck on Chrome 64 if we don't want to build our own image. Does anyone have a time to resolution on when this will be addressed or fixed?

**Comment by Niceplace** [comment]
Reproduced on 3.12, here's attached docker-compose, just start it and navigate to `http://localhost:4444/grid/console/`, in the node's configuration tab, timeouts are not set at `90` like they should be.

```
version: "3"
services:
  selenium-node-chrome:
    image: selenium/node-chrome-debug:3.12
    container_name: selenium-node-chrome-1
    depends_on:
      - selenium-grid
    volumes:
      - /dev/shm:/dev/shm
      - /dev/urandom:/dev/random
    environment:
      - HUB_HOST=selenium-grid
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
      - DBUS_SESSION_BUS_ADDRESS="/dev/null"
    networks:
      - test-network
    ports:
      - 5900:5900

  selenium-grid:
    image: selenium/hub:3.12
    container_name: selenium-grid
    environment:
      - GRID_TIMEOUT=90
      - GRID_BROWSER_TIMEOUT=90
      - GRID_MAX_SESSION=2
    ports:
      - "4444:4444"
    networks:
      - test-network
```

This seems like a regression from 3.8.1 (also tested, just change the version in the docker-compose file above), we would love to upgrade our selenium grid but unfortunately we cannot because of this problem. 

@diemol @ddavison @mtscout6 I understand that there maybe are some issues that are more of a priority but is there any chance this going to be fixed soon ? Your help would be much appreciated :) !
