### ISSUE TITLE
Firefox browser isn't opening

### ISSUE THREAD

**Issue by mlagran1** [SeleniumHQ/docker-selenium#739]
## Meta -
Image(s):  selenium/node-firefox

Docker-Selenium Image Version(s): 3.12.0-boron

Docker Version:  17.12.0-ce

OS: High Sierra

## Expected Behavior -
Browser will open and execute test. 
## Actual Behavior -
Unfortunately, when I execute the scripts, the test hangs on the first scenario for a long time and then returns:
```
"Could not open connection: Notice: Undefined index".
```
Also, the grid console returns: 
```
2 requests waiting for a slot to be free.
Capabilities {browser: firefox, browserName: firefox, ignoreZoomSetting: false, name: Behat feature suite, tags: [behat, PHP 7.0.11], version: *}
Capabilities {browser: firefox, browserName: firefox, ignoreZoomSetting: false, name: Behat feature suite, tags: [behat, PHP 7.0.11], version: *}
```

I'm also using the selenium/node-chrome image and I have no issues with that one.

Here's my docker-compose and behat.yml:

*docker-compose*
```
version: "2"

services:
  # Behat
  behat:
    hostname: behat
    image: docksal/behat
    volumes:
      - .:/src
    # Run a built-in web server for access to HTML reports
    ports:
     - 8000:8000
    entrypoint: "php -S 0.0.0.0:8000"
  # Selenium
  firefox:
    image: selenium/node-firefox:3.12.0-boron
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:3.12.0-boron
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.12.0-boron
    ports:
      - "4444:4444"
```

*behat.yml*
```
extensions:
    Behat\MinkExtension:
      selenium2: ~
      default_session: selenium2
      # Configure browser. Browser must be available on wd_host.
      browser_name: firefox
      selenium2:
        wd_host: http://hub:4444/wd/hub
        capabilities: { "browser": "firefox", "version": "*"}
```
