### ISSUE TITLE
Unresolved address error with 3.13.0 containers

### ISSUE THREAD

**Issue by triesz** [SeleniumHQ/docker-selenium#755]
This docker-compose.yml works fine with 3.12.0 versions:

```
selenium-hub:

  image: selenium/hub:3.12.0
  ports:
  - 4444:4444

chrome:
  image: selenium/node-chrome:3.12.0
  links:
  - selenium-hub:hub
  ports:
  - 5900:5900
  environment:
     HUB_HOST: hub
     HUB_PORT: 4444
     SE_OPTS: -timeout 65 -browserTimeout 60 -browser browserName=chrome,maxInstances=1,platform=LINUX,applicationName=chrome-1
     REMOTE_HOST: http://chrome:5555
  volumes:
  - /dev/shm:/dev/shm

```
doker-compose up

but trying the same with 3.13.0 image versions it leads to

> chrome_1        | java.lang.RuntimeException: java.net.SocketException: Unresolved address
> chrome_1        | 	at org.openqa.selenium.remote.server.SeleniumServer.boot(SeleniumServer.java:207)
> chrome_1        | 	at org.openqa.grid.internal.utils.SelfRegisteringRemote.startRemoteServer(SelfRegisteringRemote.java:122)
> chrome_1        | 	at org.openqa.grid.selenium.GridLauncherV3$3.launch(GridLauncherV3.java:314)
> chrome_1        | 	at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:121)
> chrome_1        | 	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:81)
> chrome_1        | Caused by: java.net.SocketException: Unresolved address
> chrome_1        | 	at sun.nio.ch.Net.translateToSocketException(Net.java:131)
> chrome_1        | 	at sun.nio.ch.Net.translateException(Net.java:157)
> chrome_1        | 	at sun.nio.ch.Net.translateException(Net.java:163)
> chrome_1        | 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:76)
> chrome_1        | 	at org.seleniumhq.jetty9.server.ServerConnector.openAcceptChannel(ServerConnector.java:334)
> chrome_1        | 	at org.seleniumhq.jetty9.server.ServerConnector.open(ServerConnector.java:302)
> chrome_1        | 	at org.seleniumhq.jetty9.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
> chrome_1        | 	at org.seleniumhq.jetty9.server.ServerConnector.doStart(ServerConnector.java:238)
> chrome_1        | 	at org.seleniumhq.jetty9.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> chrome_1        | 	at org.seleniumhq.jetty9.server.Server.doStart(Server.java:397)
> chrome_1        | 	at org.seleniumhq.jetty9.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> chrome_1        | 	at org.openqa.selenium.remote.server.SeleniumServer.boot(SeleniumServer.java:196)
> chrome_1        | 	... 4 more
> chrome_1        | Caused by: java.nio.channels.UnresolvedAddressException
> chrome_1        | 	at sun.nio.ch.Net.checkAddress(Net.java:101)
> chrome_1        | 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:218)
> chrome_1        | 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
> chrome_1        | 	... 12 more

**Comment by diemol** [comment]
Right, if the variable is already quoted I imagine it will fail. It just happens that for the 3.13 release the validation of parameters needs the value to be quoted.
Will fix it and release soon.
Thanks for reporting it @triesz

**Comment by diemol** [comment]
The previous comment was based on the snippet you pasted on the commit comment, I will try to reproduce and then I'll report back.

**Comment by diemol** [comment]
I just tried with this docker-compose file:
```
version: '2'
services:
  chrome:
    image: selenium/node-chrome:3.13.0
    links:
      - selenium-hub:hub
    ports:
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
      SE_OPTS: -timeout 65 -browserTimeout 60 -browser browserName=chrome,maxInstances=1,platform=LINUX,applicationName=chrome-1
      REMOTE_HOST: http://chrome:5555      

  selenium-hub:
    image: selenium/hub:3.13.0
    ports:
      - "4444:4444"
```

and I got the following output:
```
Creating network "issue-755_default" with the default driver
Creating issue-755_selenium-hub_1 ... done
Creating issue-755_chrome_1       ... done
Attaching to issue-755_selenium-hub_1, issue-755_chrome_1
selenium-hub_1  | starting selenium hub with configuration:
selenium-hub_1  | {
selenium-hub_1  |   "host": "0.0.0.0",
selenium-hub_1  |   "port": 4444,
selenium-hub_1  |   "role": "hub",
selenium-hub_1  |   "maxSession": 5,
selenium-hub_1  |   "newSessionWaitTimeout": -1,
selenium-hub_1  |   "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
selenium-hub_1  |   "throwOnCapabilityNotPresent": true,
selenium-hub_1  |   "jettyMaxThreads": -1,
selenium-hub_1  |   "cleanUpCycle": 5000,
selenium-hub_1  |   "browserTimeout": 0,
selenium-hub_1  |   "timeout": 30,
selenium-hub_1  |   "debug": false
selenium-hub_1  | }
selenium-hub_1  | 21:08:35.083 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.13.0', revision: '2f0d292'
selenium-hub_1  | 21:08:35.086 INFO [GridLauncherV3$2.launch] - Launching Selenium Grid hub on port 4444
chrome_1        | Connecting to the Hub using the host hub and port 4444
chrome_1        | REMOTE_HOST variable is set, appending -remoteHost
chrome_1        | appending selenium options: -timeout 65 -browserTimeout 60 -browser browserName=chrome,maxInstances=1,platform=LINUX,applicationName=chrome-1
selenium-hub_1  | 2018-07-31 21:08:35.534:INFO::main: Logging initialized @951ms to org.seleniumhq.jetty9.util.log.StdErrLog
selenium-hub_1  | 21:08:35.745 INFO [Hub.start] - Selenium Grid hub is up and running
selenium-hub_1  | 21:08:35.747 INFO [Hub.start] - Nodes should register to http://172.18.0.2:4444/grid/register/
selenium-hub_1  | 21:08:35.747 INFO [Hub.start] - Clients should connect to http://172.18.0.2:4444/wd/hub
chrome_1        | 21:08:35.999 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.13.0', revision: '2f0d292'
chrome_1        | 21:08:36.005 INFO [GridLauncherV3$3.launch] - Launching a Selenium Grid node on port 5555
chrome_1        | 2018-07-31 21:08:36.178:INFO::main: Logging initialized @675ms to org.seleniumhq.jetty9.util.log.StdErrLog
chrome_1        | 21:08:36.380 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
chrome_1        | 21:08:36.380 INFO [GridLauncherV3$3.launch] - Selenium Grid node is up and ready to register to the hub
chrome_1        | 21:08:36.445 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
chrome_1        | 21:08:36.446 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://hub:4444/grid/register
selenium-hub_1  | 21:08:36.875 INFO [DefaultGridRegistry.add] - Registered a node http://chrome:5555
chrome_1        | 21:08:36.997 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
```

The difference I see is that I specify the docker-compose file version. Could that be the issue?

**Comment by triesz** [comment]
Hi @diemol ,

thanks a lot for getting back.
My above composer file was incorrect.
```
version: '2'
services:
  hub:
    image: selenium/hub:3.13.0
    ports:
    - 4444:4444
  chrome:
    image: selenium/node-chrome:3.13.0
    ports:
    - 5900:5900
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
      SE_OPTS: -timeout 65 -browserTimeout 60 -browser browserName=chrome,maxInstances=1,platform=LINUX,applicationName=chrome-1
      REMOTE_HOST: http://chrome:5555
    volumes:
    - /dev/shm:/dev/shm
```
And this way it works fine with 3.13 images as well.

I just finished my contract at the customer where I hit this prob so I cannot investigate the original (AWS) environment anymore. Please allow me a day or two, I will ping my ex-colleagues and report back here.
