### ISSUE TITLE
Selenium/hub can't recognize selenium/node-chrome-debug while in network_mode = "host"

### ISSUE THREAD

**Issue by toolowner** [SeleniumHQ/docker-selenium#761]
## Meta
Image(s): hub, node-chrome-debug
Docker-Selenium Image Version(s):  3.14.0-arsenic
Docker Version: 18.06.0-ce, build 0ffa825
OS: Ubuntu 18.04

## Expected Behavior
Node has to be added to the hub.

## Actual Behavior
It works well until I added network_mode: "host" to my docker-compose file to access my local development site. Both the hub and node started, but when I check http://localhost:4444/grid/console, there's no node. I wonder if there is any way to solve it.

```
version: "3"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    network_mode: "host"
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug:latest
    depends_on:
      - selenium-hub
    network_mode: "host"
    ports:
      - "5900:5900"
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
```
