### ISSUE TITLE
ChromeDriver throws error during startup causing no session created at node

### ISSUE THREAD

**Issue by praveen4463** [SeleniumHQ/docker-selenium#774]
Image(s):  
selenium/hub:3.14.0-arsenic
selenium/node-chrome:3.14.0-arsenic

Docker-Selenium Image Version(s):  
3.14.0-arsenic

Docker Version:  
18.06.0-ce

OS: 
Mac 10.13.6 used for running the images

_Note - I am not assuming it as a chromedriver issue cause the chromedriver is failing to start on the port inside docker during session creation which i believe must be working for image builders (contributors).
**Expected Behavior** -ChromeDriver should start inside docker and a new session created._

**Actual Behavior** -ChromeDriver is failing to start with error - 
```
[1535293492.630][SEVERE]: bind() returned an error, errno=99: Cannot assign requested address (99)

```

*Steps to reproduce -**
1) My docker-compose.yaml

```
version: "3.7"
  services:
    selenium-hub:
      image: selenium/hub:3.14.0-arsenic
      container_name: selenium-hub
      ports:
        - "4444:4444"
    chrome:
      image: selenium/node-chrome:3.14.0-arsenic
      build:
        context: .
        shm_size: '2gb'
      depends_on:
        - selenium-hub
      environment: 
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
        - SE_OPTS="-debug"
```

2) Please run `docker-compose up`

3) Simple test in node:

```
const webdriver = require('selenium-webdriver');

let driver = new webdriver.Builder()
	.forBrowser('chrome')
	.usingServer('http://localhost:4444/wd/hub')
	.build();

driver.manage().window().maximize()
	.then(_ =>  driver.get('http://www.google.com/ncr'))
	.then(_ => driver.findElement(webdriver.By.name('q')).sendKeys('webdriver', webdriver.Key.RETURN))
	.then(_ => driver.wait(webdriver.until.titleIs('webdriver - Google Search'), 1000))
	.then(_ => driver.quit())
	.catch(_err => console.log(_err));
```
4) Run the above test and the container will log following messages:

```
chrome_1        | 14:24:52.619 DEBUG [UrlChecker.waitUntilAvailable] - Waiting for [http://localhost:13939/status]
chrome_1        | 14:24:52.621 DEBUG [UrlChecker.lambda$waitUntilAvailable$1] - Polling http://localhost:13939/status
chrome_1        | Starting ChromeDriver 2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706) on port 13939
chrome_1        | Only local connections are allowed.
chrome_1        | [1535293492.630][SEVERE]: bind() returned an error, errno=99: Cannot assign requested address (99)
chrome_1        | 14:24:52.648 DEBUG [HttpURLConnection.writeRequests] - sun.net.www.MessageHeader@51fa825f5 pairs: {GET /status HTTP/1.1: null}{User-Agent: Java/1.8.0_181}{Host: localhost:13939}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
chrome_1        | 14:24:52.651 DEBUG [HttpURLConnection.getInputStream0] - sun.net.www.MessageHeader@14f816043 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 136}{Content-Type: application/json; charset=utf-8}
chrome_1        | 14:24:53.520 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
```

5) Node app will raise error 

`WebDriverError: unknown error: failed to change window state to maximized, current state is normal`

If the test doesn't run 'window maximize' and directly go to the url, the node process hangs on the doesn't get anything back.
