### ISSUE TITLE
chrome browser takes too much time to launch.

### ISSUE THREAD

**Issue by nirbhaypatil** [SeleniumHQ/docker-selenium#782]
## Meta -
chrome browser is taking too long time to launch.
Any environment variables missing from docker-composer.yml?

Image(s):  
node-chrome  standalone 
Docker-Selenium Image Version(s):  
3.13.0-argon
Docker Version:  
1.12.3, build 6b644ec
OS: 
CentOS Linux release 7.3.1611 (Core)

## Expected Behavior -
Chrome should be launch as soon as behat test is executed.

## Actual Behavior -
seluser@f40518ad324b:/$ cat /tmp/.org.chromium.Chromium.AwiKY7/chrome_debug.log
[74:90:0911/060303.341737:ERROR:bus.cc(394)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[179:179:0911/060303.541456:ERROR:sandbox_linux.cc(375)] InitializeSandbox() called with multiple threads in process gpu-process.
[74:296:0911/060303.593426:ERROR:bus.cc(394)] Failed to connect to the bus: Address does not contain a colon
[74:74:0911/060303.615448:WARNING:password_store_factory.cc(241)] Using basic (unencrypted) store for password storage. See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_password_storage.md for more information about password storage options.
[74:74:0911/060303.643755:ERROR:gpu_process_transport_factory.cc(1019)] Lost UI shared context.
[74:74:0911/060513.460657:INFO:CONSOLE(0)] "[DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.

## Steps to reproduce -
I am using a behat test on chrome browser , here is docker-compose.yml for selenium standalone server in use.
```
#selenium-hub:
# image: selenium/hub:3.11.0-bismuth
# ports:
#  - 4445:4444
# environment:
#   - DBUS_SESSION_BUS_ADDRESS=/dev/null
chrome:
  image: selenium/standalone-chrome:3.13.0-argon
  ports:
   - 4445:4444
# links:
#  - selenium-hub:hub
  volumes:
   - /dev/shm:/dev/shm
  shm_size: '2g'
  environment:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
```
