### ISSUE TITLE
Hub console hang after upgrade nodes to 3.14.0-francium 

### ISSUE THREAD

**Issue by dlgiang** [SeleniumHQ/docker-selenium#797]
Image(s):
node-chrome, hub, standalone-firefox
Docker-Selenium Image Version(s):  
3.14.0-francium
Docker Version:  
18.03.1-ce
OS: 
Centos 7

## Steps to reproduce -
Start below stack
```
version: '3.5'

services:

  hub:
    image: selenium/hub:latest
    ports:
      - 4444:4444
    deploy:
      mode: replicated
      replicas: 1
  chrome:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/urandom:/dev/random
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_SESSION=1
    deploy:
      replicas: 1
  firefox:
    image: selenium/node-firefox:latest
    volumes:
      - /dev/urandom:/dev/random
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_SESSION=1
    deploy:
      replicas: 1

```

Go go hub console
