### ISSUE TITLE
Setting width and height parameters via docker-compose doesn't seem to work?

### ISSUE THREAD

**Issue by Saeven** [SeleniumHQ/docker-selenium#813]
Hi.

Am trying to use the selenium/node-chrome-debug:3.14.0-helium image at a specific height and width.

Using this command in your documentation as guide:
`docker run -d -e SCREEN_WIDTH=1366 -e SCREEN_HEIGHT=768 -e SCREEN_DEPTH=24 selenium/standalone-firefox`

I've added these parameters to my docker-compose

```
  chrome:
    image: selenium/node-chrome-debug:3.14.0-helium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "48000:5900"
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      SCREEN_WIDTH: 1440
      SCREEN_HEIGHT: 900
      SCREEN_DEPTH: 24
    networks:
    - lemonade-testnet
```

Checking the screen via VNC, the size is always the same.  

How can I change the screen size via docker-compose?

Thank you!

**Comment by Patabugen** [comment]
For what it's worth that syntax is working for me using the same version. I'm on Windows 10.

I'm not sure what might be going wrong on yours - but have you tried destroying the existing container and re-creating from scratch? Also worth checking that your VNC client isn't scaling/changing the resolution when you connect.

Finally - just to clarity, are you talking about the desktop resolution or the browser window size?

```
  chrome:
    image: selenium/node-chrome-debug:3.14.0-helium
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
    ports:
      - "5900:5900"
```
