### ISSUE TITLE
Selenium Hub does not set Chrome window size properly

### ISSUE THREAD

**Issue by Patabugen** [SeleniumHQ/docker-selenium#818]
## 🐛 Bug Report
When using `selenium/hub:3.12.0-cobalt` and `selenium/node-chrome-debug:3.14.0-helium` (or the non-debug version) Chrome does not set the window size properly. When using `selenium/standalone-chrome:3.14.0-helium` instead it does.

## To Reproduce

Save this to `docker-compose.yml` and build it with `docker-compose`:

```
# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: "3.6"
services:
  selenium-hub:
    image: selenium/hub:3.14.0-helium
    container_name: selenium-hub
    hostname: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug:3.14.0-helium
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    ports:
      - "5900:5900"
```

Then to make a simple test, in a temporary directory and grab the basic dependencies:

`mkdir selenium-test`
`cd selenium-test`
`composer require facebook/webdriver`
`touch index.php`

then save this to `index.php` and run `php index.php`
```
<?php

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\Chrome\ChromeOptions;

require "vendor/autoload.php";

$options = (new ChromeOptions)->addArguments([
    '--disable-gpu',
    '--headless',
    '--window-size=1920,1080'
]);


$driver = RemoteWebDriver::create(
    'http://localhost:4444/wd/hub', DesiredCapabilities::chrome()->setCapability(
        ChromeOptions::CAPABILITY, $options
    )
);

$screenshotFile = __DIR__."/screenshot.png";

$driver->get('https://www.seleniumhq.org/');
$driver->takeScreenshot($screenshotFile);
$driver->quit();

var_dump(getimagesize($screenshotFile));
```

The output will look something like this:
```
php .\index.php
array(6) {
  [0]=>
  int(937)
  [1]=>
  int(931)
  [2]=>
  int(3)
  [3]=>
  string(24) "width="937" height="931""
  ["bits"]=>
  int(8)
  ["mime"]=>
  string(9) "image/png"
}
```
## Expected behavior

The output from `php index.php` includes `getimagesize()` - showing the size of the saved screenshot. It should say "1920x1080" as requested, but it does not. However when using `standalone-chrome` (see below for `docker-compose.yml` file) it works as expected - without output like this:

```
php .\index.php
array(6) {
  [0]=>
  int(937)
  [1]=>
  int(931)
  [2]=>
  int(3)
  [3]=>
  string(24) "width="1920" height="1080""
  ["bits"]=>
  int(8)
  ["mime"]=>
  string(9) "image/png"
}
```

## Test script reproducing this issue (when applicable)

Now replace `docker-compose.yml` with the following:

```
# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: "3.6"
services:
  chrome:
    image: selenium/standalone-chrome:3.14.0-helium
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    ports:
      - "4444:4444"
```

Run `docker-compose stop` and `docker-compose up` to start the new (now standalone) selenium server.

Then run `php index.php` again - and you should see that the screensize is now correctly set.

## Environment

OS: Windows 10 using Linux based Docker.
Docker-Selenium image version: `selenium/node-chrome-debug` and  `selenium/hub:3.14.0-helium`

Docker version: 18.06.1-ce, build e68fc7a
Docker-Compose version (if applicable): 1.22.0, build f46880fe
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): See above

**Comment by diemol** [comment]
Hi @Patabugen,

I just tried to do a simple manual check, to see if the screen resolution is actually being set:


![screencast 2018-10-22 22-10-14](https://user-images.githubusercontent.com/5992658/47317308-852bd880-d649-11e8-91b2-57b28f3217a4.gif)

Are you sure that the Chrome options are properly passed? What does the container log say? If the options are not properly passed, then the screenshot will have the size of the current viewport.

**Comment by Patabugen** [comment]
Hey,

The problem isn't the containers screen resolution being set - it's Chrome's window size not being opened to the resolution requested by WebDriver.

With standalone-chrome it works, but with node-chrome it doesn't (with exactly the same control script).

The logs appear to be very similar:
## Standalone Chrome:
```
...emp\selenium\selenium-test> docker-compose up
Creating selenium-test_chrome_1 ... done
Attaching to selenium-test_chrome_1
chrome_1  | 2018-10-23 10:48:09,238 WARN Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
chrome_1  | 2018-10-23 10:48:09,242 INFO supervisord started with pid 9
chrome_1  | 2018-10-23 10:48:10,246 INFO spawned: 'xvfb' with pid 12
chrome_1  | 2018-10-23 10:48:10,249 INFO spawned: 'selenium-standalone' with pid 13
chrome_1  | 10:48:10.616 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.14.0', revision: 'aacccce0'
chrome_1  | 2018-10-23 10:48:10,618 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1  | 2018-10-23 10:48:10,618 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1  | 10:48:10.618 INFO [GridLauncherV3$1.launch] - Launching a standalone Selenium Server on port 4444
chrome_1  | 2018-10-23 10:48:10.728:INFO::main: Logging initialized @453ms to org.seleniumhq.jetty9.util.log.StdErrLog
chrome_1  | 10:48:10.964 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
chrome_1  | 10:48:15.923 INFO [ActiveSessionFactory.apply] - Capabilities are: {
chrome_1  |   "browserName": "chrome",
chrome_1  |   "chromeOptions": {
chrome_1  |     "binary": "",
chrome_1  |     "args": [
chrome_1  |       "--disable-gpu",
chrome_1  |       "--headless",
chrome_1  |       "--window-size=1920,1080"
chrome_1  |     ]
chrome_1  |   }
chrome_1  | }
chrome_1  | 10:48:15.925 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
chrome_1  | Starting ChromeDriver 2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac) on port 21360
chrome_1  | Only local connections are allowed.[
chrome_1  | 1540291695.980][SEVERE]: bind() returned an error, errno=99: Cannot assign requested address (99)
chrome_1  | 10:48:16.611 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
chrome_1  | 10:48:17.006 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 83e5baed6f33bade6d98fc20830aa7d1 (org.openqa.selenium.chrome.ChromeDriverService)
chrome_1  | 10:48:18.388 INFO [ActiveSessions$1.onStop] - Removing session 83e5baed6f33bade6d98fc20830aa7d1 (org.openqa.selenium.chrome.ChromeDriverService)
Gracefully stopping... (press Ctrl+C again to force)
Stopping selenium-test_chrome_1 ... done
```

## Node Chrome:
```
...emp\selenium\selenium-test> docker-compose up
Creating test-selenium-hub ... done
Creating selenium-test_test-chrome_1 ... done
Attaching to test-selenium-hub, selenium-test_test-chrome_1
test-selenium-hub    | 2018-10-23 10:47:02,387 WARN Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
test-selenium-hub    | 2018-10-23 10:47:02,389 INFO supervisord started with pid 9
test-chrome_1        | 2018-10-23 10:47:03,387 WARN Included extra file "/etc/supervisor/conf.d/selenium-debug.conf" during parsing
test-chrome_1        | 2018-10-23 10:47:03,387 WARN Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
test-chrome_1        | 2018-10-23 10:47:03,389 INFO supervisord started with pid 10
test-selenium-hub    | 2018-10-23 10:47:03,391 INFO spawned: 'selenium-hub' with pid 12
test-selenium-hub    | Starting Selenium Hub with configuration:
test-selenium-hub    | 2018-10-23 10:47:03,405 INFO success: selenium-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
test-selenium-hub    | {
test-selenium-hub    |   "host": "0.0.0.0",
test-selenium-hub    |   "port": 4444,
test-selenium-hub    |   "role": "hub",
test-selenium-hub    |   "maxSession": 5,
test-selenium-hub    |   "newSessionWaitTimeout": -1,
test-selenium-hub    |   "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
test-selenium-hub    |   "throwOnCapabilityNotPresent": true,
test-selenium-hub    |   "jettyMaxThreads": -1,
test-selenium-hub    |   "cleanUpCycle": 5000,
test-selenium-hub    |   "browserTimeout": 0,
test-selenium-hub    |   "timeout": 30,
test-selenium-hub    |   "debug": false
test-selenium-hub    | }
test-selenium-hub    | 10:47:03.901 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.14.0', revision: 'aacccce0'
test-selenium-hub    | 10:47:03.907 INFO [GridLauncherV3$2.launch] - Launching Selenium Grid hub on port 4444
test-selenium-hub    | 2018-10-23 10:47:04.310:INFO::main: Logging initialized @894ms to org.seleniumhq.jetty9.util.log.StdErrLog
test-chrome_1        | 2018-10-23 10:47:04,391 INFO spawned: 'xvfb' with pid 13
test-chrome_1        | 2018-10-23 10:47:04,393 INFO spawned: 'fluxbox' with pid 14
test-chrome_1        | 2018-10-23 10:47:04,395 INFO spawned: 'vnc' with pid 15
test-chrome_1        | 2018-10-23 10:47:04,396 INFO spawned: 'selenium-node' with pid 16
test-chrome_1        | 2018-10-23 10:47:04,476 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
test-chrome_1        | 2018-10-23 10:47:04,477 INFO success: fluxbox entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
test-chrome_1        | 2018-10-23 10:47:04,477 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
test-chrome_1        | 2018-10-23 10:47:04,477 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
test-chrome_1        | Connecting to the Hub using the host test-selenium-hub and port 4444
test-selenium-hub    | 10:47:04.564 INFO [Hub.start] - Selenium Grid hub is up and running
test-selenium-hub    | 10:47:04.565 INFO [Hub.start] - Nodes should register to http://172.19.0.2:4444/grid/register/
test-selenium-hub    | 10:47:04.566 INFO [Hub.start] - Clients should connect to http://172.19.0.2:4444/wd/hub
test-chrome_1        | 10:47:05.057 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.14.0', revision: 'aacccce0'
test-chrome_1        | 10:47:05.067 INFO [GridLauncherV3$3.launch] - Launching a Selenium Grid node on port 5555
test-chrome_1        | 2018-10-23 10:47:05.231:INFO::main: Logging initialized @694ms to org.seleniumhq.jetty9.util.log.StdErrLog
test-chrome_1        | 10:47:05.432 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
test-chrome_1        | 10:47:05.432 INFO [GridLauncherV3$3.launch] - Selenium Grid node is up and ready to register to the hub
test-chrome_1        | 10:47:05.506 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
test-chrome_1        | 10:47:05.507 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://test-selenium-hub:4444/grid/register
test-selenium-hub    | 10:47:05.967 INFO [DefaultGridRegistry.add] - Registered a node http://172.19.0.3:5555
test-chrome_1        | 10:47:06.087 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
test-selenium-hub    | 10:47:21.281 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: chrome, chromeOptions: {args: [--disable-gpu, --headless, --window-size=1920,1080], binary: }}
test-selenium-hub    | 10:47:21.287 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=d88750b5-b7a0-406f-98cb-4db27b9b2295, seleniumProtocol=WebDriver, browserName=chrome, maxInstances=1, platformName=LINUX, version=69.0.3497.100, applicationName=, platform=LINUX}
test-chrome_1        | 10:47:21.508 INFO [ActiveSessionFactory.apply] - Capabilities are: {
test-chrome_1        |   "browserName": "chrome",
test-chrome_1        |   "chromeOptions": {
test-chrome_1        |     "binary": "",
test-chrome_1        |     "args": [
test-chrome_1        |       "--disable-gpu",
test-chrome_1        |       "--headless",
test-chrome_1        |       "--window-size=1920,1080"
test-chrome_1        |     ]
test-chrome_1        |   },
test-chrome_1        |   "goog:chromeOptions": {
test-chrome_1        |   }
test-chrome_1        | }
test-chrome_1        | 10:47:21.510 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
test-chrome_1        | Starting ChromeDriver 2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac) on port 25127
test-chrome_1        | Only local connections are allowed.
test-chrome_1        | [1540291641.557][SEVERE]: bind() returned an error, errno=99: Cannot assign requested address (99)
test-chrome_1        | 10:47:22.429 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
test-chrome_1        | 10:47:22.837 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 3556d18558636da8694287b6d4b7269a (org.openqa.selenium.chrome.ChromeDriverService)
test-chrome_1        | 10:47:23.973 INFO [ActiveSessions$1.onStop] - Removing session 3556d18558636da8694287b6d4b7269a (org.openqa.selenium.chrome.ChromeDriverService)
Gracefully stopping... (press Ctrl+C again to force)
Stopping selenium-test_test-chrome_1 ... done
Stopping test-selenium-hub           ... done
```

**Comment by diemol** [comment]
OK, so I think I get the issue, divided in two parts.
If it works in the Standalone because it is a different path in the code, which is something we are going to change in the near future with the development of the new Grid. Most of the people are using the combination of Hub + Nodes.

Now, it does not work in the Node, because the bindings you are using somehow are not prefixing the `chromeOptions` properly. Instead of `chromeOptions` it should be `goog:chromeOptions`.

**Comment by diemol** [comment]
Closing this issue as we didn't get more information about it, and the logs also show how the bindings are not sending the options properly.

**Comment by Patabugen** [comment]
Sorry - I didn't get a notification from your previous message.

The bindings and code examples above are exactly the same for both scenarios - the messages being sent to port 4444 should be identical - but the Hub is working differently.

It sounds like you're planning on making changes to the Hub in the near future which might resolve the issue so I'll just stop using the Hub until then and will try it again when those updates come out.

**Comment by bpapez** [comment]
Since switching to selenium hub 3.141.0 we are seeing the same problem. 

In docker-compose we use 
```
  chrome:
    image: selenium/node-chrome-debug:3.141.0
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5555 -timeout 1200 -browserTimeout 1200" /opt/bin/entry_point.sh'
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1200
      - NODE_PORT=5555
      - TZ=Europe/Paris  
```
and
```
  firefox:
    image: selenium/node-firefox-debug:3.141.0
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5555 -timeout 1200 -browserTimeout 1200" /opt/bin/entry_point.sh'
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1200
      - NODE_PORT=5555
      - TZ=Europe/Paris  
```

And for both browsers we suddenly sometimes do not get the wanted screen size, but sometimes get some random sizes, Notice that we do not set the window-size via the capabilities at all.  We used the version 3.14.0 before and did not encounter these problems, but the window size was always the expected one like set via the environment variables in the docker-compose file.
