### ISSUE TITLE
Laravel dusk and firefox

### ISSUE THREAD

**Issue by loic-lopez** [SeleniumHQ/docker-selenium#840]
## 🐛 Bug Report

Crashing when launching tests with firefox browser

## To Reproduce

Launch dusk laravel tests with docker-compose : 
```
# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.5-astatine
    container_name: selenium-hub
    network_mode: "host"
  chrome:
    image: selenium/node-chrome:3.141.5-astatine
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    network_mode: "host"
  firefox:
    image: selenium/node-firefox:3.141.5-astatine
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    network_mode: "host"
```
## Expected behavior

Run tests with firefox

## Environment

OS: Debian GNU/Linux 9.6 (stretch)
Docker version 18.09.0, build 4d60db4
Docker-Compose version (if applicable): 1.23.1, build b02f1306

## Log
```
selenium-hub    | 05:22:47.646 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {acceptInsecureCerts: true, browserName: firefox, enablePassThrough: false, firefox_profile: UEsDBAoAAAAAANcqbU3f9RXUMgA...}
selenium-hub    | 05:22:47.646 INFO [RequestHandler.process] - Error forwarding the new session cannot find : Capabilities {acceptInsecureCerts: true, browserName: firefox, enablePassThrough: false, firefox_profile: UEsDBAoAAAAAANcqbU3f9RXUMgA...}
selenium-hub    | org.openqa.grid.common.exception.CapabilityNotPresentOnTheGridException: cannot find : Capabilities {acceptInsecureCerts: true, browserName: firefox, enablePassThrough: false, firefox_profile: UEsDBAoAAAAAANcqbU3f9RXUMgA...}
selenium-hub    | 	at org.openqa.grid.internal.ProxySet.verifyAbilityToHandleDesiredCapabilities(ProxySet.java:153)
selenium-hub    | 	at org.openqa.grid.internal.DefaultGridRegistry.addNewSessionRequest(DefaultGridRegistry.java:217)
selenium-hub    | 	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:111)
selenium-hub    | 	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
selenium-hub    | 	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
selenium-hub    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
selenium-hub    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
selenium-hub    | 	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
selenium-hub    | 	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
selenium-hub    | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
selenium-hub    | 	at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
selenium-hub    | 	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
selenium-hub    | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
selenium-hub    | 	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
selenium-hub    | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
selenium-hub    | 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
selenium-hub    | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
selenium-hub    | 	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
selenium-hub    | 	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
selenium-hub    | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
selenium-hub    | 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
selenium-hub    | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
selenium-hub    | 	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
selenium-hub    | 	at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
selenium-hub    | 	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
selenium-hub    | 	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
selenium-hub    | 	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
selenium-hub    | 	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
selenium-hub    | 	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
selenium-hub    | 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
selenium-hub    | 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
selenium-hub    | 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
selenium-hub    | 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
selenium-hub    | 	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
selenium-hub    | 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
selenium-hub    | 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
selenium-hub    | 	at java.lang.Thread.run(Thread.java:748)
```
