### ISSUE TITLE
Chrome node not able to connect to localhost on host machine

### ISSUE THREAD

**Issue by parky128** [SeleniumHQ/docker-selenium#846]
I have setup a selenium grid and a chrome node as per the following docker-compose.yml

```
version: '2'
services:
  hub:
    image: selenium/hub:latest
    ports:
      - 4444:4444

  chromenode:
    image: selenium/node-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5900
    depends_on:
        - hub
    environment:
      HUB_HOST: hub

```
The containers run up fine, and I am attempting to use protractor with my Angular app to run tests against the grid. I am running my app locally on my host machine (using angular-cli `ng e2e` default command) and this launches on an auto assigned port, e.g `localhost:49158`

I have VNC'd in and I see the browser being launched when the tests begin, but its not able to connect to my localhost address for my host machine and the auto assigned port from angular and so obviously cannot reach my application to run the tests against.

I feel like I have misunderstood something fundamental, I assume localhost must mean something else in the chrome container, and not be linking back to localhost on my host machine. Is this possible to do? Do I need to setup a network in my docker-compose file between my host and the chrome node container?

Thanks
