### ISSUE TITLE
I can't load user-data-dir 

### ISSUE THREAD

**Issue by osvald0** [SeleniumHQ/docker-selenium#847]
## 🐛 Bug Report

I can't load chrome user custom profile when running a test.

Image(s):  
selenium/hub and selenium/node-chrome

Docker-Selenium Image Version(s):  
latest

Docker Version:  
17.09.0-ce

OS: 
Debian Stretch 

## Expected Behavior -

Load chrome custom profile when running a test.

## Actual Behavior -

The execution open a new empty profile each time.

## Steps to reproduce -

1- Run grid, nodes, etc:

```
docker network create grid
docker run -d -p 4444:4444 --net grid --name selenium-hub selenium/hub
docker run --privileged -d --net grid -e HUB_HOST=selenium-hub -e NODE_MAX_INSTANCES=5 -e NODE_MAX_SESSION=5 -v /dev/shm:/dev/shm  -v  /Users/osvaldo/profiles:/home/seluser/profiles selenium/node-chrome
```
Also using docker-compose:

```
version: "2"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug:latest
    depends_on:
      - selenium-hub
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
      - /Users/osvaldo/profiles:/home/seluser/profiles
    environment:
      - HUB_HOST=selenium-hub
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
```

2- Check I can see the host folder mapped to /home/seluser/profiles

```
docker exec b46e9fef4a61 ls /home/seluser/profiles
```

3-Run test with the following parameters:

```javascript
 options = new chrome.Options();
 options.addArguments(`user-data-dir=/home/seluser/profiles`);
 options.addArguments("disable-popup-blocking");
 options.addArguments("screenshot");

 driver = new webdriver.Builder()
            .forBrowser('chrome')
            .setChromeOptions(options)
            .usingServer('http://localhost:4444/wd/hub')
            .build();
```
Also I tried with:

```javascript
  let capabilities = webdriver.Capabilities.chrome();

        capabilities.set('goog:chromeOptions', {
            'args': [
                `--user-data-dir=/home/seluser/profiles`,
            ]
        })

        let driver = new webdriver.Builder()
            .forBrowser("chrome")
            .withCapabilities(capabilities)
            .usingServer('http://localhost:4444/wd/hub')
            .build();
```

Note:

I can load the profile using the same javascript code but running the test from the host machine.
I've opened an issue some a couple of month ago(#790 ) but without success. I follow the steps (using node instead of java) but my issue persist.

Thanks!
