### ISSUE TITLE
Invalid or unexpected token on reading prefs.js

### ISSUE THREAD

**Issue by cambiph** [SeleniumHQ/docker-selenium#854]
## To Reproduce

1. Using Firefox v46.0 follow the guide from https://github.com/SeleniumHQ/docker-selenium/wiki/How-to-use-a-Firefox-custom-profile
2. Via `about:config` set following preferences:
   * `browser.download.folderList`: `2`,
   * `browser.download.dir`: `/tmp/`,
   * `browser.download.useDownloadDir`: `true`,
   * `browser.helperApps.neverAsk.saveToDisk`: `application/pdf`,
   * `browser.download.manager.showWhenStarting`: `false`,
   * `pdfjs.disabled`: `true`
3. Run any Protractor test with Jasmine on the selenium hub firefox-node

## Expected behavior

The profile is picked up and loaded in Firefox. Preferences which are set via the profile are active in the node firefox instance.

## Test script reproducing this issue (when applicable)

```yaml
# https://github.com/SeleniumHQ/docker-selenium
version: "3"
services:
  selenium-hub:
    image: ${DOCKER_REGISTRY}selenium/hub:2.53.1-americium
    container_name: selenium-hub
    ports:
      - 4444:4444
    environment:
      - NODE_MAX_SESSION=5
      - GRID_DEBUG=false
  selenium-chrome:
    image: ${DOCKER_REGISTRY}selenium/node-chrome-debug:2.53.1-americium
    container_name: chrome
    ports:
      - 5900:5900
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - SHM-SIZE=2g
      - SCREEN_WIDTH=2560
      - SCREEN_HEIGHT=1440
      - GRID_DEBUG=false
    volumes:
      - /tmp/
      - /dev/shm/:/dev/shm/
  selenium-firefox:
    image: ${DOCKER_REGISTRY}selenium/node-firefox-debug:2.53.1-americium
    container_name: firefox
    ports:
      - 5901:5900
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - SHM-SIZE=2g
      - SCREEN_WIDTH=2560
      - SCREEN_HEIGHT=1440
      - GRID_DEBUG=true
    volumes:
      - /tmp/
      - /dev/shm/:/dev/shm/
      - ./***/src/test/resources/firefox_profiles:/tmp/firefox_profiles
  db:
    image: ${DOCKER_REGISTRY}mdillon/postgis:9.6-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=****
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  tomcat:
    build:
      context: .
      args:
        ARTIFACTORY: ${DOCKER_REGISTRY}
    container_name: tomcat
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - FQDN=tomcat
      - bamboo_selenium_grid_address=http://selenium-hub:4444/wd/hub
```
Protractor config:

```javascript
// Set preferences: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Capabilities.html#prefs-object

exports.config = {
    allScriptsTimeout: 30000,
    seleniumPort: 4444,
    seleniumAddress: "http://localhost:4444/wd/hub",
    framework: "jasmine",
    specs: ["src/test/**/*.js"],
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 30000,
        isVerbose: true,
        includeStackTrace: true
    },
    maxSessions: 1,
    baseUrl: "http://tomcat:8080/****/",
    capabilities: {
        "browserName": "firefox",
        "moz:firefoxOptions": {
            "args": ["-profile", "/tmp/firefox_profiles/3hrtd7wg.selenium"],
        }
    },
    plugins: [{
        package: "protractor-screenshoter-plugin",
        screenshotPath: "./target/screenshots",
        screenshotOnExpect: "failure",
        screenshotOnSpec: "none",
        htmlOnExpect: "none",
        htmlOnSpec: "none",
        imageToAscii: "none",
        clearFoldersBeforeTest: true
    }],

    onPrepare: function () {
        let failFast = require("jasmine-fail-fast");
        jasmine.getEnv().addReporter(failFast.init());
        return require("./onPrepare.js")(global, "firefox");
    }
};
```

Gruntfile:
```javascript
'use strict';

module.exports = function (grunt) {
    require('load-grunt-tasks')(grunt);
    grunt.loadNpmTasks('grunt-protractor-runner');
    grunt.initConfig({
       protractor: {
            builddocker: {
                options: {
                    configFile: 'protractor.build.docker.conf.js'
                }
            }
        },
        simple_smtp: {
            run: {},
            options: {
                port: 48024
            }
        }
    });

    grunt.registerTask('builddocker', [
        'simple_smtp:run',
        'protractor:builddocker'
    ]);
};
```
## Environment

* OS: OS X Mojave
* Docker-Selenium image version: node-firefox-debug:2.53.1-americium
* Docker version: 18.09.0
* Docker-Compose version (if applicable): 1.23.2
* Command to run tests: grunt buildfirefox
