### ISSUE TITLE
Fluxbox exits on restart of selenium/node-chrome-debug

### ISSUE THREAD

**Issue by McGriddle** [SeleniumHQ/docker-selenium#877]
## 🐛 Bug Report

When start or restarting a selenium/node-chrome-debug, fluxbox intermittenly exits. Chrome does not respect the full resolution of the display (in my case 1920x1080) when instantiating a driver with `--start-maximized` . Video here: https://cl.ly/3f18af . Logs here: https://cl.ly/b57b2f

## To Reproduce
commands:
```
docker-compose up -d
open vnc://:secret@localhost:5900
docker-compose restart # until fluxbox exits
```
docker-compose.yml
```
version: '3.1'
services:
  selenium-hub:
    image: selenium/hub
    restart: unless-stopped
    networks:
      app_net:
        ipv4_address: 172.50.7.2
    environment:
     - GRID_BROWSER_TIMEOUT=180
     - GRID_TIMEOUT=120
    ports:
     - 4444:4444
  selenium-node-chrome:
    image: selenium/node-chrome-debug
    depends_on:
     - selenium-hub
    networks:
      app_net:
        ipv4_address: 172.50.7.3
    environment:
     - NODE_MAX_INSTANCES=5
     - HUB_HOST=selenium-hub
     - SCREEN_WIDTH=1920
     - SCREEN_HEIGHT=1080
     - SCREEN_DEPTH=24
    ports:
     - 5900:5900
    volumes:
     - /dev/shm:/dev/shm

 
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.50.7.0/24
```

## Expected behavior

I expect fluxbox to not quit intermittently. I've tested this setup on macos and a linux box.

## Test script reproducing this issue (when applicable)

test_selenium.py
```
#!/usr/bin/python

from selenium import webdriver


options = webdriver.ChromeOptions()
options.add_argument("--start-maximized")
capabilities = options.to_capabilities()
driver = webdriver.Remote(
   command_executor='http://0.0.0.0:4444/wd/hub',
   desired_capabilities=capabilities)
driver.maximize_window()

driver.get("http://www.python.org")
```

## Environment

OS: macos 10.14.2
Docker-Selenium image version: selenium/node-chrome-debug:latest	
Also provide the docker image id 
--> 05e4c272777077c7b1a6d93bf7ca68795d807a01b7a4b19f629de92dcd3dab39
Docker version:  18.09.2, build 6247962
Docker-Compose version (if applicable):  1.23.2, build 1110ad01
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): `docker-compose up -d`
