### ISSUE TITLE
can't connect to selenium at second time

### ISSUE THREAD

**Issue by shiratsu** [SeleniumHQ/docker-selenium#893]
## 💬 Questions and Help
i would like to connect selenium which is created by docker-compose
docker-compose.yml is here
```
version: '2'

services:
  hub:
    image: selenium/hub:3.141.59-mercury
    container_name: 'selenium-hub'
    ports:
      - '4444:4444'
  chrome:
    image: selenium/node-chrome-debug:3.141.59-mercury
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    ports:
      - '5900:5900'

```

my program can connect at first
but at second time,it can't connect.

```
In HttpCommandExecutor.php line 292:

  Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName"
  :"chrome","platform":"linux","chromeOptions":{"binary":"","args":["--disable-notifications","-
  -headless","--no-sandbox"]}}}

  Operation timed out after 60001 milliseconds with 0 bytes received
```

How do i resolve?
