### ISSUE TITLE
can't connect to selenium at second time

### ISSUE THREAD

**Issue by shiratsu** [SeleniumHQ/docker-selenium#894]
## 🐛 Bug Report

i would like my program to connect selenium which is created by docker-compose
docker-compose.yml is here
```
version: '2'

services:
  hub:
    image: selenium/hub:3.141.59-mercury
    container_name: 'selenium-hub'
    ports:
      - '4444:4444'
  chrome:
    image: selenium/node-chrome-debug:3.141.59-mercury
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    ports:
      - '5900:5900'
```
then run a program.

the following error happend

```
In HttpCommandExecutor.php line 292:

  Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName"
  :"chrome","platform":"linux","chromeOptions":{"binary":"","args":["--disable-notifications","-
  -headless","--no-sandbox"]}}}

  Operation timed out after 60001 milliseconds with 0 bytes received
```

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):

## Test script reproducing this issue (when applicable)

i use facebook/webdriver(https://github.com/facebook/php-webdriver)
the program which connect to selenium is here.
```
$host = 'http://localhost:4444/wd/hub';
$capabilities = DesiredCapabilities::chrome();

            $options = new ChromeOptions();
            $options->addArguments(
                array(
                    '--disable-notifications',
                    '--headless',
                    '--no-sandbox',
                )
            );
            $capabilities->setPlatform($this->argument('platform'));

            $capabilities->setCapability(ChromeOptions::CAPABILITY, $options);
            $this->_driver = RemoteWebDriver::create($host, $capabilities, 60 * 1000, 60 * 1000); 
```

## Environment

OS: my pc is OSX
```
➜  ~ docker -v
Docker version 18.09.2, build 6247962
➜  ~ docker-compose -v
docker-compose version 1.23.2, build 1110ad01
```

how to start docker
```
/usr/local/bin/docker-compose -f docker-compose.yml build

/usr/local/bin/docker-compose -f docker-compose.yml up -d --force-recreate --remove-orphans
```

**Comment by shiratsu** [comment]
if this post has not enough info i'm sorrt¥y

**Comment by diemol** [comment]
@shiratsu why don't you provide detailed steps on how to reproduce?
Moreover, I see you are using PHP, and it is known that those driver bindings are not working properly with recent versions of Selenium, please check https://github.com/facebook/php-webdriver/issues/469. See if they provide a workaround for it.

**Comment by newsiberian** [comment]
The problem appears after migration from `selenium/hub(selenium/node-chrome)` `:3.3.1-cesium to `3.141.59-mercury`. It allows to run tests first time after container was rised, but othen (not always) second attempt fails with 
```bash
POST http://selenium-hub:4444 /wd/hub/session - ENOTFOUND
Error: getaddrinfo ENOTFOUND selenium-hub selenium-hub:4444
```
We are using node.js v10 and nightwatch
nightwatch config

```json
{
  "src_folders" : ["tests/integration-new"],
  "output_folder" : "output/integration",

  "test_settings" : {
    "default" : {
      "end_session_on_fail": false,
      "skip_testcases_on_fail": false,
      "launch_url" : "http://some-container-name",
      "selenium_host"  : "selenium-hub",
      "screenshots" : {
        "enabled" : true,
        "on_failure" : true,
        "on_error" : true,
        "path" : "output/screenshots"
      },
      "desiredCapabilities": {
        "browserName": "chrome",
        "marionette": true,
        "chromeOptions": {
          "args": [
            "window-size=1280,1000",
            "headless",
            "no-sandbox",
            "disable-gpu"
          ],
          "prefs": {
            "credentials_enable_service" : false,
            "profile.password_manager_enabled" : false,
            "rotatable": true
          }
        }
      }
    }
  }
}
```
and docker compose:
```yml
version: '2.1'
services:
  selenium-hub:
    image: "selenium/hub:3.141.59-mercury"
    container_name: granatum-selenium-hub
    ports:
      - "4444:4444"
    links:
      - granatum-ng

  selenium-chrome:
    image: "selenium/node-chrome:3.141.59-mercury"
    container_name: granatum-selenium-chrome
    depends_on:
      - selenium-hub
    links:
      - selenium-hub:hub
    environment:
      HUB_HOST: hub
    volumes:
      - /dev/shm:/dev/shm
```
