### ISSUE TITLE
Python3: Firefox node image is not working

### ISSUE THREAD

**Issue by prasanth-G24** [SeleniumHQ/docker-selenium#958]
## 🐛 Bug Report

I am able to run the tests only if those tests were written in java. If they were written in python, I am getting a dns exception.

My Java code:

```
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
public class SelJavaFf {
	public static void main(String[] args) throws MalformedURLException {
		FirefoxOptions opts = new FirefoxOptions();
		WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"),opts);
                driver.get("https://www.google.com");
                JavascriptExecutor js = (JavascriptExecutor) driver;
                System.out.println(js.executeScript("return window.performance.timing;"));
                driver.quit();
	}
}
```

My Python3 code:

```from selenium import webdriver
from selenium.webdriver.firefox.options import Options as Firefox_Options
options = Firefox_Options()
capabilities = options.to_capabilities()
driver = webdriver.Remote(command_executor="http://localhost:4444/wd/hub", desired_capabilities=capabilities)
driver.get('https://www.google.com')
print(driver.execute_script("return window.performance.timing;"))
driver.quit()
```

## To Reproduce

Download python selenium package using `pip3 install selenium`
Download java selenium jar with this [url](https://selenium-release.storage.googleapis.com/3.9/selenium-server-3.9.1.zip)

## Expected behavior

I am trying to obtain the performance timing of the loaded site. But instead I'm getting Message: 

> Reached error page: about:neterror?e=netTimeout&u=
followed by a broken URL. 

This is happening only in Python3. In Java, it works fine.

## Test script reproducing this issue (when applicable)

I am getting this error in the docker logs

> Error: Polling for changes failed

## Environment

OS: Ubuntu 18.04 and CentOS 7
Docker-Selenium image version: 3.141.59-titanium 
Docker image id: sha256:60ebe2031f127228402c1ab6e0ae76088f6934bea08b2b864695ff86137b2c9f
Docker version: 17.09.0-ce
Docker-Compose version: 1.24.1
docker-compose.yaml file:

```
version: '2'
services:
  firefox:
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5
  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
```
command: `docker-compose up -d`
