### ISSUE TITLE
Docker Images tag for browser versioning

### ISSUE THREAD

**Issue by zhilyaev** [SeleniumHQ/docker-selenium#992]
## 🚀 Feature Proposal

Browser versioning

## Motivation

Testing with different browser version

## Example
docker pull selenium/node-chrome:v78.0
docker pull selenium/node-chrome:v77.0
docker pull selenium/node-firefox:v71.0

### Java
```java
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setBrowserName("chrome");
capabilities.setVersion("78.0");
```

### Docker-compose
```yaml
version: '2'
services:

  chrome-64:
    container_name: chrome
    image: selenium/node-chrome:v64.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      
  chrome-78:
    container_name: chrome
    image: selenium/node-chrome:v78.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    container_name: selenium
    image: selenium/hub
    ports:
      - "4444:4444"
```
